### PR TITLE
 Archive coverage data alongside corpus archives (from AFL++ fork)

### PR DESCRIPTION
**Pull request by addisoncrump**
Supercedes #2020. Moving so we (AFL++ people) can collaborate on this PR.

From the original:

> Currently, only corpora are saved in the archive and the summaries of coverage are provided at the end of the experiment. This change simply incorporates the saving of the coverage data snapshots next to the trial corpus snapshots.

### CODE REVIEW

**Comment by addisoncrump** [comment]
@DonggeLiu Can we try to do a baseline experiment with this PR again? :slightly_smiling_face: It is fully rebased to the latest changes.

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-17-2028-bases-1 --fuzzers afl aflplusplus libafl libfuzzer

**Comment by DonggeLiu** [comment]
Hi @addisoncrump,I started a test exp above.
Experiment `2024-08-17-2028-bases-1` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-17-2028-bases-1/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-17-2028-bases-1/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-17-2028-bases-1/index.html).

If it works well and you'd like to run a full exp (23 hours), could you please rebase to adopt [this change](https://github.com/google/fuzzbench/commit/782b36195db07990654d9a0f312ca409efea7fde)?
I forgot to revert temp changes in a previous PR.

Thanks!

**Comment by addisoncrump** [comment]
Rebased. The experiment looks good, all the coverage samples were archived.

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-19-2028-bases-1 --fuzzers afl aflplusplus libafl libfuzzer

**Comment by DonggeLiu** [comment]
Experiment `2024-08-19-2028-bases-1` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-19-2028-bases-1/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-19-2028-bases-1/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-19-2028-bases-1/index.html).

**Comment by addisoncrump** [comment]
It seems to still not be hitting the measurer...

**Comment by DonggeLiu** [comment]
This is a really strange, because [`2024-08-19-2028-bases-1`](https://pantheon.corp.google.com/logs/query;query=2024-08-19-2028-bases-1%0Aseverity%3E%3DERROR%0A--Hide%20similar%20entries%0A-%2528jsonPayload.message%3D~%22Error%20watching%20metadata:%20context%20canceled%22%2529%0A--End%20of%20hide%20similar%20entries;cursorTimestamp=2024-08-19T03:03:15.897809447Z;duration=P7D?project=fuzzbench&e=-13802955&mods=logs_tg_prod) has a list of errors about merging coverage summary:
image

But [`2024-08-17-2028-bases-1`](https://pantheon.corp.google.com/logs/query;query=2024-08-17-2028-bases-1%0Aseverity%3E%3DERROR%0A--Hide%20similar%20entries%0A-%2528jsonPayload.message%3D~%22Error%20watching%20metadata:%20context%20canceled%22%2529%0A--End%20of%20hide%20similar%20entries;cursorTimestamp=2024-08-17T10:15:05.959814551Z;duration=P7D?project=fuzzbench&e=-13802955&mods=logs_tg_prod) did not have any:
image

**Comment by DonggeLiu** [comment]
QQ: Is the only thing change between those 2 experiments?
image


BTW, I noticed this runtime crash in libafl. I don't think it could cause the failure, but it might be interesting to you:
https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-19-2028-bases-1/experiment-folders/libxml2_xml-libafl/trial-3070882/results/

It did not happen in [2024-08-17-2028-bases-1](https://pantheon.corp.google.com/logs/query;query=2024-08-17-2028-bases-1%0Aseverity%3E%3DERROR%0A--Hide%20similar%20entries%0A-%2528jsonPayload.message%3D~%22Error%20watching%20metadata:%20context%20canceled%22%2529%0A--End%20of%20hide%20similar%20entries;cursorTimestamp=2024-08-17T10:15:05.959814551Z;duration=P7D?project=fuzzbench&e=-13802955&mods=logs_tg_prod), maybe because that experiment was very short?

**Comment by addisoncrump** [comment]
@tokatoka random libafl crash :upside_down_face:

**Comment by addisoncrump** [comment]
I confirmed that the only difference is that commit, yes.

Let's add some more debugging and run a very short run with all the benchmarks, I guess?

**Comment by tokatoka** [comment]
ohh i see. so this is why my experiment didn't complete either

**Comment by tokatoka** [comment]
> A possible theory: libafl saved some input into its corpus during this crash, which caused measurement failure?

but it should not affect aflplusplus runs right?

**Comment by tokatoka** [comment]
> @tokatoka random libafl crash 🙃
can you reproduce?
i used the same setup on fuzzbench but cannot reproduce

**Comment by tokatoka** [comment]
I updated. @DonggeLiu 
Could you run the same command again to see if it fixes the problem or not?

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-22-2028-bases-1 --fuzzers libafl

**Comment by DonggeLiu** [comment]
> A possible theory: libafl saved some input into its corpus during this crash, which caused measurement failure?

Also running an experiment without `libafl` to help verify this theory.

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-22-2028-bases-2 --fuzzers afl aflplusplus libfuzzer

**Comment by DonggeLiu** [comment]
Experiment `2024-08-22-2028-bases-1` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-22-2028-bases-1/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-22-2028-bases-1/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-22-2028-bases-1/index.html).

Experiment `2024-08-22-2028-bases-2` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-22-2028-bases-2/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-22-2028-bases-2/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-22-2028-bases-2/index.html).

**Comment by addisoncrump** [comment]
bases-1 seems to be working fine, but bases-2 is not hitting the measurer still.

**Comment by tokatoka** [comment]
so it looks like the libafl crash is not the cause of this

**Comment by DonggeLiu** [comment]
Ops there were a DB issue yesterday which affected both experiments.
Let me re-run them

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-23-2028-libafl --fuzzers libafl

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-23-2028-bases --fuzzers afl aflplusplus libfuzzer

**Comment by tokatoka** [comment]
we have experiment-folder but not report. so the measurement is still broken

**Comment by tokatoka** [comment]
2024-08-23-2028-libafl and 2024-08-23-2028-bases is missing
but 2024-08-23-2036-bases-1 (from the other PR) is there

**Comment by tokatoka** [comment]
Btw if the experiment on my branch and https://www.fuzzbench.com/reports/experimental/2024-08-23-dgfuzz/index.html ← this experiment are working. would it be possible that the changes in this PR caused the measurement failure??

**Comment by DonggeLiu** [comment]
Experiment `2024-08-23-2028-libafl` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-23-2028-libafl/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-23-2028-libafl/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-23-2028-libafl/index.html).

Experiment `2024-08-23-2028-bases` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-23-2028-bases/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-23-2028-bases/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-23-2028-bases/index.html).

**Comment by DonggeLiu** [comment]
@addisoncrump would this happen to be related to this PR?
image

**Comment by addisoncrump** [comment]
I'm really not sure how it could be. I think it will require manual inspection to understand the root cause here. I don't really understand why this would work locally but not in the cloud environment for these reasons, since we should expect the same errors.

Looking at the changeset: I don't see why anything I did would have affected this, *especially* since we see inconsistent generation of reports. The only thing I can think of that might cause this would be rate limiting with the bucket or similar.

**Comment by DonggeLiu** [comment]
> Looking at the changeset: I don't see why anything I did would have affected this, _especially_ since we see inconsistent generation of reports. The only thing I can think of that might cause this would be rate limiting with the bucket or similar.

Yep, I did not think of any reason from this PR either. Yet this seems to be the only place that we can reproduce the no report error: I was trying to reproduce the `Fuzz target binary not found.` error in this PR, but it did not work either.

Could you please cherry-pick commits from #2038, or rebase your PR on it?
Hopefully those commits can help us understand the cause.

**Comment by addisoncrump** [comment]
Hey, what remains for this PR? We settled that the flakiness was not associated to this PR, unless I'm mistaken.

**Comment by DonggeLiu** [comment]
> Hey, what remains for this PR? We settled that the flakiness was not associated to this PR, unless I'm mistaken.

You are right, I will merge this.

**Review by DonggeLiu — APPROVED** [review]

**Comment by addisoncrump** [comment]
Any chance we could run another baselines experiment with this? Would be good to have this data in the pocket.

**Comment by DonggeLiu** [comment]
> Any chance we could run another baselines experiment with this? Would be good to have this data in the pocket.

Yep sure!

**Pull request merged**
