### PR TITLE
new afl++ experiment, make some benchmarks better to compile

### PR DESCRIPTION
**Pull request by vanhauser-thc**
Update:
  - cleanup: removes several outdated variants I do not have time for
  - new experiment for frida and the enhanced llvm select coverage loss fix
  - fix several benchmarks to make them better to compile

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
more coming

**Comment by vanhauser-thc** [comment]
done. everything that does not for for aflplusplus_gcc is disabled, everything else works (some after fixes).

**Comment by vanhauser-thc** [comment]
Update:
  - cleanup: removes several outdated variants I do not have time for
  - new experiment for frida and the enhanced llvm select coverage loss fix
  - fix several benchmarks to make them better to compile

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by vanhauser-thc** [comment]
@jonathanmetzman the changed fuzzers have passes for oss and standard, so it can be merged :) thank you!

**Comment by jonathanmetzman** [comment]
or wait for CI?

**Comment by vanhauser-thc** [comment]
can be merged, it is still the same code, just backwards merged the changes from our current dev branch into the test branches. they were based on an older and different state and that could influence the results from the previous tests.

**Pull request merged**
