### PR TITLE
[SBST23] R-Fuzz

### PR DESCRIPTION
**Pull request by chenju2k6**

### CODE REVIEW

**Comment by Alan32Liu** [comment]
Hi @chenju2k6, 
just a gentle reminder that PR is due for a pre-run on AoE 17 Feb.
Please consider at least passing the presubmit and a few benchmark-building CIs so that the pre-run can give you some preliminary results.

Could I ask you to share the following information with us, please? The conference requires it from us by Wednesday (Feb 22):
1. Title of your paper, 
2. Affiliations,
3. Emails, 
4. Name and surnames of all authors,
5. The order of authors.

You might have answered some of them in the registration form, but we do want to confirm them before submitting them to the conference.
Feel free to reply to us here or via email (sbft23fuzzcomp@googlegroups.com).

**Comment by chenju2k6** [comment]
Do you mean the tool report submitted for the competition?

Title: R-Fuzz at SBFT'2023
Authors: Ju Chen (Deepbits Technology), Chengyu Song (UC Riverside), Heng
Yin (UC Riverside and Deepbits Technology)

Best Regards,
Ju Chen
----------------------------------
Phone: 585-434-8060

**Comment by Alan32Liu** [comment]
Hi @chenju2k6, 
may I invite you to take a look at the CI failures and see if it is possible to fix some of them at the last minute? Thanks : )

Also,
could you please avoid adding/editing outside your fuzzer's directory? For example, please try not to edit `afl++` as others users of FuzzBench may rely on it. Instead, you could duplicate its code in your dir : )

**Comment by chenju2k6** [comment]
Hi Dongge,

How many hours do I have?

Best Regards,
Ju Chen
----------------------------------
Phone: 585-434-8060

**Comment by Alan32Liu** [comment]
Hi @chenju2k6,
May I ask you to remove `sbft_holder`, given it is redundant and not inside your fuzzer dir? 
Thanks!

**Pull request merged**
