### PR TITLE
Request experiment for WingFuzz

### PR DESCRIPTION
**Pull request by hghwng**
This PR adds WingFuzz, an experimental fuzzer featuring memory coverage guidance.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by hghwng** [comment]
@jonathanmetzman Seems a few benchmarks are not respecting `LDFLAGS`. Also, the base images for ffmpeg and go-ethereum are too old (Ubuntu 16.04, clang-9.0). Similarly, the other benchmarks are using an old version of clang (12). 

Should we enhance the developer experience by upgrading the base image? For example, simply switching to `oss-fuzz-base/base-builder:latest`?

**Comment by hghwng** [comment]
@jonathanmetzman @oliverchang Could you approve the pre-submit workflow? I'm stuck with the following message: " 2 workflows awaiting approval. First-time contributors need a maintainer to approve running workflows."

**Comment by oliverchang** [comment]
> @jonathanmetzman @oliverchang Could you approve the pre-submit workflow? I'm stuck with the following message: " 2 workflows awaiting approval. First-time contributors need a maintainer to approve running workflows."

done!

**Comment by hghwng** [comment]
Please let me know if there are any questions about this PR. It looks like WingFuzz-related checks all passed (despite the failing `-um` variants).

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
