### PR TITLE
libafl grammar implemenation comparison experiment

### PR DESCRIPTION
**Pull request by vanhauser-thc**

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
Actually CI looks really broken, what do you want me to do?

**Comment by vanhauser-thc** [comment]
I am working on it ... I am not the greatest rust coder and need to fix my stuff I did for libafl :)

**Comment by vanhauser-thc** [comment]
@jonathanmetzman @Alan32Liu 

Note that this PR also fixes the mruby and libgit2 benchmark!

Also note that arrow_parquet-arrow-fuzz is broken:
```
#18 93.06 CMake Error at /work/brotli_ep-prefix/src/brotli_ep-stamp/brotli_ep-install-RELEASE.cmake:37 (message):
#18 93.06   Command failed: 1
#18 93.06 
#18 93.06    '/usr/local/bin/cmake' '--build' '.' '--target' 'install'
#18 93.06 
#18 93.06   See also
#18 93.06 
#18 93.06     /work/brotli_ep-prefix/src/brotli_ep-stamp/brotli_ep-install-*.log
#18 93.06 
#18 93.06 
#18 93.06 -- stdout output is:
#18 93.06 
#18 93.06 -- stderr output is:
#18 93.06 ninja: error: unknown target 'install'
```

**Pull request merged**
