### PR TITLE
test new afl++ variant

### PR DESCRIPTION
**Pull request by vanhauser-thc**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-08-31-aflpp --fuzzers aflplusplus aflplusplus_pendfav

**Comment by Alan32Liu** [comment]
I think you might have forgotten to edit [service/gcbrun_experiment.py](https://github.com/google/fuzzbench/blob/master/service/gcbrun_experiment.py), which allows launching experiments in PRs : ) 
 Recall [your previous example to add a dummy comment](https://github.com/google/fuzzbench/pull/1818/files#diff-e870d8214beac56eaaeda2edc69de842f8382c428329dd8cf826a9cfa5edf7e9).

**Comment by vanhauser-thc** [comment]
right ... damn I do this too rarely :)

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-08-31-aflpp --fuzzers aflplusplus aflplusplus_pendfav

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-02-aflpp --fuzzers aflplusplus_frida aflplusplus_qemu aflplusplus_frida_perf aflplusplus_qemu_tcgcov

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-03-aflpp --fuzzers aflplusplus aflplusplus_pendfav

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-04-aflpp --fuzzers aflplusplus aflplusplus_pendfav

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-04-aflpp2 --fuzzers aflplusplus aflplusplus_pendfav

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-06-aflpp --fuzzers aflplusplus aflplusplus_pendfav

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-06-aflpp2 --fuzzers aflplusplus aflplusplus_pendfav

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-12-aflpp --fuzzers aflplusplus aflplusplus_o0 aflplusplus_o1 aflplusplus_o2

**Comment by jonathanmetzman** [comment]
> /gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-12-aflpp --fuzzers aflplusplus aflplusplus_o0 aflplusplus_o1 aflplusplus_o2

Can you run these experiments?

**Comment by Alan32Liu** [comment]
> /gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name test-trigger-by-quote --fuzzers aflplusplus

Testing why quoting the `gcb` command still triggers experiments.
Ideally, we only want to trigger exps if `gcb` is in plain text to avoid repeatedly triggering them when quoting them.

**Comment by Alan32Liu** [comment]
Just a sanity check: A normal comment will not trigger experiments.

**Comment by Alan32Liu** [comment]
How about this /gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name test-trigger-in-text ?

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-25-ff --fuzzers aflplusplus_ff_comp aflplusplus_fishfuzz

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-28-ff --fuzzers aflplusplus_ff_comp aflplusplus_fishfuzz aflplusplus_ff_comp2

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-06 --fuzzers aflplusplus aflplusplus_early

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-06 --fuzzers aflplusplus_fishfuzz aflplusplus_ff_comp3

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-07-aflpp  --fuzzers aflplusplus aflplusplus_early

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-08-aflpp --fuzzers aflplusplus_llvm17 aflplusplus_early

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-08-aflpp2 --fuzzers aflplusplus_llvm17 aflplusplus_early

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-08-aflpp-ff --fuzzers aflplusplus_ff_comp3  aflplusplus_fishfuzz

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-09-aflpp-nocmplog --fuzzers aflplusplus_llvm17 aflplusplus_early

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-10-aflpp-nocmplog --fuzzers aflplusplus_llvm17 aflplusplus_early

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-11-23-aflpp --fuzzers aflplusplus aflplusplus_nou8

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-11-23-aflpp2 --fuzzers aflplusplus aflplusplus_nou8

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-11-29-fish --fuzzers aflplusplus_fishfuzz aflplusplus_ff_comp3 --benchmarks bloaty_fuzz_target_52948c harfbuzz_hb-shape-fuzzer_17863b libxml2_xml_e85b9b mbedtls_fuzz_dtlsclient_7c6b0e php_php-fuzz-parser_0dbedb

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-11-29-aflpp --fuzzers aflplusplus aflplusplus_nou8

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-12-01-aflpp --fuzzers aflplusplus aflplusplus_nou8

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-12-05-aflpp --fuzzers aflplusplus aflplusplus_nou8

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-12-08-aflpp --fuzzers aflplusplus aflplusplus_nou8

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-12-10-aflpp --fuzzers aflplusplus aflplusplus_explore aflplusplus_noclassify

**Comment by vanhauser-thc** [comment]
@Alan32Liu  no experiments are currently going through it seems:

```
gs://fuzzbench-data/2023-12-07-standard/
gs://fuzzbench-data/2023-12-08-aflpp/
gs://fuzzbench-data/2023-12-08-standard-bug/
gs://fuzzbench-data/2023-12-08-standard-cov/
gs://fuzzbench-data/2023-12-10-aflpp/
```
but none of them are visible at https://www.fuzzbench.com/reports/experimental/index.html so there seems to be an issue with running the experiments.

**Comment by Alan32Liu** [comment]
> @Alan32Liu no experiments are currently going through it seems:

Thanks for the report, @vanhauser-thc !

Could you please try again with the latest commit from Jonathan (dc03c08100933a3335cf95c6575f651c8dbd50c8)? We believe that should have fixed the problem.
Sorry about the inconvenience : )

**Comment by vanhauser-thc** [comment]
can you please ping me when you know it is working again? also with the information if I can use this older state or if I need to restart from current state. thank you :)

**Comment by kdsjZh** [comment]
Looks like it works, the latest campaign's report is available at https://fuzzbench.com/reports/experimental/2023-12-10-aflpp/index.html. @vanhauser-thc

**Comment by Alan32Liu** [comment]
> Looks like it works, the latest campaign's report is available at https://fuzzbench.com/reports/experimental/2023-12-10-aflpp/index.html. @vanhauser-thc

Yep!

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-12-12-aflpp --fuzzers aflplusplus aflplusplus_cxx

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-12-13-aflpp --fuzzers aflplusplus aflplusplus_cxx

**Comment by vanhauser-thc** [comment]
@Alan32Liu  there still seem to be issues, the last run stopped, the index.html shows no update for the last 12 hours ... I restarted it but I think this is something that should be inspected.

**Comment by Alan32Liu** [comment]
> @Alan32Liu there still seem to be issues, the last run stopped, the index.html shows no update for the last 12 hours ... I restarted it but I think this is something that should be inspected.

Not sure what `2023-12-12-aflpp` looks like earlier, but it seems we have 10+ fuzzer instances successfully completed 23h-exp for all benchmarks [its report ](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-12-12-aflpp/index.html)?

We don't have all fuzzer instances, but I presume they were re-running now (hence the subtitle says `experiment incomplete/still running...`). We cannot see their progress in the plots until they finish, because the existing results in the plot are already at 23h.

I also double-checked the logs and can confirm some instances of `2023-12-12-aflpp` is running at this moment.

**Comment by vanhauser-thc** [comment]
yes it hung for about 18 hours or so, then progressed again. weird.

**Comment by vanhauser-thc** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-12-15-aflpp --fuzzers aflplusplus_408 aflplusplus_409

**Pull request closed without merging**
