### PR TITLE
Debug PR #2028

### PR DESCRIPTION
**Pull request by DonggeLiu**
Debug two new errors observed in #2028 with the logs from #2038.

Error 1:  [cloud build timeout](https://github.com/google/fuzzbench/pull/2038#issuecomment-2308365774) 

Error 2: [Fuzz target binary not found.](https://github.com/google/fuzzbench/pull/2038#issuecomment-2308574089)

### CODE REVIEW

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-25-2039-libafl --fuzzers libafl

**Comment by DonggeLiu** [comment]
Experiment `2024-08-25-2039-libafl` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-25-2039-libafl/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-25-2039-libafl/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-25-2039-libafl/index.html).

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-25-2039-libafl-1 --fuzzers libafl

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-25-2039-bases-1 --fuzzers afl aflplusplus libfuzzer

**Comment by DonggeLiu** [comment]
Experiment `2024-08-25-2039-libafl-1` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-25-2039-libafl-1/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-25-2039-libafl-1/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-25-2039-libafl-1/index.html).

Experiment `2024-08-25-2039-bases-1` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-25-2039-bases-1/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-25-2039-bases-1/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-25-2039-bases-1/index.html).

**Comment by addisoncrump** [comment]
This is starting to look like a Heisenbug...

**Comment by tokatoka** [comment]
For the 1st one some of them stopped at 15 minutes 
For the 2nd one some of them stopped at 6h so it was not really working

**Comment by tokatoka** [comment]
Now it is showing the final report.
But for the 2nd one in the final report,
**None** of {afl aflplusplus libfuzzer} is listed in the report, despite they are the fuzzers being tested

**Comment by tokatoka** [comment]
and as i said,
for the 2nd report, https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-25-2039-bases-1/data.csv.gz
the data.csv.gz does contain the data for afl, aflplusplus, and libfuzzer. but all their experiment are terminated after 6 hours (= 21600 seconds)

for the 1st one, too.
at least for this one, we have complete result for most targets on libafl except for the 5 missing NaN.

**Comment by tokatoka** [comment]
although I said "terminated after 6 hours".
but this is not really correct
because in the experiment-folder 
https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-25-2039-bases-1/experiment-folders/curl_curl_fuzzer_http-afl/trial-3106096/corpus/

here it does have corpus for the last 23 hours. So in the end the fuzzer did run successfully!. but the problem is just about the measurement not working

**Comment by DonggeLiu** [comment]
Thanks for tracking the experiment progress, @tokatoka 
It's perfectly normal for the experiment report to pause for a few hours:
1. The experiment trial VM might be preempted. Hence, that trial has to be re-run.
2. The measurer might take a while to produce results.

As a result, we can expect a 1-day experiment report to take up to 3 days : )

**Pull request closed without merging**
