### PR TITLE
Add freeze-dependencies to Makefile.

### PR DESCRIPTION
**Pull request by lszekeres**
For updating requirements.txt after installing new dependencies.

### CODE REVIEW

**Comment by lszekeres** [comment]
> nit: Will this be useful for other users ?

I believe so. (I personally never remember the pip command to do this)

**Comment by jonathanmetzman** [comment]
I don't really think this is useful. Typically when I add a dependency (like rq for example) I'll only add that dependency to requirements.txt (i.e. `pip freeze | grep rq`) This would add all the dependencies of that dependency to requirements.txt

**Comment by inferno-chromium** [comment]
> I don't really think this is useful. Typically when I add a dependency (like rq for example) I'll only add that dependency to requirements.txt (i.e. `pip freeze | grep rq`) This would add all the dependencies of that dependency to requirements.txt

ah right, forgot about that. @lszekeres - thoughts, feel free to revert.

**Comment by lszekeres** [comment]
makes sense! let me revert it

**Pull request merged**
