### PR TITLE
Allow running experiments from PRs using GCB

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Fixes: #1599

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun experiment/run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl

**Comment by jonathanmetzman** [comment]
I propose we merge this before the competition but keep the old model around for a while. This will be useful to have as it will allow us to test changes like https://github.com/google/fuzzbench/pull/1632 without deploying them.

**Comment by jonathanmetzman** [comment]
> I propose we merge this before the competition but keep the old model around for a while. This will be useful to have as it will allow us to test changes like #1632 without deploying them.

Sorry, I mean https://github.com/google/fuzzbench/pull/1626

**Comment by jonathanmetzman** [comment]
/gcbrun experiment/run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl

**Comment by jonathanmetzman** [comment]
/gcbrun experiment/run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl

**Review by oliverchang — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
/gcbrun experiment/run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl

**Comment by jonathanmetzman** [comment]
/gcbrun experiment/run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl

**Review by Alan32Liu — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
Having permission issues.

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-1 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
TODO: bucket logging so this can write to GH

**Comment by jonathanmetzman** [comment]
This successfully started an instance even though it is red

**Comment by jonathanmetzman** [comment]
I need to figure out what file to modify to make gcbrun trigger. kinda shoehorning this since it's a ci tool.

**Comment by jonathanmetzman** [comment]
Gonna merge and iterate

**Pull request merged**
