### PR TITLE
New AFL splicing experiment

### PR DESCRIPTION
**Pull request by andreafioraldi**
Experiment to see the improvements after #1412

### CODE REVIEW

**Comment by andreafioraldi** [comment]
@jonathanmetzman merged and solved the conflict

**Comment by andreafioraldi** [comment]
the bug benchmarks are failing on ffmpeg with

```
------
 > [12/25] RUN (cd /src/libXext; git checkout d965a1a8ce9331d2aaf1c697a29455ad55171b36):
#18 1.528 fatal: reference is not a tree: d965a1a8ce9331d2aaf1c697a29455ad55171b36
------
```
I don't think has nothing to do with my patch to AFL

**Comment by jonathanmetzman** [comment]
> the bug benchmarks are failing on ffmpeg with
> 
> ```
> ------
>  > [12/25] RUN (cd /src/libXext; git checkout d965a1a8ce9331d2aaf1c697a29455ad55171b36):
> #18 1.528 fatal: reference is not a tree: d965a1a8ce9331d2aaf1c697a29455ad55171b36
> ------
> ```
> 
> I don't think has anything to do with my patch to AFL

It's not your fault. I'm gonna kill this benchmark

**Review by jonathanmetzman — COMMENTED** [review]
lgtm

**Comment by andreafioraldi** [comment]
@jonathanmetzman the experiment seems stuck at ~5h since yesterday that I checked https://www.fuzzbench.com/reports/experimental/2022-07-21-afl-new-splicing/index.html

Can you check?

**Comment by jonathanmetzman** [comment]
Damn. I'm at a conference now. Lemme try when i get a chance

**Comment by andreafioraldi** [comment]
> Damn. I'm at a conference now. Lemme try when i get a chance

Maybe it was the parallel centipede experiment that tooks most of the resources. The data.csv is also stuck at 5h so it is not an issue of the report generator, the experiment simply stopped.

When you are back at work, can you rerun it ASAP please as the deadline of the journal special issue is incoming and this is the last experiment left? Ty.

**Comment by jonathanmetzman** [comment]
When is the deadline?

**Comment by jonathanmetzman** [comment]
> > Damn. I'm at a conference now. Lemme try when i get a chance
> 
> Maybe it was the parallel centipede experiment that tooks most of the resources. The data.csv is also stuck at 5h so it is not an issue of the report generator, the experiment simply stopped.
> 
> When you are back at work, can you rerun it ASAP please as the deadline of the journal special issue is incoming and this is the last experiment left? Ty.

Did you look at the experiment data in gs://fuzzbench-data ?

**Comment by andreafioraldi** [comment]
> When is the deadline?

At the end of the month.

> Did you look at the experiment data in gs://fuzzbench-data ?

No good idea, I'll try tomorrow.

**Comment by jonathanmetzman** [comment]
> > When is the deadline?
> 
> At the end of the month.
> 
> > Did you look at the experiment data in gs://fuzzbench-data ?
> 
> No good idea, I'll try tomorrow.

How important is this experiment. The bug based benchmarks are known to be finnicky and I assume the issue here is that these trials often fail. we could do a bunch of trials and try to get 20 in the end.

**Comment by andreafioraldi** [comment]
> The bug based benchmarks are known to be finnicky and I assume the issue here is that these trials often fail. we could do a bunch of trials and try to get 20 in the end.

I fuzzed some benchmarks locally to test the variant and it goes fine. Even assuming a crash in the fuzzer fuzzbench still reports the data for AFL that it is unlikely to crash during the trials.

> we could do a bunch of trials and try to get 20 in the end.

Yes ty, even if not 20, a finished experiment is enough for now as I can investigate the results and write about it. The results will unlikely change drastically from 10 to 20 trials and we can do the others later.

**Pull request merged**
