### PR TITLE
afl++: test a regression fix

### PR DESCRIPTION
**Pull request by vanhauser-thc**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
is the CI working? it looks weird.

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
> is the CI working? it looks weird.

something messed with github, i pressed the button to redo all jobs again, lets see if it works.

**Comment by inferno-chromium** [comment]
> is the CI working? it looks weird.

found the issue, we have too many fuzzers in CI, can we do some house cleaning on afl++ fuzz variants

CI failed on 
```
Build fuzzers : .github#L1
Strategy produced more than 256```

**Comment by vanhauser-thc** [comment]
the frida break is new, will be fixed in a future push, not relevant for this run.

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
> @inferno-chromium removed unnecessary ones and commented out those I still need. plus there are a lot of other temporary fuzzers that are not mine :)
> 
> there is a lot I still need to work on, but I am swamped with customer work :( (well should be :) but its way way too much atm)

a good problem to have, but not always :)

**Pull request merged**
