### PR TITLE
new afl++ token experiment

### PR DESCRIPTION
**Pull request by vanhauser-thc**
the last experiment did not start afl++, only afl++_token ... weird!

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@jonathanmetzman again afl++ is not being run for most targets, can you have a look what is going wrong please?

https://www.fuzzbench.com/reports/experimental/2023-01-05-aflpp/index.html

**Comment by jonathanmetzman** [comment]
I'll set something on my calendar to do this for Monday or Sunday

**Comment by Alan32Liu** [comment]
> @Alan32Liu could you please look into this?

Sure!

**Comment by Alan32Liu** [comment]
This is truly strange, `afl++` did not start because it failed to build.
[Its `git checkout` ](https://github.com/google/fuzzbench/blob/master/fuzzers/aflplusplus/builder.Dockerfile#L41)incurred [a fatal error 'reference is not a tree'](https://storage.googleapis.com/fuzzbench-data/2023-01-05-aflpp/build-logs/benchmark-bloaty_fuzz_target-fuzzer-aflplusplus.txt).

This is particularly strange because the same [`git checkout`](https://github.com/google/fuzzbench/blob/master/fuzzers/aflplusplus_tokens/builder.Dockerfile#L41) in `aflplusplus_tokens` [builds fine](https://storage.googleapis.com/fuzzbench-data/2023-01-05-aflpp/build-logs/benchmark-bloaty_fuzz_target-fuzzer-aflplusplus_tokens.txt).

I do not have an explanation for this, nor do I think this error will persist.
I could not reproduce this error locally, either.

I will start a very short experiment to (15-minute) test if the error is flaky, and re-run the full experiment if it is.

**Comment by Alan32Liu** [comment]
Launching test exp and recording results in #1605.

**Comment by Alan32Liu** [comment]
I started another 15-minute test experiment locally to avoid the waiting time and speed it up.
This build log confirms that `aflpp` can `checkout` and build successfully:
https://storage.googleapis.com/fuzzbench-data/2023-01-10-aflpp-test/build-logs/benchmark-arrow_parquet-arrow-fuzz-fuzzer-aflplusplus.txt

I will re-launch the full experiment later if the final report also looks alright.

**Comment by Alan32Liu** [comment]
[Result report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-01-10-aflpp-test/index.html):
`aflpp` can successfully build on all benchmarks in the experiment, but `aflpp_tokens` failed on several.

**Comment by vanhauser-thc** [comment]
hmm it builds for me:
```
/prg/fb (master) # make test-run-aflplusplus_tokens-aspell_aspell_fuzzer 
...
[+] All set and ready to roll!
[*] Entering queue cycle 1.
[*] Fuzzing test case #23 (60 total, 0 crashes saved, perf_score=100, exec_us=40969, hits=0, map=4087, ascii=1)...
INFO:root:Doing final sync.
```

**Comment by Alan32Liu** [comment]
Yeah, I cannot reproduce the error locally either.
Let me take another look into this. @vanhauser-thc.

**Comment by Alan32Liu** [comment]
Both fuzzers seem to build fine in experiment `2023-01-10-aflpp`.
I will update the result here once it is ready.

**Pull request merged**
