### PR TITLE
Archive coverage data alongside corpus archives

### PR DESCRIPTION
**Pull request by addisoncrump**
Currently, only corpora are saved in the archive and the summaries of coverage are provided at the end of the experiment. This change simply incorporates the saving of the coverage data snapshots next to the trial corpus snapshots.

### CODE REVIEW

**Comment by addisoncrump** [comment]
Forgot to format...

**Comment by addisoncrump** [comment]
It doesn't seem that the saving works as expected. I'm going to keep trying with this, but it's quite difficult to debug.

**Comment by addisoncrump** [comment]
Okay, this should work now. I got confused as to the direction of the copy originally.

**Comment by DonggeLiu** [comment]
Thanks @addisoncrump!
The code looks great to me. But before merging this, let's run an experiment on this PR to triple-check that this also works in the cloud instances : )
Could you please make a trivial modification to [service/gcbrun_experiment.py](https://github.com/google/fuzzbench/blob/master/service/gcbrun_experiment.py)?
This will allow me to launch experiments in this PR for final validation. Here is [an example to add a dummy comment](https://github.com/google/fuzzbench/pull/1818/files#diff-e870d8214beac56eaaeda2edc69de842f8382c428329dd8cf826a9cfa5edf7e9).
We can revert this after the experiment.
Thanks!

**Comment by addisoncrump** [comment]
> let's run an experiment on this PR to triple-check that this also works in the cloud instances

Sure, and also to collect the corresponding coverage data for the "standard" fuzzers. I'll make that change shortly.

**Comment by addisoncrump** [comment]
Also, a local experiment shows that we also get warning info in the JSON (!):

```
warning: 6 functions have mismatched data
{"data":[{"files":[{"branches":[[102,22,102,36,0,0,0,0,4],[103,9,103,41,0,0,0,0,4],...]}]}]}
```

Should we remove this?

**Comment by DonggeLiu** [comment]
> Should we remove this?

Do you happen to know the cause of this?

**Comment by addisoncrump** [comment]
To be honest, I've looked around a bit now and do not see the root cause.

It seems to be using [`new_process.execute`](https://github.com/google/fuzzbench/blob/master/common/new_process.py#L71), but this redirects stdout. I presume, then, that llvm-cov is actually producing warnings in stdout(!). I'll see if I can find the appropriate command line switch to remove this.

**Comment by addisoncrump** [comment]
It seems to be a known issue btw; [`get_coverage_infomation`](https://github.com/google/fuzzbench/blob/master/experiment/measurer/coverage_utils.py#L234) (typo: information) already handles this.

**Comment by addisoncrump** [comment]
That seems to have done it. The `get_coverage_infomation` function can remain as-is without loss of functionality.

**Comment by addisoncrump** [comment]
Okay, so I spent quite a while debugging a weird change that was occurring when presubmit was applied; namely, `make presubmit` was modifying the file `analysis/test_data/pairwise_unique_coverage_heatmap-failed-diff.png`. This was a result of [the seaborn version being incompatible with the version of matplotlib](https://stackoverflow.com/questions/77165100/only-the-first-row-of-annotations-displayed-on-seaborn-heatmap). Nonetheless, this still had metadata changes which caused the diff to be modified in disk. Since this is the result of a test, I added it to the gitignore.

This also implies to me that the test should be failing, but isn't. I think this is a minor difference in how seaborn now emits heatmaps (seems to be some offset change).

**Comment by addisoncrump** [comment]
Also, experimenting with compression, because the coverage dumps are quite large and easily compressible.

**Comment by addisoncrump** [comment]
> llvm-cov export: Unknown command line argument '-no-warn'.  Try: 'llvm-cov export --help'

Well, the version of llvm-cov used is too old. I'll revert this now.

**Comment by addisoncrump** [comment]
Compression reduces 15MB => 1MB, so seems worth it. This is now in a stable state and ready for a test run!

**Comment by DonggeLiu** [comment]
Nice! Let's start with a simple one.

> collect the corresponding coverage data for the "standard" fuzzers.

Then we collect these.

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-09-dg-2020 --fuzzers libfuzzer --benchmarks libxml2_xml

**Comment by DonggeLiu** [comment]
Experiment `2024-08-09-dg-2020` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-09-dg-2020/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-09-dg-2020/index.html).

**Comment by DonggeLiu** [comment]
> Should I also include new code for analysis to use this? I can include a test that points at the data available in that bucket.

Yep sure, go for it.
Thanks!

**Comment by DonggeLiu** [comment]
> collect the corresponding coverage data for the "standard" fuzzers.

To minimize our waiting time, I will start this experiment, given `2024-08-09-dg-2020` looks good so far.

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-10-base --fuzzers aflplusplus centipede honggfuzz libafl libfuzzer

**Comment by addisoncrump** [comment]
> due to the measurement bottleneck

Out of curiosity, what is the measurement bottleneck? I did notice that, despite having lots of corpus archives available, the snapshots don't seem to have been measured yet.

**Comment by DonggeLiu** [comment]
Experiment `2024-08-10-base` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-10-base/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-10-base/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-10-base/index.html).

**Comment by DonggeLiu** [comment]
> Out of curiosity, what is the measurement bottleneck? I did notice that, despite having lots of corpus archives available, the snapshots don't seem to have been measured yet.

Currently we measure coverage of all results in one VM, which becomes insanely slow when there are too many fuzzers (e.g., > 8) in one experiment.
We are working on fixing this.

**Comment by addisoncrump** [comment]
Ah, okay, I understand. With the other experiment still running, it is effectively entirely overloaded, then.

**Comment by DonggeLiu** [comment]
Wait, something is going wrong with the `2024-08-10-base`.
The data directory was generated as expected, but the report was not.

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-10-test --fuzzers aflplusplus centipede honggfuzz libfuzzer

**Comment by addisoncrump** [comment]
>  The data directory was generated as expected, but the report was not.

If none of the measurements have happened yet, it won't have created a report, no?

**Comment by tokatoka** [comment]
i guess we need to update libafl
@addisoncrump 
can you change the commit we are using for libafl?
and also use `fuzzers/fuzzbench/fuzzbench` instead of `fuzzers/fuzzbench`

**Comment by DonggeLiu** [comment]
> @DonggeLiu Any complaints if I make the libafl change in this PR as well?

Ah we would really appreciate it if you could do it in a different PR, given it is a stand-alone change.
Hope that won't cause too much trouble : )

Thanks!

**Comment by DonggeLiu** [comment]
Thanks for the info, @tokatoka.
> can you change the commit we are using for libafl?

What is the preferred commit to use?

**Comment by tokatoka** [comment]
i'd say we can just use the latest

**Comment by addisoncrump** [comment]
> Wait, something is going wrong with the 2024-08-10-base.
@DonggeLiu, was the issue ever discovered?

**Comment by DonggeLiu** [comment]
Also seeing a lot of this, but I presume that's unrelated to your PR?
```python
Traceback (most recent call last):
  File "/work/src/experiment/measurer/coverage_utils.py", line 74, in generate_coverage_report
    coverage_reporter.generate_coverage_summary_json()
  File "/work/src/experiment/measurer/coverage_utils.py", line 141, in generate_coverage_summary_json
    result = generate_json_summary(coverage_binary,
  File "/work/src/experiment/measurer/coverage_utils.py", line 269, in generate_json_summary
    with open(output_file, 'w', encoding='utf-8') as dst_file:
FileNotFoundError: [Errno 2] No such file or directory: '/work/measurement-folders/lcms_cms_transform_fuzzer-centipede/merged.json'

```

**Comment by addisoncrump** [comment]
I don't think so -- the modifications which were applied were done by the formatter. I can just revert that whole file if needed.

**Comment by DonggeLiu** [comment]
> I can just revert that whole file if needed.

No need, I've addressed this in https://github.com/google/fuzzbench/pull/2023.
Later we can merge that into here.

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-12-2020 --fuzzers aflplusplus centipede honggfuzz libfuzzer

**Comment by DonggeLiu** [comment]
Experiment `2024-08-12-2020` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-12-2020/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/2024-08-12-2020/index.html).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-12-2020/index.html).

**Comment by addisoncrump** [comment]
Yeah, looks like it's not working. This run should probably be cancelled, if nothing but to save some CPU time.

**Comment by DonggeLiu** [comment]
Yep, I suspect this is due to a benchmark compatibility issue.
Let me verify this.

**Pull request closed without merging**
