### PR TITLE
update afl++ commit id, remove variants

### PR DESCRIPTION
**Pull request by vanhauser-thc**
No experiment, just cleanup of variants and updating the afl++ commit id

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Oy, is CI just in a terrible state or is this PR broken?

**Comment by vanhauser-thc** [comment]
Neither:
```
2021-11-10T13:33:12.8311474Z #6 0.735 curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
2021-11-10T13:33:12.8312363Z #6 0.737 More details here: http://curl.haxx.se/docs/sslcerts.html
2021-11-10T13:33:12.8312837Z #6 0.737 
2021-11-10T13:33:12.8314317Z #6 0.737 curl performs SSL certificate verification by default, using a "bundle"
2021-11-10T13:33:12.8314998Z #6 0.737  of Certificate Authority (CA) public keys (CA certs). If the default
2021-11-10T13:33:12.8315824Z #6 0.737  bundle file isn't adequate, you can specify an alternate file
2021-11-10T13:33:12.8316448Z #6 0.737  using the --cacert option.
2021-11-10T13:33:12.8316983Z #6 0.737 If this HTTPS server uses a certificate signed by a CA represented in
2021-11-10T13:33:12.8317674Z #6 0.737  the bundle, the certificate verification probably failed due to a
2021-11-10T13:33:12.8318351Z #6 0.737  problem with the certificate (it might be expired, or the name might
2021-11-10T13:33:12.8318905Z #6 0.737  not match the domain name in the URL).
2021-11-10T13:33:12.8319596Z #6 0.737 If you'd like to turn off curl's verification of the certificate, use
2021-11-10T13:33:12.8321621Z #6 0.737  the -k (or --insecure) option.
2021-11-10T13:33:12.8323250Z #6 ERROR: executor failed running [/bin/sh -c mkdir $SRC/sqlite3 &&     cd $SRC/sqlite3 &&     curl 'https://sqlite.org/src/tarball/sqlite.tar.gz?r=c78cbf2e86850cc6' -o sqlite3.tar.gz &&         tar xzf sqlite3.tar.gz --strip-components 1]: exit code: 60
```
it is again certificate issues. but here it seems that the cert file is simply not installed? weird.

**Comment by vanhauser-thc** [comment]
can this be merged?

**Comment by jdhiser** [comment]
@vanhauser-thc, this PR removed `aflplusplus_qemu_tracepc` (`aflplusplus_qemu` w/o cmplog/redqueen support).  I'd like to still run this configuration for comparisons to Zafl.  Can you explain why this configuration was removed?

**Comment by vanhauser-thc** [comment]
@jdhiser uh, I cleaned up my variants, and just thought that's one of mine :) sorry!

**Comment by jdhiser** [comment]
> @jdhiser uh, I cleaned up my variants, and just thought that's one of mine :) sorry!

No worries, thanks for the reply!

**Pull request merged**
