### PR TITLE
Compare AFL Dumb mode with a few other fuzzers

### PR DESCRIPTION
**Pull request by dliyanage**
Hi,
We are evaluating how well the classical estimators of fuzzer effectiveness perform in an actual blackbox fuzzer setting. Therefore, we came up with a variant of AFL named `pythia_effect_bb` that keeps track of all the variables we need. Let's see how long this fuzzer takes to saturate the path/edge coverage.

Thanks.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Please sign the CLA and ping me when CI completes and I will merge.

**Comment by dliyanage** [comment]
> Please sign the CLA and ping me when CI completes and I will merge.

Hey Jonathan, I have already signed the CLA. But, it's not showing here for some reason.

Screen Shot 2021-09-18 at 2 03 20 am

**Comment by dliyanage** [comment]
@googlebot I signed it!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by dliyanage** [comment]
Thanks @jonathanmetzman.

**Comment by dliyanage** [comment]
Hi @jonathanmetzman, Can you please let me know the status of our submitted experiment last weekend? The analysis is not appearing in [https://www.fuzzbench.com/reports/experimental](https://www.fuzzbench.com/reports/experimental) and I am wondering whether there was any issue. Thanks in advance.

Danushka

**Comment by jonathanmetzman** [comment]
I think the experiment name was invalid. But I've fixed that here: https://github.com/google/fuzzbench/pull/1246

**Comment by dliyanage** [comment]
Thanks a lot @jonathanmetzman. Cheers.

**Pull request merged**
