### PR TITLE
request for an experiment on fafuzz

### PR DESCRIPTION
**Pull request by Mart11n**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Sorry I've been slow approving this. I'll merge after CI completes

**Comment by jonathanmetzman** [comment]
Is https://github.com/google/fuzzbench/pull/1283 needed after this lands?

**Comment by Mart11n** [comment]
This PR is enough for fafuzz experiment. Thx.

**Comment by Mart11n** [comment]
Sorry for missing to add fafuzz in .github/workflows/fuzzers.yml.

**Comment by Mart11n** [comment]
> Sorry for missing to add fafuzz in .github/workflows/fuzzers.yml.

Can you rerun the CL? Thx.(I just passed the "make presubmit" before I commit ,but it seems that this cmd can not detected some errors like \t, which results in the failure for last CL.)

**Pull request merged**
