### PR TITLE
revert oss_fuzz_corpus typo fix

### PR DESCRIPTION
**Pull request by ndrewh**
This reverts #1993

the comments in experiment-requests.yml are untouchable without breaking tests

### CODE REVIEW

**Comment by ndrewh** [comment]
🤬 presubmit failed

**Comment by ndrewh** [comment]
Alright, I changed it to just touch the **_comments_** in experiment-requests.yml, and it **_still_** breaks tests. So i'm giving up on fixing the typo. Just reverting

**Comment by DonggeLiu** [comment]
Thanks for creating this, @ndrewh.
May I ask if `experiment-requests.yml` is the only source of error when unifying the `-`s and `_`s?

I reckon there is no need to rewrite `experiment-requests.yml`: it will not be used/parsed/revived anytime soon.

**Comment by ndrewh** [comment]
Yes it is the only issue and yes it has CI failures if you try to fix

**Comment by DonggeLiu** [comment]
I see, that's really weird.

Sorry that it did not work out this time, but thanks again for your time.
Let me merge this for now.

**Review by DonggeLiu — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
Dongge I think we can just delete the test and reland.

**Pull request merged**
