### PR TITLE
New schedule test

### PR DESCRIPTION
**Pull request by vanhauser-thc**
A fix in a central scheduling setup results that the scheduling efficient seems to be degraded - or at least the order of effectiveness has changed.
this compares  the original best schedule with all the fixed ones, plus tests a change in the havoc routine.

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
I am curious if 

make test-run-aflplusplus_no_mopt-openthread-2019-12-23
succeeds locally for you. all these openthread failure seem to show up on openthread, so just curious, maybe try it and see if there is an easy fix. Who does not love green CI :), we can try to look more in next week or so.

**Comment by vanhauser-thc** [comment]
@inferno-chromium yeah I am curious too, as I wrote in the previous PR - why does afl fail but aflfast pass? they are both using the same build.
That aflplusplus_optimal passes can be explained by that I am using a dedicated llvm 11 install.

So my guess is it is a clang issue. Maybe it was updated for llvm 12 for openthread and that is why it fails?

**Comment by vanhauser-thc** [comment]
I think the easiest fix would be to get rid of -Werror in the openthread checkout directory by

sed -i 's/Wshadow -Werror /Wshadow/g' config*

not sure that is the solution you'd like though ;)

**Comment by inferno-chromium** [comment]
> I think the easiest fix would be to get rid of -Werror in the openthread checkout directory by
> 
> sed -i 's/Wshadow -Werror /Wshadow/g' config*
> 
> not sure that is the solution you'd like though ;)

Error disappear if i bump up to latest revision, doing that.

**Comment by jonathanmetzman** [comment]
lgtm

**Pull request merged**
