### PR TITLE
new afl++ mutation experiment

### PR DESCRIPTION
**Pull request by vanhauser-thc**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@Alan32Liu can you please merge this before enjoying your weekend please? :-)
thanks!

**Review by Alan32Liu — APPROVED** [review]

**Comment by Alan32Liu** [comment]
> @Alan32Liu can you please merge this before enjoying your weekend please? :-) thanks!

No problem : )

**Comment by vanhauser-thc** [comment]
thanks!
it is also not showing up in the gs:// bucket ... is it that I made an error in the request yaml? or is something broken?

**Comment by Alan32Liu** [comment]
Yeah, strange.
Monday is a public holiday in Australia, I will check that on Tuesday.

**Pull request merged**
