### PR TITLE
Request experiment on fuzzers in main experiment 

### PR DESCRIPTION
**Pull request by jiradeto**
I would like to request an experiment to benchmark the fuzzers in the [Main Experiment](https://www.fuzzbench.com/reports/paper/Main%20Experiment/index.html). My intention is to evaluate the up-to-date version of each fuzzer.

Thank you very much.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@jiradeto How soon do you need this?
I need to run some experiments of my own and I don't want to run any for outsiders for some time (maybe a week).

**Comment by jiradeto** [comment]
@jonathanmetzman Sure! there's no hurry I can wait until you have available resources. Thanks!

**Comment by jiradeto** [comment]
@jonathanmetzman, would you mind giving me an update on this?

**Comment by jonathanmetzman** [comment]
Hey, could you pull from master again and push to this branch. I want to test your PR with CI. I'll merge your PR if it passes

**Comment by jonathanmetzman** [comment]
Don't know what's going on with CI.

**Comment by jonathanmetzman** [comment]
Sorry, I'm being dumb.
The PR doesn't need to build every fuzzer-benchmark pair in CI, since it's not changing any of them.

**Comment by jonathanmetzman** [comment]
Yeah should be running. Will take a look.

**Comment by jonathanmetzman** [comment]
I think I fixed the issue.
I think deleted the service account we actually use when I was cleaning up some older ones.

**Comment by jonathanmetzman** [comment]
I'd wait ~6 hours for the results to start rolling in.

**Comment by jiradeto** [comment]
@jonathanmetzman hmm it's a bit strange that the results haven't published yet.

**Pull request merged**
