### PR TITLE
[SBFT23]GFuzz

### PR DESCRIPTION
**Pull request by CXWorks**
Placeholder for SBFT'23 fuzzing competition.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
Dear authors,
Thank you for your submission!

We were wondering if you were planning to submit [this `GFuzz`](https://huhong789.github.io/papers/liu:gfuzz.pdf) by any chance?
If I understand correctly, `GFuzz` is designed for `Go` language, yet [our competition](https://sbft23.github.io/tools/fuzzing) only uses `C`/`C++` benchmarks this year, unfortunately.

We would be more than happy to accept your submission if it has been adapted to `C`/`C++` benchmarks.

Wish you a lovely day and look forward to hearing from you.

**Comment by CXWorks** [comment]
> 

Hi, thanks. I'm sorry that this name happens to be the same as GFuzz, but I just come up this name by myself and it will be designed for C/C++.

Shall I change the name of it?

Thanks!

**Comment by Alan32Liu** [comment]
> > 
> 
> Hi, thanks. I'm sorry that this name happens to be the same as GFuzz, but I just come up this name by myself and it will be designed for C/C++.
> 
> Shall I change the name of it?
> 
> Thanks!

Thanks for your prompt response, @CXWorks!
There is no need to change the name, we are also very glad to know that your fuzzer works on `C`/`C++` programs.
Would there be any chance that you could provide more information about your fuzzer? E.g., algorithms, designs, or insights. Many other participants explained those things with a 2-page draft tool report as mentioned in [our competition rule](https://sbft23.github.io/tools/fuzzing).
This will help us decide if we could accept your submission and justify our decision to the conference/work if we decide to do so : )

**Comment by CXWorks** [comment]
@Alan32Liu Thanks. Can I ask for extension for the submission of this proposal until the end of this week?

**Comment by Alan32Liu** [comment]
> @Alan32Liu Thanks. Can I ask for extension for the submission of this proposal until the end of this week?

Sure!
But please be aware that this will not automatically extend your Pull Request deadline (AoE Friday 17 Feb 2023).

**Comment by CXWorks** [comment]
@Alan32Liu Hi Alan, thanks for your help. 

Unfortunately I didn't find any insteresting topic to work with, and I'm sorry for your time and patience. Can I withdraw my PR?

**Comment by Alan32Liu** [comment]
> @Alan32Liu Hi Alan, thanks for your help.
> 
> Unfortunately I didn't find any insteresting topic to work with, and I'm sorry for your time and patience. Can I withdraw my PR?

Sure, no problem!
I will close this PR if you would not mind : )

**Pull request closed without merging**
