### PR TITLE
big afl++ experiment (ctx, counter, release)

### PR DESCRIPTION
**Pull request by vanhauser-thc**
this tests the new CTX implementation variants of @andreafioraldi , plus a fine-grained counter experiment (loops, memory functions), plus tests our upcoming 3.11c bugfix release state.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
not ready for merging yet.

**Comment by andreafioraldi** [comment]
@googlebot I consent.

**Comment by vanhauser-thc** [comment]
@inferno-chromium since your change the CI is crawling ... "2 in progress" ... ;)

**Comment by inferno-chromium** [comment]
> @inferno-chromium since your change the CI is crawling ... "2 in progress" ... ;)

right now, all google org repos are impacted. they have a meeting with github folks today in afternoon to discuss these github actions issues. we can merge if you need the experiment right away (if you are sure things build fine).

**Comment by vanhauser-thc** [comment]
> > @inferno-chromium since your change the CI is crawling ... "2 in progress" ... ;)
> 
> right now, all google org repos are impacted. they have a meeting with github folks today in afternoon to discuss these github actions issues. we can merge if you need the experiment right away (if you are sure things build fine).

ah ok.
No I am not sure that everything builds.
I will try to build on my own and then tell you when everything is fine. that will be way faster ...

**Comment by vanhauser-thc** [comment]
@inferno-chromium tested aflplusplus on all targets and test-run works on all.
it can be merged now.
thanks!

**Comment by vanhauser-thc** [comment]
@jonathanmetzman @inferno-chromium the experiment web page shows no results.
thankfully I can see in the cloud data buckets that the experiment is running and generating results, so it is just the coverage gathering and/or the html generation that has an issue.

https://www.fuzzbench.com/reports/experimental/2021-03-10-aflpp/index.html

**Comment by inferno-chromium** [comment]
> @jonathanmetzman @inferno-chromium the experiment web page shows no results.
> thankfully I can see in the cloud data buckets that the experiment is running and generating results, so it is just the coverage gathering and/or the html generation that has an issue.
> 
> https://www.fuzzbench.com/reports/experimental/2021-03-10-aflpp/index.html

```
warning: /work/measurement-folders/aspell_aspell_fuzzer-aflplusplus_optimal_flcnt/trial-1156057/coverage/data-4183040966513697681_0.profraw: Profile uses zlib compression but the profile reader was built without zlib support
error: No profiles could be merged.
```
i know why, Catena's latest PR on OSS-Fuzz added zlib profile support in llvm script, just need to update dispatcher image here. doing it now

**Comment by inferno-chromium** [comment]
done, and rerequested experiments in 2021-03-11-aflpp*

**Comment by vanhauser-thc** [comment]
> done, and rerequested experiments in 2021-03-11-aflpp*

nope, still not working :(

**Comment by inferno-chromium** [comment]
> > done, and rerequested experiments in 2021-03-11-aflpp*
> 
> nope, still not working :(

cleared my local image, something with cache, now new 03-12 experiment seems to work - see https://www.fuzzbench.com/reports/experimental/2021-03-12-aflpp/index.html
bug one should start in sometime too.

**Comment by vanhauser-thc** [comment]
yes it is running now :) thanks

**Pull request merged**
