### PR TITLE
libafl_libfuzzer optimization experiment

### PR DESCRIPTION
**Pull request by addisoncrump**
We made some heavy optimisations and new features that we'd like to test. Can an experiment be run for:
- libafl_libfuzzer
- libafl_libfuzzer_best (from this PR)
- ~~libafl (depends on #1902; temporarily rebased)~~ please skip while we remediate `libafl_cc`
- aflplusplus
- libfuzzer

Thanks!

### CODE REVIEW

**Comment by addisoncrump** [comment]
having some linkage issues

**Comment by addisoncrump** [comment]
Found an issue with one of our recent optimisations. Marked as draft until it's fixed up.

**Comment by addisoncrump** [comment]
Good to go! Hunted down all the bugs with the recent optimisations (that I'm aware of... :skull:)

libafl_libfuzzer is not affected by the issue identified in #1902 because we don't use libafl_cc, so this is good to go whenever y'all are ready to fire the experiment.

**Comment by addisoncrump** [comment]
Rebased on #1902 for sanity.

**Comment by Alan32Liu** [comment]
Hi @addisoncrump, is this ready for experiments?

If so, would you mind making a trivial modification to [service/gcbrun_experiment.py](https://github.com/google/fuzzbench/blob/master/service/gcbrun_experiment.py)?
This will allow me to launch experiments in this PR. Here is [an example to add a dummy comment](https://github.com/google/fuzzbench/pull/1818/files#diff-e870d8214beac56eaaeda2edc69de842f8382c428329dd8cf826a9cfa5edf7e9) : )
Thanks!

In addition, could you please write your experiment request in [this format](https://github.com/google/fuzzbench/pull/1866#issuecomment-1681565046)?
You can swap the `--experiment-name` and `--fuzzers` parameters with your values.
I would really appreciate that : )

For example, I reckon the command for this case is:
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-05-libafl_best --fuzzers libafl_libfuzzer_best libafl_libfuzzer
```

Where FuzzBench will reuse existing results of `aflplusplus` and `libfuzzer`.

**Comment by addisoncrump** [comment]
We have a couple of more changes in the queue ready, so I'll send this in in a bit :slightly_smiling_face:

**Comment by tokatoka** [comment]
this is ready with all the pr merged? @addisoncrump

**Comment by addisoncrump** [comment]
Yup, let me update the commit

**Comment by addisoncrump** [comment]
All of the relevant libafl changes landed, so I removed libfuzzer_best. For now, this is good to go :heavy_check_mark: 

Let's compare:
 - libafl_libfuzzer
 - libafl
 - aflplusplus
 - libfuzzer

Thanks!

**Comment by addisoncrump** [comment]
Well, that didn't work. Coming back to this in the morning.

**Comment by addisoncrump** [comment]
Superceded by other recent PRs.

**Pull request closed without merging**
