### PR TITLE
new test for pre-3.0 changes

### PR DESCRIPTION
**Pull request by vanhauser-thc**
pre-3.0 changes:
  - LTO and dict2file dictionary now contains interesting cmp value
  - unstable edges completely ignored
  - -i subdir support
  - ignore duplicate seeds
  - partial read of large files
  - qem5

plus requesting a new test run for Tuesday (fuzzcon :) )

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@jonathanmetzman @inferno-chromium 
this can be merged :)
this will be really interesting, v2.68c vs v3.00a should have quite a performance boost. I hope :)

P.S. if you merge this before Monday please update the start time for the experiment to start earlier (I put Tuesday).

**Comment by inferno-chromium** [comment]
> @jonathanmetzman @inferno-chromium
> this can be merged :)
> this will be really interesting, v2.68c vs v3.00a should have quite a performance boost. I hope :)
> 
> P.S. if you merge this before Monday please update the start time for the experiment to start earlier (I put Tuesday).

Date is just an identifier, it will start now.

**Comment by vanhauser-thc** [comment]
didnt know that, thanks!

**Comment by vanhauser-thc** [comment]
and I was several time a bit at panic "if they dont merge it in time they have to modify the date by hand, lets hope the CI run finishes soon!" :D

**Pull request merged**
