### PR TITLE
remove variant, add variants

### PR DESCRIPTION
**Pull request by vanhauser-thc**
still experimenting with more efficient havoc mutations.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Lol, what is aflplusplus_honggfuzz?

**Comment by vanhauser-thc** [comment]
> Lol, what is aflplusplus_honggfuzz?

@robertswiecki - this might be fun and/or interesting for you

this is honggfuzz's mangle.c imported to afl++ as a custom mutator.
It does not have the autodict and cmplog feature, just the mutation strategies.

and the last test run showed how important the autodict and cmplog is for honggfuzz's success.
afl-fuzz with running solely the honggfuzz custom mutator is 3x+ faster than honggfuzz itself. :-)
and as honggfuzz has a better coverage than aflplusplus_honggfuzz this shows how powerful the coverage feature is.

for a fun assessment this PR changes aflplusplus_honggfuzz to have redqueen/cmplog to have a more even playing field :)

but this PR also has serious test cases in there obviously :)

**Comment by jonathanmetzman** [comment]
What should I do with the build failures in aflplusplus_honggfuzz?
It looks like afl-fuzz is segfaulting during fuzzing, so i don't think this can land.

**Comment by vanhauser-thc** [comment]
@jonathanmetzman  I fixed it but then put the wrong commit id in the builder.dockerfile ... now it shoud be fine. fingers crossed.

**Pull request merged**
