### PR TITLE
Integrating the benchmark "proj4" with target "standard_fuzzer", commit date "2019-03-15T01:51"

### PR DESCRIPTION
**Pull request by GiovaniGuizzo**
This project was chosen based on number of bugs.

There are 36 known bugs in this benchmark. We could reproduce 27 of them.

### CODE REVIEW

**Comment by GiovaniGuizzo** [comment]
@googlebot I signed it!

**Comment by Vaush** [comment]
@googlebot I consent.

**Review by inferno-chromium — CHANGES_REQUESTED** [review]
Can you please check lafintel failure and see if it can be fixed, if not feasible, please add to blacklist

```
2021-04-15T00:47:25.5042350Z #19 5.309 + ./configure --disable-shared
2021-04-15T00:47:25.6540829Z #19 5.451 checking for a BSD-compatible install... /usr/bin/install -c
2021-04-15T00:47:25.6541793Z #19 5.461 checking whether build environment is sane... yes
2021-04-15T00:47:25.6542974Z #19 5.473 checking for a thread-safe mkdir -p... /bin/mkdir -p
2021-04-15T00:47:25.6543627Z #19 5.476 checking for gawk... no
2021-04-15T00:47:25.6544125Z #19 5.476 checking for mawk... mawk
2021-04-15T00:47:25.6544675Z #19 5.477 checking whether make sets $(MAKE)... yes
2021-04-15T00:47:25.6545528Z #19 5.490 checking whether make supports nested variables... yes
2021-04-15T00:47:25.6547766Z #19 5.502 checking for gcc... /afl/afl-clang-fast
2021-04-15T00:47:25.7980813Z #19 5.612 checking whether the C compiler works... no
2021-04-15T00:47:25.7982156Z #19 5.636 configure: error: in `/src/proj.4':
2021-04-15T00:47:25.7982876Z #19 5.636 configure: error: C compiler cannot create executables
2021-04-15T00:47:25.7983794Z #19 5.636 See `config.log' for more details
2021-04-15T00:47:25.7984366Z #19 5.663 Traceback (most recent call last):
2021-04-15T00:47:25.7984928Z #19 5.663   File "<string>", line 1, in <module>
2021-04-15T00:47:25.7985585Z #19 5.664   File "/src/fuzzers/lafintel/fuzzer.py", line 53, in build
2021-04-15T00:47:25.7986243Z #19 5.664     utils.build_benchmark()
2021-04-15T00:47:25.8006456Z #19 5.664   File "/src/fuzzers/utils.py", line 76, in build_benchmark
2021-04-15T00:47:25.8007673Z #19 5.664     subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
2021-04-15T00:47:25.8008535Z #19 5.664   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
2021-04-15T00:47:25.8009876Z #19 5.664     raise CalledProcessError(retcode, cmd)
2021-04-15T00:47:25.8011398Z #19 5.664 subprocess.CalledProcessError: Command '['/bin/bash', '-ex', '/src/build.sh']' returned non-zero exit status 77.
2021-04-15T00:47:25.8013319Z #19 ERROR: executor failed running [/bin/sh -c PYTHONPATH=$SRC python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.$FUZZER import fuzzer; fuzzer.build()"]: exit code: 1
2021-04-15T00:47:25.8014586Z ------
2021-04-15T00:47:25.8015575Z  > importing cache manifest from gcr.io/fuzzbench/builders/lafintel/proj4_standard_fuzzer:
```

**Comment by Vaush** [comment]
> 
> 
> Can you please check lafintel failure and see if it can be fixed, if not feasible, please add to blacklist
> 
> ```
> 2021-04-15T00:47:25.5042350Z #19 5.309 + ./configure --disable-shared
> 2021-04-15T00:47:25.6540829Z #19 5.451 checking for a BSD-compatible install... /usr/bin/install -c
> 2021-04-15T00:47:25.6541793Z #19 5.461 checking whether build environment is sane... yes
> 2021-04-15T00:47:25.6542974Z #19 5.473 checking for a thread-safe mkdir -p... /bin/mkdir -p
> 2021-04-15T00:47:25.6543627Z #19 5.476 checking for gawk... no
> 2021-04-15T00:47:25.6544125Z #19 5.476 checking for mawk... mawk
> 2021-04-15T00:47:25.6544675Z #19 5.477 checking whether make sets $(MAKE)... yes
> 2021-04-15T00:47:25.6545528Z #19 5.490 checking whether make supports nested variables... yes
> 2021-04-15T00:47:25.6547766Z #19 5.502 checking for gcc... /afl/afl-clang-fast
> 2021-04-15T00:47:25.7980813Z #19 5.612 checking whether the C compiler works... no
> 2021-04-15T00:47:25.7982156Z #19 5.636 configure: error: in `/src/proj.4':
> 2021-04-15T00:47:25.7982876Z #19 5.636 configure: error: C compiler cannot create executables
> 2021-04-15T00:47:25.7983794Z #19 5.636 See `config.log' for more details
> 2021-04-15T00:47:25.7984366Z #19 5.663 Traceback (most recent call last):
> 2021-04-15T00:47:25.7984928Z #19 5.663   File "<string>", line 1, in <module>
> 2021-04-15T00:47:25.7985585Z #19 5.664   File "/src/fuzzers/lafintel/fuzzer.py", line 53, in build
> 2021-04-15T00:47:25.7986243Z #19 5.664     utils.build_benchmark()
> 2021-04-15T00:47:25.8006456Z #19 5.664   File "/src/fuzzers/utils.py", line 76, in build_benchmark
> 2021-04-15T00:47:25.8007673Z #19 5.664     subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
> 2021-04-15T00:47:25.8008535Z #19 5.664   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
> 2021-04-15T00:47:25.8009876Z #19 5.664     raise CalledProcessError(retcode, cmd)
> 2021-04-15T00:47:25.8011398Z #19 5.664 subprocess.CalledProcessError: Command '['/bin/bash', '-ex', '/src/build.sh']' returned non-zero exit status 77.
> 2021-04-15T00:47:25.8013319Z #19 ERROR: executor failed running [/bin/sh -c PYTHONPATH=$SRC python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.$FUZZER import fuzzer; fuzzer.build()"]: exit code: 1
> 2021-04-15T00:47:25.8014586Z ------
> 2021-04-15T00:47:25.8015575Z  > importing cache manifest from gcr.io/fuzzbench/builders/lafintel/proj4_standard_fuzzer:
> ```

So, I finally managed to access the config.log file. You can find it attached.
As you can see, it says that the builtin option for fsanitize is not supported (for some reason). I am not really sure why this only happens for lafintel, but we don't have any way to selectively change sanitizer options just for a specific (fuzzer, benchmark) pair, do we?
I am not sure how we could solve this, as it seems to be something specific to lafintel.

Also, what is happening with all the variants of aflplusplus? The ones raising errors during checks are not in the fuzzer list anymore, but there are a lot of other different ones.
[config.log](https://github.com/google/fuzzbench/files/6385887/config.log)

**Pull request merged**
