### PR TITLE
[presubmit] Don't complain that coverage is not tested in CI.

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Maybe we should be testing coverage builds in CI? This change makes sense if we don't want to.

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
> Maybe we should be testing coverage builds in CI? This change makes sense if we don't want to.

i think yes, can you add it.

**Review by inferno-chromium — CHANGES_REQUESTED** [review]
requesting changes to actually test coverage config.

**Comment by inferno-chromium** [comment]
We are now testing coverage builds in CI, closing. https://github.com/google/fuzzbench/blob/master/.github/workflows/fuzzers.yml#L20

**Comment by jonathanmetzman** [comment]
> We are now testing coverage builds in CI, closing. https://github.com/google/fuzzbench/blob/master/.github/workflows/fuzzers.yml#L20

We actually are not testing coverage in CI. That change introduced a bug. See complaint about coverage build failure here: https://github.com/google/fuzzbench/pull/921#issuecomment-744596051

Thats because CI uses `test-run-` make targets. But these don't exist for coverage builds because they don't have a `fuzz` function.

**Pull request closed without merging**
