### PR TITLE
new afl++ feature experiment

### PR DESCRIPTION
**Pull request by vanhauser-thc**
tests how performance is impacted if we skip the initial calibration phase. will only impact experiments with a large queue.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@jonathanmetzman the experiment doesnt seem to start, it is not showing up on the cloud bucket.

**Comment by jonathanmetzman** [comment]
There's a breakage. Let me fix it.

**Comment by jonathanmetzman** [comment]
Fixed it hopefully: https://github.com/google/fuzzbench/commit/da5fab4dfcabcd856e0247b90122bb577f0c734e

**Comment by jonathanmetzman** [comment]
There's some weird Google Cloud quota that got added. I have to request an increase. But until it's fulfilled we can't run any experiments. CC @oliverchang

**Comment by vanhauser-thc** [comment]
ok, thanks for the heads up!

**Comment by jonathanmetzman** [comment]
@Navidem This issue also prevented your experiment from running.

**Pull request merged**
