### PR TITLE
update afl++ commit id and _optimal setup

### PR DESCRIPTION
**Pull request by vanhauser-thc**
does not include a new experiment.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by vanhauser-thc** [comment]
added a bug experiment. can be merged I think (no update to any commit it)

**Comment by jonathanmetzman** [comment]
Ping

**Comment by vanhauser-thc** [comment]
@jonathanmetzman 
yeah I am on vacation without Internet.... using the single 15 minute window now :)

**Comment by vanhauser-thc** [comment]
@jonathanmetzman the experiment is stuck after start:
https://www.fuzzbench.com/reports/experimental/2022-04-10-aflpp/index.html

nothing is moving ...

**Comment by jonathanmetzman** [comment]
Looks to me a like an issue generating the report.

**Comment by vanhauser-thc** [comment]
@jonathanmetzman can you restart the report generation? I have no clue how I could create a report once it is done :)

**Comment by jonathanmetzman** [comment]
I did generate it manually and things are still broken. I think the issue is because of all of these benchmarks that were added recently that are now run by default.

**Comment by jonathanmetzman** [comment]
We may need to run this again.

**Comment by jonathanmetzman** [comment]
I think there's a good chance though that just waiting will solve this. I think bug benchmarking can be very bottlenecky

**Comment by vanhauser-thc** [comment]
@jonathanmetzman the report did not move. I guess the experiment is done, can you create a report please? that would be great :)

**Comment by vanhauser-thc** [comment]
@jonathanmetzman so are the bug benchmarks now working correctly?

**Comment by vanhauser-thc** [comment]
asking because in andrea's last run some of the benchmarks only have 6 runs ...

**Comment by jonathanmetzman** [comment]
Sorry lemme look into this.

**Pull request merged**
