### PR TITLE
Integrate project arrow with target parquet-arrow-fuzz

### PR DESCRIPTION
**Pull request by Vaush**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Several fuzzers are failing here

```
[-] PROGRAM ABORT : All test cases time out or crash, giving up!
         Location : perform_dry_run(), afl-fuzz.c:2905

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzers/afl_qemu/fuzzer.py", line 32, in fuzz
    flags=flags)
  File "/src/fuzzers/aflplusplus/fuzzer.py", line 182, in fuzz
    additional_flags=flags)
  File "/src/fuzzers/afl/fuzzer.py", line 119, in run_afl_fuzz
    subprocess.check_call(command, stdout=output_stream, stderr=output_stream)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./afl-fuzz', '-i', '/out/seeds', '-o', '/out/corpus', '-d', '-m', 'none', '-t', '1000+', '-Q', '--', '/out/parquet-arrow-fuzz', '2147483647']' returned non-zero exit status 1.
ERROR:root:Executed command: "nice -n 5 python3 -u -c from fuzzers.afl_qemu import fuzzer; fuzzer.fuzz('/out/seeds', '/out/corpus', '/out/parquet-arrow-fuzz')" returned: 1.
ERROR:root:Fuzz process returned nonzero. Extras: {'traceback': 'Traceback (most recent call last):\n  File "/src/experiment/runner.py", line 202, in run_fuzzer\n    kill_children=True)\n  File "/src/common/new_process.py", line 124, in execute\n    raise subprocess.CalledProcessError(retcode, command)\nsubprocess.CalledProcessError: Command \'[\'nice\', \'-n\', \'5\', \'python3\', \'-u\', \'-c\', "from fuzzers.afl_qemu import fuzzer; fuzzer.fuzz(\'/out/seeds\', \'/out/corpus\', \'/out/parquet-arrow-fuzz\')"]\' returned non-zero exit status 1.\n'}
```

**Review by inferno-chromium — CHANGES_REQUESTED** [review]
See comment above.

**Comment by inferno-chromium** [comment]
Numerous afl++ failures, @Vaush ptal. @vanhauser-thc fyi in case he has thoughts here

```
[*] Target map size: 1029056
25h
[-] PROGRAM ABORT : Target's coverage map size of 1029056 is larger than the one this afl++ is set with (900000). Either set AFL_MAP_SIZE=1029056 and restart  afl-fuzz, or change MAP_SIZE_POW2 in config.h and recompile afl-fuzz
         Location : afl_fsrv_start(), src/afl-forkserver.c:652

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzers/aflplusplus_fast_v1_time/fuzzer.py", line 35, in fuzz
    aflplusplus_fuzzer.fuzz(input_corpus,
  File "/src/fuzzers/aflplusplus/fuzzer.py", line 179, in fuzz
    afl_fuzzer.run_afl_fuzz(input_corpus,
  File "/src/fuzzers/afl/fuzzer.py", line 131, in run_afl_fuzz
    subprocess.check_call(command, stdout=output_stream, stderr=output_stream)
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./afl-fuzz', '-i', '/out/seeds', '-o', '/out/corpus', '-m', 'none', '-t', '1000+', '-d', '-p', 'fast', '-c', '/out/cmplog/parquet-arrow-fuzz', '-x', './afl++.dict', '--', '/out/parquet-arrow-fuzz', '2147483647']' returned non-zero exit status 1.
ERROR:root:Executed command: "nice -n 5 python3 -u -c from fuzzers.aflplusplus_fast_v1_time import fuzzer; fuzzer.fuzz('/out/seeds', '/out/corpus', '/out/parquet-arrow-fuzz')" returned: 1.
ERROR:root:Fuzz process returned nonzero. Extras: {'traceback': 'Traceback (most recent call last):\n  File "/src/experiment/runner.py", line 199, in run_fuzzer\n    new_process.execute(command,\n  File "/src/common/new_process.py", line 124, in execute\n    raise subprocess.CalledProcessError(retcode, command)\nsubprocess.CalledProcessError: Command \'[\'nice\', \'-n\', \'5\', \'python3\', \'-u\', \'-c\', "from fuzzers.aflplusplus_fast_v1_time import fuzzer; fuzzer.fuzz(\'/out/seeds\', \'/out/corpus\', \'/out/parquet-arrow-fuzz\')"]\' returned non-zero exit status 1.\n'}
INFO:root:Doing final sync.
make: *** [test-run-aflplusplus_fast_v1_time-arrow_parquet-arrow-fuzz] Error 1
```

**Comment by vanhauser-thc** [comment]
that one is easy, in runner.Dockerfile the ENV AFL_MAP_SIZE value has to be set to something larger than 1029056

**Comment by inferno-chromium** [comment]
@vanhauser-thc - are they bad perf implications for bumping up AFL_MAP_SIZE across all afl++ variants to like 1048576

**Comment by vanhauser-thc** [comment]
> @vanhauser-thc - are they bad perf implications for bumping up AFL_MAP_SIZE across all afl++ variants to like 1048576

no, the the target only takes as much from the shared mem as needed.
The value I put in was larger than anything I have ever encountered anywhere. well now there is a new record :)

**Comment by inferno-chromium** [comment]
Merging this and bumping up AFL_MAP_SIZE as said in last comment in another cl.

**Pull request merged**
