### PR TITLE
resubmit experiment + fixes

### PR DESCRIPTION
**Pull request by vanhauser-thc**
fingers crossed :)

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@inferno-chromium I think this can be merged already

**Comment by jonathanmetzman** [comment]
Do you want me to review this?

**Comment by vanhauser-thc** [comment]
@jonathanmetzman its a resubmit because of a cloud failure. plus two fixes that are not relevant for this run but have shows not to break in the CI - so no, not required :)

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman its a resubmit because of a cloud failure. plus two fixes that are not relevant for this run but have shows not to break in the CI - so no, not required :)

SOrry I think I meant to write my first comment on #1068.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by inferno-chromium** [comment]
i will merge, but @vanhauser-thc please do a look at this comment - https://github.com/google/fuzzbench/pull/1068#issuecomment-772901213. Some of these failures are legit and reproduce locally. hopefully those fixes fix some other failures as well - https://github.com/google/fuzzbench/actions/runs/536892982. Looks like all of these failures started with clang-12 install, can you try using latest clang from base-builder itself ?

**Comment by vanhauser-thc** [comment]
@inferno-chromium AFAIK the freetype bug is fixed (llvm internal error I had to work around) - unless there is something new but it worked for me locally. the hecv will be an LTO issue, that is on my list to check out but not relevant to this experiment. (nor the freetype one if that is still an issue)

**Comment by vanhauser-thc** [comment]
This re-run too shows weirdness: https://www.fuzzbench.com/reports/experimental/2021-02-04-aflpp/index.html

e.g. bloaty (and other) are stuck at 4h since 9 hours now.

**Comment by inferno-chromium** [comment]
> This re-run too shows weirdness: https://www.fuzzbench.com/reports/experimental/2021-02-04-aflpp/index.html
> 
> e.g. bloaty (and other) are stuck at 4h since 9 hours now.

@jonathanmetzman - can you please check it out.

**Comment by vanhauser-thc** [comment]
and since the 3 hours nothing moved in the html output

**Comment by inferno-chromium** [comment]
@vanhauser-thc - bloaty is at 5hr30, several others at 16 hr (pcap), 10 hr (curl), so i see things moving. measurer is right now a giant 96 core instance, we need to break it up in next month or so, then everything will be just real-time, sorry about slowness.

**Pull request merged**
