### PR TITLE
Request an experiment for aflpp_symsan

### PR DESCRIPTION
**Pull request by chenju2k6**
Added a new fuzzer, `aflpp_symsan`. This fuzzer is a version of aflplusplus that features a customized mutator, which is built on top of our Concolic Execution Engine, Symsan.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
Hi @chenju2k6, would you mind making a trivial modification to [service/gcbrun_experiment.py](https://github.com/google/fuzzbench/blob/master/service/gcbrun_experiment.py)?
This will allow me to launch experiments in this PR before merging. Here is [an example to add a dummy comment](https://github.com/google/fuzzbench/pull/1818/files#diff-e870d8214beac56eaaeda2edc69de842f8382c428329dd8cf826a9cfa5edf7e9) : )
Thanks!

BTW, you don't have to add experiment requests to [service/experiment-requests.yaml](https://github.com/google/fuzzbench/blob/master/service/experiment-requests.yaml), as we are running experiments from this PR with `/gcbrun` commands.
Instead, could you please write the experiment request in [this format](https://github.com/google/fuzzbench/pull/1866#issuecomment-1681565046)?
You can swap the `--experiment-name` and `--fuzzers` parameters with your values.
I would really appreciate that : )

**Comment by chenju2k6** [comment]
> Hi @chenju2k6, would you mind making a trivial modification to [service/gcbrun_experiment.py](https://github.com/google/fuzzbench/blob/master/service/gcbrun_experiment.py)? This will allow me to launch experiments in this PR before merging. Here is [an example to add a dummy comment](https://github.com/google/fuzzbench/pull/1818/files#diff-e870d8214beac56eaaeda2edc69de842f8382c428329dd8cf826a9cfa5edf7e9) : ) Thanks!
> 
> BTW, you don't have to add experiment requests to [service/experiment-requests.yaml](https://github.com/google/fuzzbench/blob/master/service/experiment-requests.yaml), as we are running experiments from this PR with `/gcbrun` commands. Instead, could you please write the experiment request in [this format](https://github.com/google/fuzzbench/pull/1866#issuecomment-1681565046)? You can swap the `--experiment-name` and `--fuzzers` parameters with your values. I would really appreciate that : )

This is the command:

/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-08-17-symsan-aflpp-symsan --fuzzers symsan_aflplusplus

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-08-17-symsan-aflpp-symsan --fuzzers symsan_aflplusplus

**Comment by Alan32Liu** [comment]
> This is the command:

Thanks, launched.
Experiment data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-08-17-symsan-aflpp-symsan/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-08-17-symsan-aflpp-symsan/index.html).

Just a minor tip: FuzzBench expects experiment names to be [within 30 chars.](https://github.com/google/fuzzbench/blob/a516f8889f44b9804c23f8c5c7807eb8a0b55d6e/experiment/run_experiment.py#L47)
Your experiment name is perfectly fine because it is exactly 30 chars.
Please consider using a shorter name in the future : )
Thanks!

**Comment by chenju2k6** [comment]
@Alan32Liu Thank you for your assistance. We have received the results from our fuzzer. To provide context for these results, I would like to compare them with the results of other fuzzers using the same benchmarks. Could you please advise me on how to proceed?

**Comment by Alan32Liu** [comment]
> @Alan32Liu Thank you for your assistance. We have received the results from our fuzzer. To provide context for these results, I would like to compare them with the results of other fuzzers using the same benchmarks. Could you please advise me on how to proceed?

Once the experiment finishes, FuzzBench will merge prev results of core fuzzers with your results.
No action is needed : )

**Comment by Alan32Liu** [comment]
Hi @chenju2k6 , please feel free to close the PR if no further experiment is needed :)
Thanks!

**Comment by chenju2k6** [comment]
Thanks. Closing.

**Pull request closed without merging**
