### PR TITLE
Another LibAFL compaison on new programs of SBFT'23

### PR DESCRIPTION
**Pull request by tokatoka**
Hi @Alan32Liu.

This is another experiment following #1840 
Is it possible to run the experiment on the 17 coverage-based benchmarks from SBFT'23?

I would like to run these fuzzers
``` 
- aflplusplus
- libfuzzer
- libafl
- honggfuzz
- libafl_fuzzbench_cmplog
- libafl_fuzzbench_cov_accounting
- libafl_fuzzbench_explore
- libafl_fuzzbench_fast
- libafl_fuzzbench_cmplog
- libafl_fuzzbench_mopt
- libafl_fuzzbench_naive
- libafl_fuzzbench_naive_ctx
- libafl_fuzzbench_ngram4
- libafl_fuzzbench_ngram8
- libafl_fuzzbench_rand_scheduler
- libafl_fuzzbench_value_profile
- libafl_fuzzbench_weighted
```

on
```
- arduinojson_json_fuzzer
- assimp_assimp_fuzzer
- astc-encoder_fuzz_astc_physical_to_symbolic
- botan_tls_server
- brotli_decode_fuzzer
- double-conversion_string_to_double_fuzzer
- draco_draco_pc_decoder_fuzzer
- dropbear_fuzzer-postauth_nomaths
- firestore_firestore_serializer_fuzzer
- fmt_chrono-duration-fuzzer
- guetzli_guetzli_fuzzer
- icu_unicode_string_codepage_create_fuzzer
- jansson_json_load_dump_fuzzer
- libaom_av1_dec_fuzzer
- libcoap_pdu_parse_fuzzer
- libhevc_hevc_dec_fuzzer
- librdkafka_fuzz_regex
```

### CODE REVIEW

**Comment by Alan32Liu** [comment]
No problem, @tokatoka. Thanks for listing the fuzzers and benchmarks in the comment, this makes my life easier!
BTW, you don't have to edit the `service/experiment-requests.yaml` file: we run all experiments here via gcb commands : )

There is one minor issue: FuzzBench does not scale well when we run too many fuzzers in one experiment, (last time it took almost a month to finish 10+ fuzzers). It would be better if we could limit the number of fuzzers below 5, and run multiple experiments in parallel instead.

Because of that, I will remove the following base fuzzers. They are not modified in your PR, FuzzBench will merge their old results to your report once your experiment finishes:
```
- aflplusplus
- libfuzzer
- libafl
- honggfuzz
```

In addition, for the rest 13 fuzzers, I will divide them into the following 3 groups, would that look good to you?
```
- libafl_fuzzbench_cmplog
- libafl_fuzzbench_cov_accounting
- libafl_fuzzbench_explore
- libafl_fuzzbench_fast
- - libafl_fuzzbench_mopt
```

```
- libafl_fuzzbench_naive
- libafl_fuzzbench_naive_ctx
- libafl_fuzzbench_ngram4
- libafl_fuzzbench_ngram8
```

```
- libafl_fuzzbench_rand_scheduler
- libafl_fuzzbench_value_profile
- libafl_fuzzbench_weighted
```

(`libafl_fuzzbench_cmplog` showed up twice in your list; I only kept one above).

If you'd like to have them on one report, [here is a guide](https://google.github.io/fuzzbench/developing-fuzzbench/custom_analysis_and_reports) to merge results.

**Comment by tokatoka** [comment]
> Because of that, I will remove the following base fuzzers.

Yes ok.

> In addition, for the rest 13 fuzzers, I will divide them into the following 3 groups, would that look good to you?

Looks good. Thank you!

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks  arduinojson_json_fuzzer assimp_assimp_fuzzer astc-encoder_fuzz_astc_physical_to_symbolic botan_tls_server brotli_decode_fuzzer double-conversion_string_to_double_fuzzer draco_draco_pc_decoder_fuzzer dropbear_fuzzer-postauth_nomaths firestore_firestore_serializer_fuzzer fmt_chrono-duration-fuzzer guetzli_guetzli_fuzzer icu_unicode_string_codepage_create_fuzzer jansson_json_load_dump_fuzzer libaom_av1_dec_fuzzer libcoap_pdu_parse_fuzzer libhevc_hevc_dec_fuzzer librdkafka_fuzz_regex --fuzzers libafl_fuzzbench_cmplog libafl_fuzzbench_cov_accounting libafl_fuzzbench_explore libafl_fuzzbench_fast libafl_fuzzbench_mopt --experiment-name 2023-08-24-libafl-1

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks arduinojson_json_fuzzer assimp_assimp_fuzzer astc-encoder_fuzz_astc_physical_to_symbolic botan_tls_server brotli_decode_fuzzer double-conversion_string_to_double_fuzzer draco_draco_pc_decoder_fuzzer dropbear_fuzzer-postauth_nomaths firestore_firestore_serializer_fuzzer fmt_chrono-duration-fuzzer guetzli_guetzli_fuzzer icu_unicode_string_codepage_create_fuzzer jansson_json_load_dump_fuzzer libaom_av1_dec_fuzzer libcoap_pdu_parse_fuzzer libhevc_hevc_dec_fuzzer librdkafka_fuzz_regex --fuzzers libafl_fuzzbench_cmplog libafl_fuzzbench_cov_accounting libafl_fuzzbench_explore libafl_fuzzbench_fast libafl_fuzzbench_mopt --experiment-name 2023-08-24-libafl-1

**Comment by Alan32Liu** [comment]
gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks arduinojson_json_fuzzer assimp_assimp_fuzzer astc-encoder_fuzz_astc_physical_to_symbolic botan_tls_server brotli_decode_fuzzer double-conversion_string_to_double_fuzzer draco_draco_pc_decoder_fuzzer dropbear_fuzzer-postauth_nomaths firestore_firestore_serializer_fuzzer fmt_chrono-duration-fuzzer guetzli_guetzli_fuzzer icu_unicode_string_codepage_create_fuzzer jansson_json_load_dump_fuzzer libaom_av1_dec_fuzzer libcoap_pdu_parse_fuzzer libhevc_hevc_dec_fuzzer librdkafka_fuzz_regex --fuzzers  libafl_fuzzbench_rand_scheduler libafl_fuzzbench_value_profile libafl_fuzzbench_weighted--experiment-name 2023-08-24-libafl-3

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks arduinojson_json_fuzzer assimp_assimp_fuzzer astc-encoder_fuzz_astc_physical_to_symbolic botan_tls_server brotli_decode_fuzzer double-conversion_string_to_double_fuzzer draco_draco_pc_decoder_fuzzer dropbear_fuzzer-postauth_nomaths firestore_firestore_serializer_fuzzer fmt_chrono-duration-fuzzer guetzli_guetzli_fuzzer icu_unicode_string_codepage_create_fuzzer jansson_json_load_dump_fuzzer libaom_av1_dec_fuzzer libcoap_pdu_parse_fuzzer libhevc_hevc_dec_fuzzer librdkafka_fuzz_regex --fuzzers libafl_fuzzbench_naive libafl_fuzzbench_naive_ctx libafl_fuzzbench_ngram4 libafl_fuzzbench_ngram8 --experiment-name 2023-08-24-libafl-2

**Comment by Alan32Liu** [comment]
> Hi @tokatoka, I just realized that this PR is on the wrong branch: If you'd like to use benchmarks that are only available in [SBFT'23](https://github.com/google/fuzzbench/tree/SBFT'23), (e.g. [arduinojson_json_fuzzer](https://github.com/google/fuzzbench/tree/SBFT'23/benchmarks/arduinojson_json_fuzzer)), then please create a PR based on it.
> 
> The experiment failed to launch because the current master branch does not contain these benchmarks.
> 
> Please feel free to create a new PR, I will leave the experiment command below for documentation purposes.

Gentle ping : ) @tokatoka

**Comment by tokatoka** [comment]
Hey sorry for the late reply. I was sick.

> Please feel free to create a new PR, I will leave the experiment command below for documentation purposes.

Yes! will do. thanks

**Pull request closed without merging**
