### PR TITLE
[honggfuzz] Update version

### PR DESCRIPTION
**Pull request by robertswiecki**
ASAN is not technically required for honggfuzz to work in the fuzzbench
mode (i.e. to increase coverage), so let's try to make it work w/o it
(as it should be faster).

This PR is mostly to run presubmit checks, but if it passes them
cleanly, we could as well get it into fuzzbench code.

Also: add liblzma-dev, as it might be needed now due to some problems
with incorrect ubuntu libunwind-dev package build.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
See also https://github.com/google/fuzzbench/pull/126
Thanks for the other fixes, but ASan is planned to be removed soon.
We are trying to stabilize our CI atm (we had a bug which caused OSS-Fuzz benchmarks to be not built and that led to some PRs checked in and broke those benchmarks. our p0 priority is to get CI first asap, then PR will flow smoothly).

**Comment by inferno-chromium** [comment]
Can revert changes in fuzzers/honggfuzz/fuzzer.py, keep the others (since #126 will remove ASan properly).

**Comment by robertswiecki** [comment]
Thanks, I'll wait for the presubmits to finish, cause I'm curious, and I'll remove asan change.

**Comment by robertswiecki** [comment]
Tho https://github.com/google/fuzzbench/pull/126 doesn't change hongfuzz's compilation flags, no?

**Comment by inferno-chromium** [comment]
> Tho #126 doesn't change hongfuzz's compilation flags, no?

Yes i should have counted fuzzers when reviewing, thanks for noticing.

**Comment by robertswiecki** [comment]
QQ: do you intend to change https://github.com/google/fuzzbench/pull/126 or shall we submit this PR as is to simplify things?

**Comment by inferno-chromium** [comment]
> QQ: do you intend to change #126 or shall we submit this PR as is to simplify things?

#126 should add Honggfuzz's ASAN change since it becomes easier to revert if needed. This PR can do rest of the Dockerfile changes which are independent. We will still merge these 2 prs after CI is fixed, since we want to ensure everything builds, so can be a day or two.

**Comment by jonathanmetzman** [comment]
I'll make the ASAN change in another PR. The lzma change I also made already (in #116).

**Pull request merged**
