### PR TITLE
Experiment request

### PR DESCRIPTION
**Pull request by RafaelTupynamba**
Hi,
I'd like to request an experiment with a new fuzzer.
Thank you,
Rafael.

### CODE REVIEW

**Comment by RafaelTupynamba** [comment]
@googlebot I signed it!

**Comment by RafaelTupynamba** [comment]
@googlebot I fixed it.

**Comment by jonathanmetzman** [comment]
> Hi,
> I'd like to request an experiment with a new fuzzer.
> Thank you,
> Rafael.

Hi, we're too busy at the moment and can't run this experiment until next week.
Sorry,
Jonathan

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
The bug based benchmark build is failing in CI. Since this PR isn't requesting that kind of experiment, I'm comfortable merging this anyway.

**Pull request merged**
