### PR TITLE
afl++ impact of edge collisions on bug finding

### PR DESCRIPTION
**Pull request by pietroborrello**
We would like to request a simple experiment to assess the impact of edge collisions on bug finding capabilities, for a paper we are just finalizing.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
there are some CI failures due to build failing, can you check those out - https://github.com/google/fuzzbench/runs/4738035062?check_suite_focus=true

**Comment by pietroborrello** [comment]
@inferno-chromium I excluded the failing benchmarks

**Review by inferno-chromium — APPROVED** [review]
Please do remember to remove these variants once the experiment completes (and report generated).

**Comment by pietroborrello** [comment]
perfect, thanks!

**Comment by pietroborrello** [comment]
@inferno-chromium excluded some other benchmarks that were only excluded for a single fuzzer and not both

**Comment by pietroborrello** [comment]
@inferno-chromium it seems the checks run fine now, you can merge the PR. The auto-merge got disabled since my last push.
Thank you for your work

**Comment by jonathanmetzman** [comment]
pietroborrello - sorry for the delay

**Pull request merged**
