### PR TITLE
AFLChurn++ Experiment

### PR DESCRIPTION
**Pull request by Dammo3**
Hi,

I have added two fuzzers: AFLChurn and AFLChurn++

AFLChurn is built off AFL, and AFLChurn++ is built of AFL++, so I've pretty much copied the respective integration files

I haven't been able to successfully test them locally so at the moment I'm just hoping the CI can help me identify any issues

### CODE REVIEW

**Comment by DonggeLiu** [comment]
Hi @Dammo3, I've enabled the CIs.
If them look good to you and you'd like to run an experiment, could you please leave a comment on your experiment command, e.g.:
```bash
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name <date-exp-name> --fuzzers <fuzzers> --benchmarks <benchmarks>
```
E.g.,
```bash
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-06 --fuzzers aflchurn aflchurnplusplus  --benchmarks bloaty_fuzz_target
```

**Comment by Dammo3** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-07-aflchurnplusplus --fuzzers afl aflplusplus aflchurnplusplus

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-07-aflchurnplusplus --fuzzers afl aflplusplus aflchurnplusplus

**Comment by DonggeLiu** [comment]
Just a minor note: There is no need to include the baseline fuzzers in the experiment request, because FuzzBench will automatically [merge their recent results](https://github.com/google/fuzzb%20nch/blob/master/service/experiment-config.yaml#L18) in your report.

**Comment by DonggeLiu** [comment]
Experiment `2024-08-07-aflchurnplusplus` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-07-aflchurnplusplus/).
[The experiment report(experimental)](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-08-07-aflchurnplusplus/index.html).

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-07-aflchurnplusplus --fuzzers aflchurnplusplus

**Pull request closed without merging**
