### PR TITLE
afl++ qemu vs frida

### PR DESCRIPTION
**Pull request by vanhauser-thc**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
This can be merged :) ty

**Review by inferno-chromium — APPROVED** [review]

**Comment by vanhauser-thc** [comment]
@inferno-chromium did something go wrong? the experiment is not showing up yet on the web page - 24h after merge.

**Comment by inferno-chromium** [comment]
Something is broken w.r.t wheel, i tried upgrading from 3.7 to 3.8 on bot, didnt work, @jonathanmetzman can you take a look

```
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /tmp/fuzzbench-automatic-experiment-repo/.venv/bin/python3 /tmp/fuzzbench-automatic-experiment-repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpp3otm6g8
         cwd: /tmp/pip-install-0spdsb5t/PyQtWebEngine
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/tmp/fuzzbench-automatic-experiment-repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 64, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/fuzzbench-automatic-experiment-repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/tmp/fuzzbench-automatic-experiment-repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/fuzzbench-automatic-experiment-repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 66, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/tmp/fuzzbench-automatic-experiment-repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 95, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-ch9nzfaz/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/tmp/pip-build-env-ch9nzfaz/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-ch9nzfaz/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 481, in setup
        self.apply_user_defaults(tool)
      File "/tmp/pip-build-env-ch9nzfaz/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-ch9nzfaz/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 227, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-ch9nzfaz/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/fuzzbench-automatic-experiment-repo/.venv/bin/python3 /tmp/fuzzbench-automatic-experiment-repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpp3otm6g8 Check the logs for full command output.
```

**Comment by inferno-chromium** [comment]
Seems fixed now, experiment started, lets check back in a few hours to see if report shows up. @jonathanmetzman fyi

**Pull request merged**
