### PR TITLE
afl++ cmplog experiment

### PR DESCRIPTION
**Pull request by vanhauser-thc**
testing 3 changes to afl++'s cmplog.
please add as soon as possible, thank you :)

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
the CI errors are not mine:
```
==================================== ERRORS ====================================
____________ ERROR collecting analysis/test_coverage_data_utils.py _____________
ImportError while importing test module '/home/runner/work/fuzzbench/fuzzbench/analysis/test_coverage_data_utils.py'.
```

```
 =========================== short test summary info ============================
ERROR analysis/test_coverage_data_utils.py
ERROR analysis/test_data_utils.py
ERROR analysis/test_experiment_results.py
ERROR analysis/test_plotting.py
ERROR analysis/test_stat_tests.py
ERROR experiment/test_dispatcher.py
ERROR experiment/test_reporter.py
!!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 13 warnings, 7 errors in 6.50s ========================
```

none of my changes are reporting errors in the CI (anymore).

**Comment by vanhauser-thc** [comment]
@jonathanmetzman the fuzzers to test build, so if possible please merge :)

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by vanhauser-thc** [comment]
@jonathanmetzman can you have a look? It looks like something went wrong. most targets are stuck at 30min for over 12 hours how.
https://www.fuzzbench.com/reports/experimental/2022-11-22-aflpp-cmplog/index.html

**Comment by vanhauser-thc** [comment]
ok one of my dev changes crashes ... damn ... will fix and submit a new experiment

**Pull request merged**
