### PR TITLE
best schedulers vs instrumentation types

### PR DESCRIPTION
**Pull request by vanhauser-thc**
this removes the previous afl++ instances that tested the schedules and uses the best two of them plus "explore" (that was not part of the test) and combines them with the 4 available target instrumentation options: ctx, instrim, ngram-2, ngram-4 and standard instrumentation.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
AFL++ fails to build with bloaty with this error message:
```
2020-04-13T22:19:12.4018568Z CXXFLAGS = -stdlib=libc++ -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -O3
2020-04-13T22:19:14.6692773Z Building benchmark
2020-04-13T22:19:14.6788822Z [91m+ cd /work
2020-04-13T22:19:14.6798929Z [0m[91m+ cmake -G Ninja -DBUILD_TESTING=false /src/bloaty
2020-04-13T22:19:14.7501082Z [0m-- The C compiler identification is unknown
2020-04-13T22:19:14.7836093Z -- The CXX compiler identification is unknown
2020-04-13T22:19:14.7878672Z -- Check for working C compiler using: Ninja
2020-04-13T22:19:14.7986241Z -- Check for working C compiler using: Ninja -- broken
2020-04-13T22:19:14.7990029Z [91mCMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
2020-04-13T22:19:14.7990593Z   The C compiler "/afl/afl-clang-fast" is not able to compile a simple test
2020-04-13T22:19:14.7990707Z   program.
2020-04-13T22:19:14.7990776Z 
2020-04-13T22:19:14.7990881Z   It fails with the following output:
2020-04-13T22:19:14.7990936Z 
2020-04-13T22:19:14.7991040Z    Change Dir: /work/CMakeFiles/CMakeTmp
2020-04-13T22:19:14.7991094Z 
2020-04-13T22:19:14.7991192Z   
2020-04-13T22:19:14.7991240Z 
2020-04-13T22:19:14.7991344Z   Run Build Command:"/usr/bin/ninja" "cmTC_bf04f"
2020-04-13T22:19:14.7991399Z 
2020-04-13T22:19:14.7991506Z   [1/2] Building C object CMakeFiles/cmTC_bf04f.dir/testCCompiler.c.o
2020-04-13T22:19:14.7991581Z 
2020-04-13T22:19:14.7991853Z   FAILED: /afl/afl-clang-fast -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm
2020-04-13T22:19:14.7992111Z   -Wno-unused-command-line-argument -O3 -o
2020-04-13T22:19:14.7992380Z   CMakeFiles/cmTC_bf04f.dir/testCCompiler.c.o -c testCCompiler.c
2020-04-13T22:19:14.7992441Z 
2020-04-13T22:19:14.7992648Z   )B
2020-04-13T22:19:14.7992697Z 
2020-04-13T22:19:14.7992973Z   [-] PROGRAM ABORT : unknown AFL_LLVM_INSTRUMENT value: default
2020-04-13T22:19:14.7993049Z 
2020-04-13T22:19:14.7993296Z            Location : func_unknown(), afl-clang-fast.c:589
2020-04-13T22:19:14.7993368Z 
2020-04-13T22:19:14.7993463Z   
2020-04-13T22:19:14.7993511Z 
2020-04-13T22:19:14.7993610Z   ninja: build stopped: subcommand failed.
2020-04-13T22:19:14.7993663Z 
2020-04-13T22:19:14.7993759Z   
2020-04-13T22:19:14.7993806Z 
2020-04-13T22:19:14.7993900Z   
2020-04-13T22:19:14.7993945Z 
2020-04-13T22:19:14.7994049Z   CMake will not be able to correctly generate this project.
2020-04-13T22:19:14.7994158Z Call Stack (most recent call first):
2020-04-13T22:19:14.7994266Z   CMakeLists.txt:3 (project)
```

It also fails on freetype with this error: 
```
2020-04-13T22:20:34.8247237Z checking whether the C compiler works... no
```
Can you check if these are false positives please?

**Comment by vanhauser-thc** [comment]
damnit it was so sure I had implemented that. fixed. sorry!

**Comment by andreafioraldi** [comment]
@vanhauser-thc rebase your changes with AFLplusplus/fuzzbench. Now confs for afl++ can be made as described in https://github.com/google/fuzzbench/pull/225.
I included also the ctx, ngram2, ngram4, ngram8 so that you can use it. just use `aflplusplus.build("ctx", "instrim")` for istance.

**Comment by vanhauser-thc** [comment]
you can not use ctx/instrim/lto/ngramX together but yes ok

**Comment by jonathanmetzman** [comment]
We have some concerns that doubling the number of fuzzers might cause us to run into some scaling issues that we'd rather avoid right now. So what i'll do is I'll run a full experiment without all of these AFL++ clones and then run and then run one with the afl++ fuzzers after.

**Comment by vanhauser-thc** [comment]
andrea did different things than me and we were not aware of each others doings, so there are two PRs, and both collide ... I will incorporate andrea's changes in this one here.

the aflplusplus_cmplog and aflplusplus_mopt ones are "permanent", all other afl++ ones are temporary ones.

**Comment by jonathanmetzman** [comment]
> andrea did different things than me and we were not aware of each others doings, so there are two PRs, and both collide ... I will incorporate andrea's changes in this one here.
> 
> the aflplusplus_cmplog and aflplusplus_mopt ones are "permanent", all other afl++ ones are temporary ones.

sounds good.

**Comment by vanhauser-thc** [comment]
I will create a new PR, that is easier.

**Pull request closed without merging**
