### PR TITLE
ci test  - do not merge

### PR DESCRIPTION
**Pull request by vanhauser-thc**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
I think I found the issue. `-march=native` seems to generate mis-optimized code for some specific intel CPUs that violate memory and result in a segfault. What is weird is that it happens with both clang and gcc compiler. But removing this compile flag seems to fix it at least for the CI.

I noted another issue btw - only outdated python3 is available in some build images, e.g. for bloaty. qemu does not build with that python3.5. hence aflplusplus_qemu fails for this and other benchmark targets.

**Comment by inferno-chromium** [comment]
> I think I found the issue. `-march=native` seems to generate mis-optimized code for some specific intel CPUs that violate memory and result in a segfault. What is weird is that it happens with both clang and gcc compiler. But removing this compile flag seems to fix it at least for the CI.
> 
> I noted another issue btw - only outdated python3 is available in some build images, e.g. for bloaty. qemu does not build with that python3.5. hence aflplusplus_qemu fails for this and other benchmark targets.

You rock Sir!!! yes fixed my local too.
Can you reenable 
aflplusplus_optimal is not included in fuzzer list in /home/runner/work/fuzzbench/fuzzbench/.github/workflows/fuzzers.yml.
aflplusplus_eclipser is not included in fuzzer list in /home/runner/work/fuzzbench/fuzzbench/.github/workflows/fuzzers.yml.
so that presubmit is fixed. then can merge this (i will approve this).

for those old build images [old python], i do plan to remove build hash hardcode from their dockerfile. i think all build benchmark should use the same oss-fuzz latest base-builder.

**Review by inferno-chromium — APPROVED** [review]
Just uncomment this

          # Disabled due to segfaults and timeouts.
          # See https://github.com/google/fuzzbench/issues/1073.	          # See https://github.com/google/fuzzbench/issues/1073.
          # - aflplusplus_optimal	          # - aflplusplus_optimal
          # - aflplusplus_eclipser	          # - aflplusplus_eclipser

**Comment by vanhauser-thc** [comment]
so weird. I have seen march=native breaking cross-system usage, obivously, but same-system ... I suspected that when I saw that your system is a xeon, so it had to be something about the CPU, because it could not be the compiler or kernel or docker version...

**Comment by vanhauser-thc** [comment]
optimal fails, will fix that the next days

**Pull request merged**
