### PR TITLE
LibAFL Const CmpLogs Experiment

### PR DESCRIPTION
**Pull request by DanBlackwell**
Hi, right now LibAFL doesn't care whether sanitizer coverage trace cmps have a constant argument or not. I've made a quick and dirty implementation to see if there's much benefit to using this data.

### CODE REVIEW

**Comment by DanBlackwell** [comment]
Hi @DonggeLiu, I'd like to see if this proposed change will be useful to the LibAFL maintainers; could you run an experiment with the following please?

```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-09-16-libafl-constcmp --fuzzers libafl_71ed5c libafl_const_cmplogs
```

Thanks!

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-09-16-libafl-constcmp --fuzzers libafl_71ed5c libafl_const_cmplogs

**Comment by DanBlackwell** [comment]
Hi @DonggeLiu could you please run:

```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-09-20-libafl-constcmp --fuzzers libafl_const_cmplogs
```

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-09-20-libafl-constcmp --fuzzers libafl_const_cmplogs

**Comment by DanBlackwell** [comment]
Hi @DonggeLiu, I realised I managed to screw up a C macro in that last one. Any chance you could run this fixed one instead? Thanks!

```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-09-20b-libafl-constcmp --fuzzers libafl_const_cmplogs
```

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-09-23-libafl-constcmp --fuzzers libafl_const_cmplogs

**Pull request closed without merging**
