### PR TITLE
New scheduling algorithm for LibAFL

### PR DESCRIPTION
**Pull request by tokatoka**
We want to test a new scheduling algorithm that gives less priority to the testcases that discovered crashes.

The command is
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-04-24-libafl --fuzzers libafl libafl_penalize
```

### CODE REVIEW

**Comment by tokatoka** [comment]
@DonggeLiu 
Can you run this experiment? Thanks

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-04-30-libafl --fuzzers libafl libafl_penalize

**Comment by DonggeLiu** [comment]
> @DonggeLiu Can you run this experiment? Thanks

Absolutely! Sorry about the delay, please always feel free to ping me if I missed the request.

It appears you forgot to modify [service/gcbrun_experiment.py](https://github.com/google/fuzzbench/blob/master/service/gcbrun_experiment.py), though : )
Here is [a quick example](https://github.com/google/fuzzbench/pull/1818/files#diff-e870d8214beac56eaaeda2edc69de842f8382c428329dd8cf826a9cfa5edf7e9).
Thanks!

**Comment by tokatoka** [comment]
Sorry i always forget that.

Fixed it now!

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-05-02-libafl --fuzzers libafl libafl_penalize

**Comment by tokatoka** [comment]
Thank you!

**Pull request closed without merging**
