### PR TITLE
remove temporary fuzzers, update commit id, typos

### PR DESCRIPTION
**Pull request by vanhauser-thc**
This removes the temporary variants, updates the commit it - plus fixes typos in the report template.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Do you need another experiment for this change? I assume not.

**Comment by vanhauser-thc** [comment]
I have a long list :)
some I can do with our test server, but others I cannot.
However I am pretty busy this week so designing the next test case will take some time.
Next will be most likely new mutation options.

**Comment by vanhauser-thc** [comment]
With the initial 7 hours of 2020-07-17 it might maybe be a good idea to do a full run again and see if the results are same as previous runs or if there is a difference as it looks in this one?

**Comment by jonathanmetzman** [comment]
Yeah I'll rerun when I get a chance. There are some other other things in the queue, but I should get to it pretty soon.

**Comment by jonathanmetzman** [comment]
> With the initial 7 hours of 2020-07-17 it might maybe be a good idea to do a full run again and see if the results are same as previous runs or if there is a difference as it looks in this one?

Just kicked off an experiment for this. Should appear on http://commondatastorage.googleapis.com/fuzzbench-reports/oss-fuzz-benchmarks/index.html in a couple hours.

**Comment by vanhauser-thc** [comment]
the results look "normal", not like the other run :)

**Pull request merged**
