### PR TITLE
Request focus function for libarchive

### PR DESCRIPTION
**Pull request by Navidem**

### CODE REVIEW

**Comment by Navidem** [comment]
pending for #1447 to merge.

**Review by jonathanmetzman — APPROVED** [review]
It seems a bit wasteful to do only one benchmark. Try to add a few more if you can

**Comment by jonathanmetzman** [comment]
This CI failure is correct because this PR does not work yet.

**Comment by Navidem** [comment]
> It seems a bit wasteful to do only one benchmark. Try to add a few more if you can

I will, in future experiments as we discussed.

**Pull request merged**
