### PR TITLE
fix cmplog introspection experiment

### PR DESCRIPTION
**Pull request by vanhauser-thc**
fixes cmplog introspection variant and does an experiment with solely this one. does need no comparison, it just collects data.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
https://www.fuzzbench.com/reports/experimental/2021-02-26-aflpp/index.html  has stopped progressing after 45 minutes runtime - many hours ago. the bug benchmark hasnt started.

once fuzzbench is fixed this can be merged which will start the same experiment again with a fixed variant.

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
> https://www.fuzzbench.com/reports/experimental/2021-02-26-aflpp/index.html has stopped progressing after 45 minutes runtime - many hours ago. the bug benchmark hasnt started.
> 
> once fuzzbench is fixed this can be merged which will start the same experiment again with a fixed variant.

The zone 'projects/fuzzbench/zones/us-central1-a' does not have enough resources available to fulfill the request.
looks like gce zone is running out of cores atm, hopefully should come back in some time, if not, i will see if we can just change the production zone. rare occurence.

**Comment by inferno-chromium** [comment]
> > https://www.fuzzbench.com/reports/experimental/2021-02-26-aflpp/index.html has stopped progressing after 45 minutes runtime - many hours ago. the bug benchmark hasnt started.
> > once fuzzbench is fixed this can be merged which will start the same experiment again with a fixed variant.
> 
> The zone 'projects/fuzzbench/zones/us-central1-a' does not have enough resources available to fulfill the request.
> looks like gce zone is running out of cores atm, hopefully should come back in some time, if not, i will see if we can just change the production zone. rare occurence.

2021-02-26-aflpp-bug is now being restarted in another zone [us-central1-f]. when this one merges, it will start in us-central1-f as well. leaving 2021-02-26-aflpp to recover in us-central1-a. if you need it, then just propose to run again if you cannot wait.

**Comment by vanhauser-thc** [comment]
@inferno-chromium no, please cancel the 02-26-* ones. one fuzzer was not working, just the 02-28-* are fine :)

**Comment by inferno-chromium** [comment]
> @inferno-chromium no, please cancel the 02-26-* ones. one fuzzer was not working, just the 02-28-* are fine :)

ok sg.

**Comment by vanhauser-thc** [comment]
@inferno-chromium looks broken again:
https://www.fuzzbench.com/reports/experimental/2021-02-27-aflpp/index.html
it is stuck at 30 minutes for 8 hours now. the bug one is also stuck at 2h.

**Comment by inferno-chromium** [comment]
> @inferno-chromium looks broken again:
> https://www.fuzzbench.com/reports/experimental/2021-02-27-aflpp/index.html
> it is stuck at 30 minutes for 8 hours now. the bug one is also stuck at 2h.

Still struggling to work around this. There is a weird ZONE_RESOURCE_POOL_EXHAUSTED errors across multiple zones us-central1-a, us-central1-f, etc. I will retry today with 2021-02-29-aflpp*.

**Pull request merged**
