### PR TITLE
Use POSTGRES_PASSWORD

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-2 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-2 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-2 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-2 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-2 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-2 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
Experiment requests from PRs now working. Only downside is you need to modify gcbrun_experiment.py to trigger it. Maybe I'll change this to be experiment-requests.yaml or some dummy file.

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz --experiment-name gh-experiment-2 --fuzzers afl -a

**Comment by jonathanmetzman** [comment]
TBR

**Comment by Alan32Liu** [comment]
> Experiment requests from PRs now working. Only downside is you need to modify gcbrun_experiment.py to trigger it. Maybe I'll change this to be experiment-requests.yaml or some dummy file.

Do we always need to change a file before requesting experiments?
If so, could we require people to change fuzzers/benchmarks?

**Comment by Alan32Liu** [comment]
Also a trivial optimization:
Would it make sense to make `/opt/fuzzbench/service/experiment-config.yaml` the default for `--experiment-config` in PR-request experiments?

**Comment by jonathanmetzman** [comment]
> Also a trivial optimization: Would it make sense to make `/opt/fuzzbench/service/experiment-config.yaml` the default for `--experiment-config` in PR-request experiments?

Yeah really we should probably be calling some custom script

**Pull request merged**
