### PR TITLE
first time: libaflfuzzer

### PR DESCRIPTION
**Pull request by vanhauser-thc**
This introduces a new core fuzzer: libaflfuzzer
it is based on libafl, the new and very WIP library that will replace afl++ at some point in the future.
This is a libfuzzer like implementation of a fuzzer based on libafl.
It is missing a lot of features (no dictionaries, no cmplog, no advanced havoc), but should already generate good results.

also: updated core fuzzer configs and new variants to further explore havoc and schedule defaults.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
The presumbit error is weird:
```
E           Actual call: generate_report(['test-experiment'], '/work/reports', coverage_report=False, fuzzers=['afl', 'afl_qemu', 'aflfast', 'aflplusplus', 'aflplusplus_optimal', 'aflplusplus_qemu', 'aflsmart', 'eclipser', 'entropic', 'fairfuzz', 'fuzzer-a', 'fuzzer-b', 'honggfuzz', 'honggfuzz_qemu', 'lafintel', 'libaflfuzzer', 'libfuzzer', 'manul', 'mopt', 'weizz_qemu'], in_progress=False, merge_with_clobber_nonprivate=False, report_name='test-experiment')

/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/unittest/mock.py:878: AssertionError
```
could it be that adding libaflfuzzer as a core fuzzer triggered this bug somehow?

**Comment by vanhauser-thc** [comment]
aflplusplus_optimal fail both because of:
```
build (aflplusplus_optimal, oss-fuzz)/8_Build Benchmarks.txt:2020-09-18T12:15:38.5136760Z #5 131.7 gpg: keyserver timed out
build (aflplusplus_optimal, standard)/8_Build Benchmarks.txt:2020-09-18T12:15:57.8878955Z #5 130.9 gpg: keyserver timed out
```
as only the commit id was changed to the same one as in aflplusplus this builds perfectly fine otherwise.

**Comment by inferno-chromium** [comment]
> The presumbit error is weird:
> 
> ```
> E           Actual call: generate_report(['test-experiment'], '/work/reports', coverage_report=False, fuzzers=['afl', 'afl_qemu', 'aflfast', 'aflplusplus', 'aflplusplus_optimal', 'aflplusplus_qemu', 'aflsmart', 'eclipser', 'entropic', 'fairfuzz', 'fuzzer-a', 'fuzzer-b', 'honggfuzz', 'honggfuzz_qemu', 'lafintel', 'libaflfuzzer', 'libfuzzer', 'manul', 'mopt', 'weizz_qemu'], in_progress=False, merge_with_clobber_nonprivate=False, report_name='test-experiment')
> 
> /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/unittest/mock.py:878: AssertionError
> ```
> 
> could it be that adding libaflfuzzer as a core fuzzer triggered this bug somehow?

Yes this is a legit test failure, if you add a fuzzer in core-fuzzers.yaml, then you need to modify test in test_reporter.py to add that to list, should be a simple word-addition. I will merge once you do this. It is easy to verify with "make presubmit"

**Comment by vanhauser-thc** [comment]
@inferno-chromium ah ok, added it. :)

I would use presubmit if it would work for me, but it fails on several things (starting with python module issues, then that I use subversion instead of git, etc. )

**Comment by vanhauser-thc** [comment]
I dont get it, I added it to the list in experiment/test_reporter.py and looked over every file if the fuzzers are hard coded somewhere else too ... nothing ... still it fails. what did I forget? I have never added a core fuzzer ...

**Comment by vanhauser-thc** [comment]
yay alphabetical ordering did the trick :)

**Review by jonathanmetzman — APPROVED** [review]

**Pull request merged**
