### PR TITLE
Sancov based ctx/ngram LibAFL fuzzers

### PR DESCRIPTION
**Pull request by tokatoka**
Hello, fuzzbench team.

We implemented ctx and ngram coverage based on sanitizer coverage.
(`libafl_ctx_large_map`, `libafl_ctx_mid_map`, `libafl_ctx_small_map`, `libafl_ngram_large_map`, `libafl_ngram_mid_map`, `libafl_ngram_small_map`)
The previous implementation was based on AFL's llvm pass which has negative impact on performance.

Therefore we want to compare how this new implementation compares to the baseline.
Both ctx, ngram has 3 variants depending on the map size we use.

### CODE REVIEW

**Comment by tokatoka** [comment]
This one is ready

Ths command is
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-02-23-libafl --fuzzers libafl_ctx_large_map libafl_ctx_mid_map libafl_ctx_small_map libafl_ngram_large_map libafl_ngram_mid_map libafl_ngram_small_map
```

@DonggeLiu 
Could you run this experiment? :)

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-02-26-libafl --fuzzers libafl_ctx_large_map libafl_ctx_mid_map libafl_ctx_small_map libafl_ngram_large_map libafl_ngram_mid_map libafl_ngram_small_map

**Comment by DonggeLiu** [comment]
Ops, could you please add [a dummy change](https://github.com/google/fuzzbench/pull/1929/files#diff-e870d8214beac56eaaeda2edc69de842f8382c428329dd8cf826a9cfa5edf7e9R19) to enable PR experiments?
Thanks :)

**Comment by tokatoka** [comment]
hi i made the change also i added the more recent libafl to compare as the baseline

the command would be
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-02-23-libafl --fuzzers libafl_ctx_large_map libafl_ctx_mid_map libafl_ctx_small_map libafl_ngram_large_map libafl_ngram_mid_map libafl_ngram_small_map libafl_280224
```

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-02-29-libafl --fuzzers libafl_ctx_large_map libafl_ctx_mid_map libafl_ctx_small_map libafl_ngram_large_map libafl_ngram_mid_map libafl_ngram_small_map libafl_280224

**Comment by tokatoka** [comment]
Hello @DonggeLiu 
Could you run another run?

In this change, we
```
- make LibAFL fuzzers base on the same commit as #1840 so we can make a fair comparison (sorry previous run was based on the latest LibAFL, it is my fault :man_facepalming: 
- add value-profile (named as libafl_fuzzbench_vp_alter) and ngram-8 fuzzers, both are sancov based new implementation
```

The command is 
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-03-06-libafl --fuzzers libafl_fuzzbench_ngram4 libafl_fuzzbench_ngram8 libafl_fuzzbench_ctx libafl_fuzzbench_vp_alter
```

**Comment by DonggeLiu** [comment]
Thanks @tokatoka, unfortunately we are making some change to FuzzBench at this moment and may need a few days before it is ready for experiments :)

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-03-11-libafl --fuzzers libafl_fuzzbench_ngram4 libafl_fuzzbench_ngram8 libafl_fuzzbench_ctx libafl_fuzzbench_vp_alter

**Comment by tokatoka** [comment]
this is done. thank you! 👍

**Comment by DonggeLiu** [comment]
Sure, could you please fix the presubmit failure? Thanks!

**Comment by tokatoka** [comment]
done!

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-04-22-libafl --fuzzers libafl_fuzzbench_fast libafl_fuzzbench_fast_ngram4 libafl_fuzzbench_fast_value_profile libafl_fuzzbench_ngram libafl_fuzzbench_value_profile

**Comment by DonggeLiu** [comment]
The experiment failed to launch because of invalid fuzzer name.
Maybe `libafl_fuzzbench_ngram` should be `libafl_fuzzbench_ngram4` or `libafl_fuzzbench_ngram8`?

**Comment by tokatoka** [comment]
I'm sorry 😔 
It is `libafl_fuzzbench_ngram8`

so 
`/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-04-22-libafl --fuzzers libafl_fuzzbench_fast libafl_fuzzbench_fast_ngram4 libafl_fuzzbench_fast_value_profile libafl_fuzzbench_ngram8 libafl_fuzzbench_value_profile`

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-04-23-libafl --fuzzers libafl_fuzzbench_fast libafl_fuzzbench_fast_ngram4 libafl_fuzzbench_fast_value_profile libafl_fuzzbench_ngram8 libafl_fuzzbench_value_profile

**Comment by tokatoka** [comment]
Hi. I adjusted the map size because previously it was using a map that was too large.

Can you run it again along with an additional fuzzer of libafl_fuzzbench_ngram4 ?
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-04-4-libafl --fuzzers libafl_fuzzbench_fast_ngram4 libafl_fuzzbench_ngram4
```

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-04-24-libafl --fuzzers libafl_fuzzbench_fast_ngram4 libafl_fuzzbench_ngram4

**Comment by tokatoka** [comment]
Hi @DonggeLiu , I waited for a few days, for the `2024-04-24-libafl` experiment but the results do not look complete.
I downloaded the csv from here https://www.fuzzbench.com/reports/experimental/2024-04-24-libafl/data.csv.gz.
However, the result does not contain the result for 24 hours. and most experiments ends in 17.5 hours. I suspect it is because of out of resource since there was another different experiment conducted on the same day.

Could you run this again for me? thanks

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-05-03-libafl --fuzzers libafl_fuzzbench_fast_ngram4 libafl_fuzzbench_ngram4

**Comment by tokatoka** [comment]
> While waiting for the new experiment to complete, did you have a chance to look into the run log of your experiment?
Sometimes, the fuzzer's run log may have clues, too.

For the LibAFL log, we do not log anything, so I can only guess by the last corpus update time.

These days I almost always see an weird restart (or you could say vm preemption) with the results.
That is,
1. First the experiments starts.
2. Then after 10 ~ 12 hours, suddenly most instances stop, and then the result page will also revert back. 
3. After that the instances start again, this time they will run for 23 hours. 

For me, I'm fine as long as they give the complete result in 3.
However 3. didn't happen this time, as long as i can tell from the result, they didn't finish its 23-hours run.
When I quickly look through these results. https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-04-24-libafl/experiment-folders/
then the instances with bigger trial id (these are the restarted instances in the above 3.) somehow all stopped fuzzing around on 24th April 1PM to 2PM.
So I would assume something has happend during that period.

**Comment by tokatoka** [comment]
And on the other hand,
https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-04-24-full-muttfuzz

Oddly here, the last corpus time is at latest around 26th April's morning. So in theory, there should be no "out of resource" at the time of 26th April's afternoon. Because at this time, this experiment is already finished

**Comment by DonggeLiu** [comment]
> However 3. didn't happen this time, as long as i can tell from the result, they didn't finish its 23-hours run. When I quickly look through these results. https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-04-24-libafl/experiment-folders/ then the instances with bigger trial id (these are the restarted instances in the above 3.) somehow all stopped fuzzing around on 26th April 1PM to 2PM. So I would assume something has happend during that period.

Yes, this is indeed strange why no trial instances are running:
1. There is no trial instance of `2024-04-24-libafl`, but the main dispatcher VM still exists:
```
NAME                         STATUS      CREATION_TIMESTAMP   PREEMPTIBLE  ZONE
d-2024-04-24-libafl          RUNNING     2024-04-25T00:03:46  FALSE        us-central1-c
```

2. The report shows the experiment has not finished: https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2024-04-24-libafl/index.html

3. The gcloud log shows it has not finished either:
image

**Comment by DonggeLiu** [comment]
BTW, this code ensures trial instances will eventually complete within 2 days:
https://github.com/google/fuzzbench/blob/162ca0c277054e479128151ff8b0cdb87727bfac/experiment/scheduler.py#L301-L312

If a trial was preempted after 1 day, then a non-preemptible instance will be used.
Not sure why they did not produce result in the last exp, though.

**Comment by tokatoka** [comment]
It's complete thank you 👍

**Pull request closed without merging**
