### PR TITLE
afl++ release test

### PR DESCRIPTION
**Pull request by vanhauser-thc**
new benchmark to check for regressions for a new release

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
the bug benchmark is failing, but not only for afl++ but also classic afl. I can look into that next week, for this run it is not important though

**Comment by vanhauser-thc** [comment]
it would be great if we can get this merges as soon as possible so we can release a new version. thank you!

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
@Vaush - some ci tests for newly added bug benchmarks now always fail, e.g. https://github.com/google/fuzzbench/pull/1155/checks?check_run_id=2654928713 , https://github.com/google/fuzzbench/pull/1155/checks?check_run_id=2654929008
can you please fix those or remove them.

**Comment by inferno-chromium** [comment]
> it would be great if we can get this merges as soon as possible so we can release a new version. thank you!

experiment building now.

**Comment by vanhauser-thc** [comment]
> @Vaush - some ci tests for newly added bug benchmarks now always fail, e.g. https://github.com/google/fuzzbench/pull/1155/checks?check_run_id=2654928713 , https://github.com/google/fuzzbench/pull/1155/checks?check_run_id=2654929008
> can you please fix those or remove them.

I think this only affects afl based ones so afl, afl++, afl-rb(?). pretty sure this is not so hard to fix. But I am giving a training all week, can have a look or help out next week.

**Comment by vanhauser-thc** [comment]
@inferno-chromium thank you!

**Comment by inferno-chromium** [comment]
> > @Vaush - some ci tests for newly added bug benchmarks now always fail, e.g. https://github.com/google/fuzzbench/pull/1155/checks?check_run_id=2654928713 , https://github.com/google/fuzzbench/pull/1155/checks?check_run_id=2654929008
> > can you please fix those or remove them.
> 
> I think this only affects afl based ones so afl, afl++, afl-rb(?). pretty sure this is not so hard to fix. But I am giving a training all week, can have a look or help out next week.

next week sounds good, thanks for your help in taking a look.

**Comment by vanhauser-thc** [comment]
@inferno-chromium hmm experiment is not showing up
I see some activity in the bucket though:
```
gs://fuzzbench-data/2021-05-21-aflpp/
gs://fuzzbench-data/2021-05-21-cloning/
gs://fuzzbench-data/2021-05-22-symccafl/
```
"cloning" is Andrea's run which was merged at least a day before me and there is no experiment data in his either.

**Comment by inferno-chromium** [comment]
@jonathanmetzman - can you take a look

**Comment by inferno-chromium** [comment]
> gs://fuzzbench-data/2021-05-21-aflpp/

Something stupid broke in gcloud api interface, (with some new version change), looking
```
I 2021-05-26T03:10:53.264031913Z startup-script: TypeError: with_scopes_if_required() got an unexpected keyword argument 'default_scopes' 
I 2021-05-26T03:10:53.264017479Z startup-script:     credentials = google.auth.credentials.with_scopes_if_required( 
I 2021-05-26T03:10:53.263998890Z startup-script:   File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 235, in _create_composite_credentials 
I 2021-05-26T03:10:53.263983973Z startup-script:     composite_credentials = _create_composite_credentials( 
I 2021-05-26T03:10:53.263960093Z startup-script:   File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 304, in create_channel 
I 2021-05-26T03:10:53.263920063Z startup-script:     return google.api_core.grpc_helpers.create_channel( 
I 2021-05-26T03:10:53.263892380Z startup-script:   File "/usr/local/lib/python3.8/site-packages/google/cloud/errorreporting_v1beta1/gapic/transports/report_errors_service_grpc_transport.py", line 105, in create_channel 
I 2021-05-26T03:10:53.263877007Z startup-script:     channel = self.create_channel( 
I 2021-05-26T03:10:53.263849614Z startup-script:   File "/usr/local/lib/python3.8/site-packages/google/cloud/errorreporting_v1beta1/gapic/transports/report_errors_service_grpc_transport.py", line 64, in __init__ 
I 2021-05-26T03:10:53.263828542Z startup-script:     self.transport = report_errors_service_grpc_transport.ReportErrorsServiceGrpcTransport( 
I 2021-05-26T03:10:53.263812102Z startup-script:   File "/usr/local/lib/python3.8/site-packages/google/cloud/errorreporting_v1beta1/gapic/report_errors_service_client.py", line 178, in __init__ 
I 2021-05-26T03:10:53.263794038Z startup-script:     gapic_api = report_errors_service_client.ReportErrorsServiceClient( 
I 2021-05-26T03:10:53.263775859Z startup-script:   File "/usr/local/lib/python3.8/site-packages/google/cloud/error_reporting/_gapic.py", line 31, in make_report_error_api 
I 2021-05-26T03:10:53.263757776Z startup-script:     self._report_errors_api = make_report_error_api(self) 
I 2021-05-26T03:10:53.263738643Z startup-script:   File "/usr/local/lib/python3.8/site-packages/google/cloud/error_reporting/client.py", line 202, in report_errors_api 
I 2021-05-26T03:10:53.263723780Z startup-script:     self.report_errors_api.report_error_event(error_report) 
I 2021-05-26T03:10:53.263704089Z startup-script:   File "/usr/local/lib/python3.8/site-packages/google/cloud/error_reporting/client.py", line 317, in _send_error_report 
I 2021-05-26T03:10:53.263688837Z startup-script:     self._send_error_report( 
I 2021-05-26T03:10:53.263667081Z startup-script:   File "/usr/local/lib/python3.8/site-packages/google/cloud/error_reporting/client.py", line 357, in report 
I 2021-05-26T03:10:53.263652585Z startup-script:     _error_reporting_client.report(message) 
I 2021-05-26T03:10:53.263637300Z startup-script:   File "/src/common/logs.py", line 188, in _report_error_with_retries 
I 2021-05-26T03:10:53.263621806Z startup-script:     result = func(*args, **kwargs) 
I 2021-05-26T03:10:53.263603873Z startup-script:   File "/src/common/retry.py", line 81, in _wrapper 
I 2021-05-26T03:10:53.263580758Z startup-script: Traceback (most recent call last): 
```

**Comment by inferno-chromium** [comment]
trying again in https://github.com/google/fuzzbench/commit/d2234a0cfa532058f1a57328dbefab3d24ee5894 to see if experiments work.

**Comment by inferno-chromium** [comment]
> @inferno-chromium hmm experiment is not showing up
> I see some activity in the bucket though:
> 
> ```
> gs://fuzzbench-data/2021-05-21-aflpp/
> gs://fuzzbench-data/2021-05-21-cloning/
> gs://fuzzbench-data/2021-05-22-symccafl/
> ```
> 
> "cloning" is Andrea's run which was merged at least a day before me and there is no experiment data in his either.

fix seems to work, e.g. https://www.fuzzbench.com/reports/experimental/2021-05-25-aflpp/index.html
other 2 experiments should start showing up as well (i restarted them with 2021-05-25-*

**Pull request merged**
