### PR TITLE
LibAFL text mode + autotokens experiment

### PR DESCRIPTION
**Pull request by andreafioraldi**
Big changes in LibAFL that are worth an experiment

### CODE REVIEW

**Comment by andreafioraldi** [comment]
I also removed my past afl variant

**Comment by inferno-chromium** [comment]
@jonathanmetzman is doing some experiments for a last-minute paper submission, this might need to wait a day or two.

**Comment by andreafioraldi** [comment]
> @jonathanmetzman is doing some experiments for a last-minute paper submission, this might need to wait a day or two.

sure, np

**Comment by jonathanmetzman** [comment]
> > @jonathanmetzman is doing some experiments for a last-minute paper submission, this might need to wait a day or two.
> 
> sure, np

May even be up to a week sorry.

**Comment by andreafioraldi** [comment]
> > > @jonathanmetzman is doing some experiments for a last-minute paper submission, this might need to wait a day or two.
> > 
> > 
> > sure, np
> 
> May even be up to a week sorry.

What's the state? Can you enable the CI so that I can see if there is something else to fix tomorrow?

**Comment by jonathanmetzman** [comment]
Gonna merge this if it passes today.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by andreafioraldi** [comment]
> Gonna merge this if it passes today.

(libafl, bug) fails on aspell with the same error of (afl, bug), an ubsan violation during configure. Dunno if it is a problem of the benchmark, btw I requested a coverage exp so in theory no problems.

**Pull request merged**
