### PR TITLE
Redo experiments

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @jdhiser @dliyanage @worksbutnottested @vanhauser-thc @andreafioraldi

**Comment by jonathanmetzman** [comment]
TBR

**Review by oliverchang — COMMENTED** [review]
LGTM

**Comment by jdhiser** [comment]
> CC @jdhiser @dliyanage @WorksButNotTested @vanhauser-thc @andreafioraldi

Thanks, @jonathanmetzman !

**Pull request merged**
