### PR TITLE
Initial contribution from SVRWB benchmark

### PR DESCRIPTION
**Pull request by roachspray**
- This pull request is related to issue #50  and includes:
   - `audiofile 0.3.6` and specifically libaudiofile. The harness is based on `sfconvert"`which is a utility that is a part of this project. 
   - `jasper 1.701.0` and libjasper. The harness is based on jasper.c which is a utility in that project.
  - `tcpdump 4.9.0`
- I was unable to test in the FuzzBench environment, but able to test by hand ... It needs FuzzBench testing. All feedback is good feedback. :)
- I include bugs in `known_bugs` directory. For audiofile, are 4 CVEs that do not want to crash under this setup, but do with the original sfconvert utility. Similarly, there were a handful of CVEs that were not wanting to crash for jasper (or only in 32 or 64 bit mode). All of the samples not included may be found in the original svrwb benchmark for reference (https://github.com/veracode-research/svrwb-fuzz-benchmark-suite/)
- I do not include any seed files, but a seed should be a WAV file. I have one I used, but it was selected w/o any rhyme or reason other than it was the correct type and AFL liked it's size.
- There are another bunch of crashes for `sfinfo` tool, but I believe it should be a different fuzz target rather than build a harness to handle both sfconvert and sfinfo.
- This work is done with the support of the Veracode Applied Research Group.

When this is OK'd (after whatever iterations), I will work on others. Some others will require common.sh changes -- e.g., using wget(1) to pull a .tgz from a URL and unpack it.

### CODE REVIEW

**Comment by roachspray** [comment]
@googlebot I signed it!

**Comment by roachspray** [comment]
Ok, this is failing on wanting libtool, but I see libtool listed in the `base-builder` Dockerfile. Anyone with any tips?

**Comment by jonathanmetzman** [comment]
> Ok, this is failing on wanting libtool, but I see libtool listed in the `base-builder` Dockerfile. Anyone with any tips?

I don't have any off the top of my head. I can try hacking around on the PR to see what works when I get back into the office.

**Comment by jonathanmetzman** [comment]
Note to self: I need to change the env var `$FUZZ_TARGET` so that it isn't always set to `fuzz-target` and instead is based on what the fuzz target is actually named.

**Comment by lszekeres** [comment]
Thanks so much for the PR!

> * I include bugs in `known_bugs` directory. For audiofile, are 4 CVEs that do not want to crash under this setup, but do with the original sfconvert utility. Similarly, there were a handful of CVEs that were not wanting to crash for jasper (or only in 32 or 64 bit mode). All of the samples not included may be found in the original svrwb benchmark for reference (https://github.com/veracode-research/svrwb-fuzz-benchmark-suite/)

Just wondering if you have any hypothesis on why some of the original reproducers aren't crashing under the new setup? Also, do you happen to have a test script for checking if the inputs crash?

**Comment by roachspray** [comment]
> Thanks so much for the PR!
> 
> > * I include bugs in `known_bugs` directory. For audiofile, are 4 CVEs that do not want to crash under this setup, but do with the original sfconvert utility. Similarly, there were a handful of CVEs that were not wanting to crash for jasper (or only in 32 or 64 bit mode). All of the samples not included may be found in the original svrwb benchmark for reference (https://github.com/veracode-research/svrwb-fuzz-benchmark-suite/)
> 
> Just wondering if you have any hypothesis on why some of the original reproducers aren't crashing under the new setup? Also, do you happen to have a test script for checking if the inputs crash?

I am unsure at this point, but I am going to to investigate hopefully tonight, but likely tomorrow. I am fine with holding off on this merge until that is sussed out, if that is a more appealing route to take.

Somewhat tangential: I figure I would not include any additional metadata related to stack traces with this and wait until how things may be structured with the bugs found experiment(s) work. I

Regarding the test script: I do not have such as script, but I can make one. For both of these targets in this pull request, I have a _HAS_MAIN ifdef to enable running one-offs for such testing, so I can create something. Is there a good location for that script to live? If I generate the _HAS_MAIN version of the harness, where is a good location for that?  If you have an example to look at that sorta has what would be wanted, I would appreciate it.

**Comment by inferno-chromium** [comment]
Please fix the build failures

```
You must have libtool installed to compile libaudiofile.
Get ftp://ftp.gnu.org/gnu/libtool/libtool-1.4.2.tar.gz
(or a newer version if it is available).
```

**Comment by lszekeres** [comment]
> I am unsure at this point, but I am going to to investigate hopefully tonight, but likely tomorrow. I am fine with holding off on this merge until that is sussed out, if that is a more appealing route to take.

Thanks a lot!

> Somewhat tangential: I figure I would not include any additional metadata related to stack traces with this and wait until how things may be structured with the bugs found experiment(s) work.

Yes, that makes sense. As long as the bugs are reproducible, we can figure this out as we go.

> Regarding the test script: I do not have such as script, but I can make one. For both of these targets in this pull request, I have a _HAS_MAIN ifdef to enable running one-offs for such testing, so I can create something. Is there a good location for that script to live? If I generate the _HAS_MAIN version of the harness, where is a good location for that? If you have an example to look at that sorta has what would be wanted, I would appreciate it.

The reason I asked is that it'd be nice to check during CI that crashes remain reproducible with changes. We don't have an example for this yet, as this is our first "bug benchmark" :) I imagine we could have a test_known_bugs.sh next to build.sh, which could for each known_bugs/* check if the input still crashes (using asan, gdb, or simply by checking if $? is 139). Then we could call test_know_bugs.sh from build.sh (perhaps depending on an env var) and thus verify reproducibility for builds. We can add this later too, but if you have a anything towards this, that'd be great!

(Using the current _HAS_MAIN would be great for this, and later we can generalize and provide a common main() for testing purposes used across benchmarks)

**Comment by roachspray** [comment]
> Please fix the build failures
> 
> ```
> You must have libtool installed to compile libaudiofile.
> Get ftp://ftp.gnu.org/gnu/libtool/libtool-1.4.2.tar.gz
> (or a newer version if it is available).
> ```

What is the proper way to add this? Try to install relative to SRC/ or another directory and point to it in this build? Or add to dependencies in Docker?

**Comment by jonathanmetzman** [comment]
>What is the proper way to add this? Try to install relative to SRC/ or another directory and point to it in this build? Or add to dependencies in Docker?

Whatever works to build it in builder.Dockerfile is good for me. I find it so odd given that libtool is installed (maybe this is a bad way of saying the version is wrong). I'm a bit short on time because I've been in and out of the office lately but if I get a chance I will try to debug this.

**Comment by roachspray** [comment]
> > What is the proper way to add this? Try to install relative to SRC/ or another directory and point to it in this build? Or add to dependencies in Docker?
> 
> Whatever works to build it in builder.Dockerfile is good for me. I find it so odd given that libtool is installed (maybe this is a bad way of saying the version is wrong). I'm a bit short on time because I've been in and out of the office lately but if I get a chance I will try to debug this.

Agreed re: libtool there already and maybe is version related.

I am a bit concerned about doing it in docker as I do not wish to impact the other builds. Would it be unacceptable for me to try off of the BUILD/ dir in which the benchmark is built given the libtool is in docker now and it's just this one benchmark that wants a specific version?

**Comment by jonathanmetzman** [comment]
> > > What is the proper way to add this? Try to install relative to SRC/ or another directory and point to it in this build? Or add to dependencies in Docker?
> > 
> > 
> > Whatever works to build it in builder.Dockerfile is good for me. I find it so odd given that libtool is installed (maybe this is a bad way of saying the version is wrong). I'm a bit short on time because I've been in and out of the office lately but if I get a chance I will try to debug this.
> 
> Agreed re: libtool there already and maybe is version related.
> 
> I am a bit concerned about doing it in docker as I do not wish to impact the other builds. Would it be unacceptable for me to try off of the BUILD/ dir in which the benchmark is built given the libtool is in docker now and it's just this one benchmark that wants a specific version?

It's a totally acceptable solution.

Sorry my previous comment about builder.Dockerfile was confused.

**Comment by roachspray** [comment]
> > > > What is the proper way to add this? Try to install relative to SRC/ or another directory and point to it in this build? Or add to dependencies in Docker?
> > > 
> > > 
> > > Whatever works to build it in builder.Dockerfile is good for me. I find it so odd given that libtool is installed (maybe this is a bad way of saying the version is wrong). I'm a bit short on time because I've been in and out of the office lately but if I get a chance I will try to debug this.
> > 
> > 
> > Agreed re: libtool there already and maybe is version related.
> > I am a bit concerned about doing it in docker as I do not wish to impact the other builds. Would it be unacceptable for me to try off of the BUILD/ dir in which the benchmark is built given the libtool is in docker now and it's just this one benchmark that wants a specific version?
> 
> It's a totally acceptable solution.
> 
> Sorry my previous comment about builder.Dockerfile was confused.

No worries; I figured as much, but just pressed to make sure. Thanks and sorry to be slow.

**Comment by roachspray** [comment]
> Thanks so much for the PR!
> 
> > * I include bugs in `known_bugs` directory. For audiofile, are 4 CVEs that do not want to crash under this setup, but do with the original sfconvert utility. Similarly, there were a handful of CVEs that were not wanting to crash for jasper (or only in 32 or 64 bit mode). All of the samples not included may be found in the original svrwb benchmark for reference (https://github.com/veracode-research/svrwb-fuzz-benchmark-suite/)
> 
> Just wondering if you have any hypothesis on why some of the original reproducers aren't crashing under the new setup? Also, do you happen to have a test script for checking if the inputs crash?

Follow-up: Yes, during my porting I had not compiled in ASan, which is relied upon for a number of the crashes.

Do you or @jonathanmetzman  know whether we include -fsanitize=address by default in CFLAGS or CXXFLAGS that get passed around in the build environment? Looking at source, I am not 100% sure.

For the test script, I can write it, but am unsure what context to run it under -- tips appreciated. If just writing it is enough, for now, I'll get that done.

I will also go back over to see what few that were in audiofile and jasper that should be included from my repo.

Further, I have a harness for tcpdump-4.9.0 which has a ton of known issues (thanks to ian beer) and would like to include that with this merge (and any tests) ... I will add to this PR.  

Another question: how to handle seeds? Should each benchmark include them? Maybe this discussion belongs on a issue.

I apologize to abuse PR to get CI testing done... if there is a way to do some of the build of benchmarks done locally, I would do that. My goal is to figure out why audiofile autogen.sh is being a pain, tcpdump 4.9.0 in, and any test script(s) for the known bugs.

**Comment by jonathanmetzman** [comment]
> > Thanks so much for the PR!
> > > * I include bugs in `known_bugs` directory. For audiofile, are 4 CVEs that do not want to crash under this setup, but do with the original sfconvert utility. Similarly, there were a handful of CVEs that were not wanting to crash for jasper (or only in 32 or 64 bit mode). All of the samples not included may be found in the original svrwb benchmark for reference (https://github.com/veracode-research/svrwb-fuzz-benchmark-suite/)
> > 
> > 
> > Just wondering if you have any hypothesis on why some of the original reproducers aren't crashing under the new setup? Also, do you happen to have a test script for checking if the inputs crash?
> 
> Follow-up: Yes, during my porting I had not compiled in ASan, which is relied upon for a number of the crashes.
> 
> Do you or @jonathanmetzman know whether we include -fsanitize=address by default in CFLAGS or CXXFLAGS that get passed around in the build environment? Looking at source, I am not 100% sure.

We used to include ASAN in C(XX)FLAGS. We don't anymore.
We stopped because it didn't seem to make sense when we were only measuring coverage.
We will probably reenable ASAN once we have infra for measuring bug finding in place.

> 
> For the test script, I can write it, but am unsure what context to run it under -- tips appreciated. If just writing it is enough, for now, I'll get that done.

@lszekeres might need to answer this one since I'm not sure what he wanted from the script.

> 
> I will also go back over to see what few that were in audiofile and jasper that should be included from my repo.
> 
> Further, I have a harness for tcpdump-4.9.0 which has a ton of known issues (thanks to ian beer) and would like to include that with this merge (and any tests) ... I will add to this PR.

Sounds good. I slightly prefer a new PR, but if it's easier for you to add it in the same PR, then that is fine.

> 
> Another question: how to handle seeds? Should each benchmark include them? Maybe this discussion belongs on a issue.

I think it's a good idea to include seeds. I think you simply need to make a `seeds/` directory in `$OUT` to do this.
Seeds will obviously affect benchmarking, but for now our approach is to include them. We will try later experiment-wide configs to disable seeds and see how it affects things.

> 
> I apologize to abuse PR to get CI testing done... if there is a way to do some of the build of benchmarks done locally, I would do that. My goal is to figure out why audiofile autogen.sh is being a pain, tcpdump 4.9.0 in, and any test script(s) for the known bugs.

I'm 100% OK with you using CI for this purpose. But are you able to do `make build-$FUZZER-$BENCHMARK`?

**Comment by roachspray** [comment]
> I'm 100% OK with you using CI for this purpose. But are you able to do `make build-$FUZZER-$BENCHMARK`?

Ah, I have not tried this ... I will need to look closer as to how to do this.

**Comment by lszekeres** [comment]
> We will probably reenable ASAN once we have infra for measuring bug finding in place.
> 
> > For the test script, I can write it, but am unsure what context to run it under -- tips appreciated. If just writing it is enough, for now, I'll get that done.

Thanks! Just adding the script would be perfect, and we can figure out how to run it during CI later (to verify the reproducibility of the bugs). We might add a special context for this where we compile with ASAN and FUZZER_LIB is a common main() function that takes an input file and runs LLVMFuzzerTestOneInput().

**Comment by roachspray** [comment]
> I'm 100% OK with you using CI for this purpose. But are you able to do `make build-$FUZZER-$BENCHMARK`?

Ah, I had not seen the updated (I think?) documentation!  Apologies for not checking back to the docs page.

**Comment by roachspray** [comment]
Closing this:
- With the build-/run- make targets I can test locally.
- `audiofile` is broken in this environment and while Ive battled this specific setup before, I am not sure what my path to fixing was... so need to pull this back.
- `tcpdump` builds and I can run it locally, but with the libAFL.a setup it crashes and I need to debug.
- `jasper` works ok.

**Comment by jonathanmetzman** [comment]
I think I may have misunderstood the purpose of this PR, because I was expecting to merge it rather than closing. Are you plan on landing those benchmarks in a separate PR?

**Comment by roachspray** [comment]
> I think I may have misunderstood the purpose of this PR, because I was expecting to merge it rather than closing. Are you plan on landing those benchmarks in a separate PR?

Yes, I am working on a new PR that will not include `audiofile` -- there is an issue in building it that I do not have an exact solution for (it's something I've dealt with before but I'm not recalling the fix). That benchmark will be replaced with another. If you want me to do it all in this PR, that is fine ... just figured I would declutter the commit trail.

**Comment by jonathanmetzman** [comment]
OK, I don't have a preference, whatever works best for you!

**Pull request closed without merging**
