### PR TITLE
LibAFL cmplog ctx experiment

### PR DESCRIPTION
**Pull request by tokatoka**
Hi.

We'd like to do an experiment for a new feature "ctx sensitive cmplog" on libafl to compare if it will improve.
Basically it records the context of the function calls, but hashs this context together when writing cmp values into the cmplog map.
I also chose to use llvm-16 to make the most of the LLVM Pass

The command would be
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-18-libafl --fuzzers libafl libafl_cmplog_ctx
```

### CODE REVIEW

**Comment by tokatoka** [comment]
this one is ready

**Comment by tokatoka** [comment]
@Alan32Liu 
Could you run the experiment for this too please :)

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-10-25-libafl --fuzzers libafl libafl_cmplog_ctx

**Comment by Alan32Liu** [comment]
Experiment `2023-10-25-libafl` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-10-25-libafl/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-10-25-libafl/index.html).

**Comment by tokatoka** [comment]
Thanks. @Alan32Liu 
In the end, ctx cmplog is not for all the fuzzers

In the last week's commit we adopted the cmplog ctx and changed the hash we use for writing into cmplog map.
Now in the latest commit, i removed the cmplog ctx. And I want to see if the hash change it self is a improvement.

Could you run another experiment for the fuzzer?
The command is 
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-11-03-libafl --fuzzers libafl_cmplog_ctx
```

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-11-03-libafl --fuzzers libafl_cmplog_ctx

**Comment by Alan32Liu** [comment]
Experiment `2023-11-03-libafl` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-11-03-libafl/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-11-03-libafl/index.html).

**Pull request closed without merging**
