### PR TITLE
symbolic variants

### PR DESCRIPTION
**Pull request by vanhauser-thc**
this is a fair comparison of the symbolic solvers eclipser, symcc, symqemu and fuzzolic (z3 + fuzzy), and also compare them against afl++ cmplog (normal and via qemu).
each variant has a single, simple afl++ secondary.
In cooperation with @DavidKorczynski

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
LGTM! 

Loads of interesting stuff, amongst other things I am excited to see how symcc and symqemu compares.

**Comment by vanhauser-thc** [comment]
@DavidKorczynski  you still have to write a "@googlebot I consent."

**Comment by DavidKorczynski** [comment]
@googlebot I consent.

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski you still have to write a "@googlebot I consent."

Ah I misunderstood - thanks!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by vanhauser-thc** [comment]
@jonathanmetzman  @inferno-chromium 
this can be merged now.
There will still be a few benchmarks that wont build, but that is OK to have an overview over the capabilities.
Also there are false negatives, as the killing of some fuzzing threads fail which makes the CI fail, but the fuzzing runs fine.
thank you!
super excited for these results ...

**Pull request merged**
