### PR TITLE
[New Fuzzer]: `emasfuzz`

### PR DESCRIPTION
**Pull request by Ricardo-609**
paper's experiment.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
CI tests failed due to #1754.
Re-run them now as #1754 is fixed.

**Comment by Alan32Liu** [comment]
Hi @Ricardo-609, could you please sign the CLA? You can find it in the CI tests : )
We are holding off all experiments for 1-2 weeks due to an ongoing competition, hope that would be alright with you.

**Comment by Ricardo-609** [comment]
> 

hi, @Alan32Liu . I have successfully signed cla. What should I do next?Thanks.

**Comment by Alan32Liu** [comment]
> > 
> 
> hi, @Alan32Liu . I have successfully signed cla. What should I do next?Thanks.

Thanks, @Ricardo-609!
Could you please fix the CI tests at your convenience?
This is necessary before running experiments because CI tests verify if your fuzzer can successfully build with each benchmark.
You can also [test your fuzzer locally](https://google.github.io/fuzzbench/getting-started/adding-a-new-fuzzer/#blocklisting-benchmarks) before pushing your code : )

Feel free to take your time, as the competition needs another 2 weeks.
We are more than happy to launch experiments for your fuzzer right after that.

**Pull request closed without merging**
