### PR TITLE
[AFL++] remove duplicate code and test combined mutators

### PR DESCRIPTION
**Pull request by andreafioraldi**
Hi, now an AFL++ conf can be made without code duplicates just passing parameters to build and run.
E.g. this is aflplusplus_cmplog:

```python
def build():
    """Build benchmark."""
    aflplusplus_fuzzer.build("cmplog")


def fuzz(input_corpus, output_corpus, target_binary):
    """Run fuzzer."""
    aflplusplus_fuzzer.fuzz(input_corpus,
                            output_corpus,
                            target_binary)
```

I removed all the schedules-related confs and added an experimental combination of mopt + cmplog (aflplusplus_andrea (yes, we finished the names lol)).

Today, looking also at the results last report that includes aflplusplus_cmplog, I improved a lot cmplog looking at its limitations like cmp related to loops (that are now blacklisted), decreasing probability for cmp that does not increase coverage, and much more.

Now cmplog can be used in combination with Mopt thanks to the probabilistic fuzzing of cmps.

I also removed instrim as default instrumentation, I feel that it is decremental in coverage (just a guess).

So, currently the afl++ confs in this PR are aflplusplus (plain), aflplusplus_mopt, aflplusplus_cmplog (with new optimizations), aflplusplus_andrea (mopt+cmplog).

Thanks you as always!

### CODE REVIEW

**Comment by andreafioraldi** [comment]
Seems that presubmit is failing but not in my code (?).

**Comment by jonathanmetzman** [comment]
A couple comments/questions:
1. Is this in place of #222 ?
2. Which of these fuzzers are supposed to be permanent and which are just one-offs?
3. There are some merge conflicts, can you please resolve.

**Comment by jonathanmetzman** [comment]
Also, I'm not sure I agree that the presubmit failures are "not your code". For example, it complains that `fuzzers/aflplusplus_cmplog/fuzzer.py:19:0: W0611: Unused fuzzer imported from fuzzers.afl as afl_fuzzer` because you deleted the place where that module was used. All the other complaints seem to be about unused imports. So please go back and remove those imports that this PR makes obsolete.

**Comment by andreafioraldi** [comment]
Oh yes you're right, I went directly to the end of the presubmit report and I missed the errors.

**Comment by andreafioraldi** [comment]
btw,
1. yes
2. see how aflplusplus_cmplog_mopt performs, the other 3 are permanent
3. ok

**Comment by andreafioraldi** [comment]
I added the marc configurations from #229 (that can be closed /cc @vanhauser-thc) except aflplusplus_rare and aflplusplus_mmopt that we already tested.

**Comment by jonathanmetzman** [comment]
I think this is missing some runner.Dockerfiles (e.g. freetype+aflplusplus_cmplog fails [here](https://github.com/google/fuzzbench/pull/225/checks?check_run_id=586975784) because there is no runner.Dockerfile).

**Comment by jonathanmetzman** [comment]
It seems like that's the only one missing the file since all others build.
Apologies for the state of our CI, I'm working to reduce the false positives in #221

**Comment by andreafioraldi** [comment]
Ah damn I forgot to git add it

**Comment by vanhauser-thc** [comment]
@jonathanmetzman I dont care if you accept andrea's or my PR :)
I am just very eager for the result of the new temporary ones!

**Comment by jonathanmetzman** [comment]
Just one question before I run the experiment (I'll try to do so this weekend or early next week).
I want to make sure I get this right since this is a lot of fuzzers.
I am going to run an experiment with `aflplusplus_cmplog aflplusplus_mopt_cmplog aflplusplus_ctx aflplusplus_ctx_mmopt aflplusplus_ctx_rare aflplusplus_instrim aflplusplus_instrim_mmopt aflplusplus_instrim_rare aflplusplus_ngram2 aflplusplus_ngra\
  m2_mmopt aflplusplus_ngram2_rare aflplusplus_ngram4 aflplusplus_ngram4_mmopt aflplusplus_ngram4_rare`.
And then combine that data with https://www.fuzzbench.com/reports/2020-04-14/index.html
Does this sound right or is there something I messed up here?

**Comment by vanhauser-thc** [comment]
@jonathanmetzman yes - basically all that were not in the run that is just finished. Thanks!

**Comment by jonathanmetzman** [comment]
OK just started.
For the record that other run isn't finished measuring yet (for some benchmarks). I think measuring the irssi benchmark is a big bottleneck.

**Comment by jonathanmetzman** [comment]
For the record, I needed to restart the afl++ experiment because of an unrelated bug that was fixed.

**Pull request merged**
