### PR TITLE
Fix matio benchmark, add missing zlib dependency.

### PR DESCRIPTION
**Pull request by inferno-chromium**
Also, fix the unsupported fuzzers list.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@Vaush as fyi

**Comment by inferno-chromium** [comment]
Merging to unblock CI.

**Comment by jonathanmetzman** [comment]
Very surprising to me that this mistake was made. @Vaush didn't we just copy this directly from the Dockerfile?

**Comment by inferno-chromium** [comment]
And https://github.com/google/fuzzbench/commit/9560b28e2d7c2dc1bf615eec047f34a04eda09c2 as well. i just fixed by checking OSS-Fuzz project integration.

**Comment by Vaush** [comment]
> 
> 
> Very surprising to me that this mistake was made. @Vaush didn't we just copy this directly from the Dockerfile?

Yes, the Dockerfile, as of now, hasn't been modified. It's exactly the same as the one generated by the script to integrate OSS-Fuzz benchmarks.
I am not entirely sure why the problem didn't show up with afl, libfuzzer and others, but my guess is that whoever integrated matio in OSS-Fuzz made the mistake and it was never caught because the fuzzer used on OSS-Fuzz doesn't trigger the issue?
I am don't know exactly how the integration from OSS-Fuzz to FuzzBench works internally, but I am guessing the compile command is taken from the OSS-Fuzz project, so it would at least make sense if this was the case.

**Comment by Vaush** [comment]
Just to be 100% sure, I see that the fuzzer list was fixed, and zlib included and linked to, so there is nothing I need to do on my part for this, right?

**Comment by inferno-chromium** [comment]
> > Very surprising to me that this mistake was made. @Vaush didn't we just copy this directly from the Dockerfile?
> 
> Yes, the Dockerfile, as of now, hasn't been modified. It's exactly the same as the one generated by the script to integrate OSS-Fuzz benchmarks.
> I am not entirely sure why the problem didn't show up with afl, libfuzzer and others, but my guess is that whoever integrated matio in OSS-Fuzz made the mistake and it was never caught because the fuzzer used on OSS-Fuzz doesn't trigger the issue?
> I am don't know exactly how the integration from OSS-Fuzz to FuzzBench works internally, but I am guessing the compile command is taken from the OSS-Fuzz project, so it would at least make sense if this was the case.

Just fyi, problem did show for afl, libfuzzer and honggfuzz fuzzers, CI didnt break as you added those in unsupported_fuzzers.

**Comment by Vaush** [comment]
> 
> 
> > > Very surprising to me that this mistake was made. @Vaush didn't we just copy this directly from the Dockerfile?
> > 
> > 
> > Yes, the Dockerfile, as of now, hasn't been modified. It's exactly the same as the one generated by the script to integrate OSS-Fuzz benchmarks.
> > I am not entirely sure why the problem didn't show up with afl, libfuzzer and others, but my guess is that whoever integrated matio in OSS-Fuzz made the mistake and it was never caught because the fuzzer used on OSS-Fuzz doesn't trigger the issue?
> > I am don't know exactly how the integration from OSS-Fuzz to FuzzBench works internally, but I am guessing the compile command is taken from the OSS-Fuzz project, so it would at least make sense if this was the case.
> 
> Just fyi, problem did show for afl, libfuzzer and honggfuzz fuzzers, CI didnt break as you added those in unsupported_fuzzers.

Only for their qemu version though, which shouldn't be what's used by OSS-Fuzz. Afl and libfuzzer built normally, I checked locally with those two before even sending the PR.

**Comment by inferno-chromium** [comment]
> > > > Very surprising to me that this mistake was made. @Vaush didn't we just copy this directly from the Dockerfile?
> > > 
> > > 
> > > Yes, the Dockerfile, as of now, hasn't been modified. It's exactly the same as the one generated by the script to integrate OSS-Fuzz benchmarks.
> > > I am not entirely sure why the problem didn't show up with afl, libfuzzer and others, but my guess is that whoever integrated matio in OSS-Fuzz made the mistake and it was never caught because the fuzzer used on OSS-Fuzz doesn't trigger the issue?
> > > I am don't know exactly how the integration from OSS-Fuzz to FuzzBench works internally, but I am guessing the compile command is taken from the OSS-Fuzz project, so it would at least make sense if this was the case.
> > 
> > 
> > Just fyi, problem did show for afl, libfuzzer and honggfuzz fuzzers, CI didnt break as you added those in unsupported_fuzzers.
> 
> Only for their qemu version though, which shouldn't be what's used by OSS-Fuzz. Afl and libfuzzer built normally, I checked locally with those two before even sending the PR.

it was breaking compile for me for libfuzzer, but whatever, it is fixed now. no worries, this was more of a fyi.

**Comment by Vaush** [comment]
I see, that's interesting. Thanks for fixing this, I am just trying to understand the situation completely so I don't repeat the same mistake on the next benchmarks.

**Pull request merged**
