### PR TITLE
Update honggfuzz to the newest version (b56729e6f29672be2edb2885807844df68d8db32)

### PR DESCRIPTION
**Pull request by robertswiecki**
Update honggfuzz to the newest version (b56729e6f29672be2edb2885807844df68d8db32)

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Please check the compile failure on bug benchmark openexr

```
#18 167.7 + fuzzer_basename=openexr_exrenvmap_fuzzer
#18 167.7 + /honggfuzz/hfuzz_cc/hfuzz-clang++ -fsanitize=address -fsanitize=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unreachable,vla-bound,vptr -stdlib=libc++ -O1 -std=c++11 -pthread -I /src/openexr/OpenEXR/IlmImf -I /src/openexr/OpenEXR/exrenvmap -I /src/openexr/IlmBase/Imath -I /src/openexr/IlmBase/Iex -I /src/openexr/IlmBase/Half -I /work/OpenEXR/config -I /work/IlmBase/config /src/openexr_exrenvmap_fuzzer.cc /honggfuzz/empty_lib.o /work/OpenEXR/IlmImf/libIlmImf.a /work/IlmBase/Iex/libIex.a /work/IlmBase/Half/libHalf.a /work/IlmBase/IlmThread/libIlmThread.a /work/IlmBase/Imath/libImath.a /work/OpenEXR/libOpenexrUtils.a -lz -o /out/openexr_exrenvmap_fuzzer
#18 168.5 /work/OpenEXR/libOpenexrUtils.a(Image.cpp.o):(.rodata+0x120): multiple definition of `typeinfo for ImageChannel'
#18 168.5 /work/OpenEXR/libOpenexrUtils.a(Image.cpp.o):(.rodata+0x120): first defined here
#18 168.5 /work/OpenEXR/libOpenexrUtils.a(Image.cpp.o):(.rodata+0xe0): multiple definition of `typeinfo name for ImageChannel'
#18 168.5 /work/OpenEXR/libOpenexrUtils.a(Image.cpp.o):(.rodata+0xe0): first defined here
#18 168.5 /work/OpenEXR/libOpenexrUtils.a(Image.cpp.o):(.rodata+0x20): multiple definition of `vtable for ImageChannel'
#18 168.5 /work/OpenEXR/libOpenexrUtils.a(Image.cpp.o):(.rodata+0x20): first defined here
#18 169.1 clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
#18 169.1 Traceback (most recent call last):
#18 169.1   File "<string>", line 1, in <module>
#18 169.1   File "/src/fuzzers/honggfuzz/fuzzer.py", line 31, in build
#18 169.1     utils.build_benchmark()
#18 169.1   File "/src/fuzzers/utils.py", line 76, in build_benchmark
#18 169.1     subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
#18 169.1   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#18 169.1     raise CalledProcessError(retcode, cmd)
#18 169.1 subprocess.CalledProcessError: Command '['/bin/bash', '-ex', '/src/build.sh']' returned non-zero exit status 1.
#18 ERROR: executor failed running [/bin/sh -c PYTHONPATH=$SRC python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.$FUZZER import fuzzer; fuzzer.build()"]: runc did not terminate sucessfully
```

**Comment by robertswiecki** [comment]
Thanks, I will check it.

**Comment by robertswiecki** [comment]
Seems like those two symbols are present in two distinct files inside ```/work/OpenEXR/libOpenexrUtils.a``` created by build.sh via ```ar```. I'm surprised it doesn't fail with other fuzzers. Though it doesn't fail with my local build too, so I wonder what might be the difference between honggfuzz, my local build, and other fuzzers.

In any case, I think it might be good to ask owners of this code if this is the desirable situation - creating a library with duplicated symbols. And I'll debug it a little bit more in the meantime.

If authors of this code think it's the intended way of building this fuzzer, adding the following LDFLAG (by setting CXXFLAG in build.sh) might help here

```-Wl,-z,muldefs```

but this is a temporary hack IMO.

```
$ nm build/OpenEXR/exrmultiview/CMakeFiles/exrmultiview.dir/Image.cpp.o | c++filt | grep type
0000000000000048 R typeinfo for ImageChannel
0000000000000000 V typeinfo for TypedImageChannel<half>
0000000000000000 V typeinfo for TypedImageChannel<float>
0000000000000000 V typeinfo for TypedImageChannel<unsigned int>
                 U typeinfo for Iex_2_5::ArgExc
0000000000000038 R typeinfo name for ImageChannel
0000000000000000 V typeinfo name for TypedImageChannel<half>
0000000000000000 V typeinfo name for TypedImageChannel<float>
0000000000000000 V typeinfo name for TypedImageChannel<unsigned int>
                 U vtable for __cxxabiv1::__class_type_info
                 U vtable for __cxxabiv1::__si_class_type_info
```
```
$ nm build/OpenEXR/exrmaketiled/CMakeFiles/exrmaketiled.dir/Image.cpp.o | c++filt | grep type
0000000000000040 R typeinfo for ImageChannel
0000000000000000 V typeinfo for TypedImageChannel<half>
0000000000000000 V typeinfo for TypedImageChannel<float>
0000000000000000 V typeinfo for TypedImageChannel<unsigned int>
                 U typeinfo for Iex_2_5::ArgExc
0000000000000030 R typeinfo name for ImageChannel
0000000000000000 V typeinfo name for TypedImageChannel<half>
0000000000000000 V typeinfo name for TypedImageChannel<float>
0000000000000000 V typeinfo name for TypedImageChannel<unsigned int>
                 U vtable for __cxxabiv1::__class_type_info
                 U vtable for __cxxabiv1::__si_class_type_info
```

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
> Seems like those two symbols are present in two distinct files inside `/work/OpenEXR/libOpenexrUtils.a` created by build.sh via `ar`. I'm surprised it doesn't fail with other fuzzers. Though it doesn't fail with my local build too, so I wonder what might be the difference between honggfuzz, my local build, and other fuzzers.
> 
> In any case, I think it might be good to ask owners of this code if this is the desirable situation - creating a library with duplicated symbols. And I'll debug it a little bit more in the meantime.
> 
> If authors of this code think it's the intended way of building this fuzzer, adding the following LDFLAG (by setting CXXFLAG in build.sh) might help here
> 
> `-Wl,-z,muldefs`
> 
> but this is a temporary hack IMO.
> 
> ```
> $ nm build/OpenEXR/exrmultiview/CMakeFiles/exrmultiview.dir/Image.cpp.o | c++filt | grep type
> 0000000000000048 R typeinfo for ImageChannel
> 0000000000000000 V typeinfo for TypedImageChannel<half>
> 0000000000000000 V typeinfo for TypedImageChannel<float>
> 0000000000000000 V typeinfo for TypedImageChannel<unsigned int>
>                  U typeinfo for Iex_2_5::ArgExc
> 0000000000000038 R typeinfo name for ImageChannel
> 0000000000000000 V typeinfo name for TypedImageChannel<half>
> 0000000000000000 V typeinfo name for TypedImageChannel<float>
> 0000000000000000 V typeinfo name for TypedImageChannel<unsigned int>
>                  U vtable for __cxxabiv1::__class_type_info
>                  U vtable for __cxxabiv1::__si_class_type_info
> ```
> 
> ```
> $ nm build/OpenEXR/exrmaketiled/CMakeFiles/exrmaketiled.dir/Image.cpp.o | c++filt | grep type
> 0000000000000040 R typeinfo for ImageChannel
> 0000000000000000 V typeinfo for TypedImageChannel<half>
> 0000000000000000 V typeinfo for TypedImageChannel<float>
> 0000000000000000 V typeinfo for TypedImageChannel<unsigned int>
>                  U typeinfo for Iex_2_5::ArgExc
> 0000000000000030 R typeinfo name for ImageChannel
> 0000000000000000 V typeinfo name for TypedImageChannel<half>
> 0000000000000000 V typeinfo name for TypedImageChannel<float>
> 0000000000000000 V typeinfo name for TypedImageChannel<unsigned int>
>                  U vtable for __cxxabiv1::__class_type_info
>                  U vtable for __cxxabiv1::__si_class_type_info
> ```

@metamerism, any thoughts on fixing this duplicate symbols issue. I think it will impact OSS-Fuzz build.sh [https://github.com/google/oss-fuzz/blob/master/projects/openexr/build.sh] as well once new honggfuzz version rolls in

**Comment by metamerism** [comment]
Hi @inferno-chromium, Since PR 4624 in OSS-Fuzz, libOpenexrUtils.a should have gone away. The fuzz testing code is now in the OpenEXR source in OpenEXRUtil, which gets compiled into libOpenEXRUtil.a
Is fuzzbench picking up an older build.sh file?

**Comment by inferno-chromium** [comment]
> Hi @inferno-chromium, Since PR 4624 in OSS-Fuzz, libOpenexrUtils.a should have gone away. The fuzz testing code is now in the OpenEXR source in OpenEXRUtil, which gets compiled into libOpenEXRUtil.a
> Is fuzzbench picking up an older build.sh file?

Ignore it then. FuzzBench picks benchmarks for fuzzing and several times it can be an old one. If this is not a problem now, no action needed from your side, thanks for confirming then. at some time, we can update benchmark.

**Pull request merged**
