### PR TITLE
update various fuzzers

### PR DESCRIPTION
**Pull request by vanhauser-thc**
afl, aflcc, mopt and honggfuzz have not been updated for a while but received updates.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
aflcc build is failing, can you either take a look or revert the change

```
Stack dump:
0.	Program arguments: /usr/lib/llvm-3.8/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -main-file-name jsoncpp_fuzzer.bc -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -dwarf-column-info -debugger-tuning=gdb -resource-dir /usr/lib/llvm-3.8/bin/../lib/clang/3.8.0 -O3 -std=c++11 -fdebug-compilation-dir /src/jsoncpp -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -load /afl/afl-llvm-pass-original.so -o /tmp/jsoncpp_fuzzer-bb0ddd.o -x ir /out/jsoncpp_fuzzer.bc 
1.	Code generation
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-3.8/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzer.py", line 303, in build
    post_build(fuzz_target)
  File "/src/fuzzer.py", line 259, in post_build
    raise ValueError('command "{command}" failed'.format(command=bin1_cmd))
ValueError: command "/afl/aflc-clang-fast++ -I/usr/local/include/c++/v1/ -stdlib=libc++ -std=c++11 -O3 /out/jsoncpp_fuzzer.bc -o /out/jsoncpp_fuzzer-original -lpthread -lm  -lz -larchive -lglib-2.0 -ldl -lbsd" failed
```

**Comment by vanhauser-thc** [comment]
> aflcc build is failing, can you either take a look or revert the change

also mopt was failing. I fixed the build script and that should work now I hope.

for afl_cc it would be nice if it would build so I created an issue at the repo there: https://github.com/Samsung/afl_cc/issues/1

**Comment by jonathanmetzman** [comment]
Btw is honggfuzz_qemu working? Maybe we should disable it if not?

**Comment by vanhauser-thc** [comment]
> Btw is honggfuzz_qemu working? Maybe we should disable it if not?

good reminder. I changed something, maybe that fixed it ...

**Comment by jonathanmetzman** [comment]
The experiment-requests feature is now ready for public consumption!
Can you request an experiment as described [here](https://google.github.io/fuzzbench/getting-started/adding-a-new-fuzzer/#requesting-an-experiment).

**Comment by vanhauser-thc** [comment]
> The experiment-requests feature is now ready for public consumption!
> Can you request an experiment as described [here](https://google.github.io/fuzzbench/getting-started/adding-a-new-fuzzer/#requesting-an-experiment).

thank you!
will try this out the coming days :)

**Comment by vanhauser-thc** [comment]
@jonathanmetzman  trying the request experiment feature. all those which have been touched with this PR are in the list with the exception of aflplusplus_optimal, not necessary for this one :)

**Comment by vanhauser-thc** [comment]
that is not my error:
```
Reusing existing connection to downloads.sourceforge.net:443.
HTTP request sent, awaiting response... 200 OK
Length: 746 [text/html]
Saving to: ‘libpng-1.2.56.tar.gz’

     0K                                                       100% 96.1M=0s

2020-07-23 17:01:25 (96.1 MB/s) - ‘libpng-1.2.56.tar.gz’ saved [746/746]

+ '[' '!' -e libpng-1.2.56 ']'
+ tar xf libpng-1.2.56.tar.gz

gzip: stdin: not in gzip format
```

**Comment by vanhauser-thc** [comment]
building still fails randomly ...
```
Reusing existing connection to downloads.sourceforge.net:443.
HTTP request sent, awaiting response... 200 OK
Length: 746 [text/html]
Saving to: ‘libpng-1.2.56.tar.gz’

     0K                                                       100%  162M=0s

2020-07-23 20:50:16 (162 MB/s) - ‘libpng-1.2.56.tar.gz’ saved [746/746]

+ '[' '!' -e libpng-1.2.56 ']'
+ tar xf libpng-1.2.56.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
IMHO the PR is fine and could land.

**Comment by vanhauser-thc** [comment]
@jonathanmetzman a different build is failing everytime i force a rebuild ... can you just restart the one failing please? or just accept

**Comment by vanhauser-thc** [comment]
thanks!
lets see if the experiment request feature works :)

**Pull request merged**
