### PR TITLE
LibAFL fuzzers comparison

### PR DESCRIPTION
**Pull request by tokatoka**
Hi, fuzzbench team.

We are currently studying how the selection of fuzzer's technique (scheduling, feedbacks and mutators) affects fuzzer's performance.

For this, we want to do a large-scale evaluation of 13 fuzzers using libafl and see how each fuzzer perform's in every target program.

cc @andreafioraldi

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@Alan32Liu can you start an experiment for this using gcbrun?

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-05-19-libafl_var --fuzzers libafl_fuzzbench_cmplog libafl_fuzzbench_cov_accounting libafl_fuzzbench_eco libafl_fuzzbench_explore libafl_fuzzbench_fast libafl_fuzzbench_mopt libafl_fuzzbench_naive libafl_fuzzbench_naive_ctx libafl_fuzzbench_ngram4 libafl_fuzzbench_ngram8 libafl_fuzzbench_rand_scheduler libafl_fuzzbench_value_profile libafl_fuzzbench_weighted

**Comment by Alan32Liu** [comment]
@tokatoka Could you please make [a dummy modification](https://github.com/google/fuzzbench/pull/1818/files#diff-e870d8214beac56eaaeda2edc69de842f8382c428329dd8cf826a9cfa5edf7e9R19) to `service/gcbrun_experiment.py` so that I can trigger the experiment here?
Thanks!

**Comment by tokatoka** [comment]
Done!

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-05-22-libafl_var --fuzzers libafl_fuzzbench_cmplog libafl_fuzzbench_cov_accounting libafl_fuzzbench_eco libafl_fuzzbench_explore libafl_fuzzbench_fast libafl_fuzzbench_mopt libafl_fuzzbench_naive libafl_fuzzbench_naive_ctx libafl_fuzzbench_ngram4 libafl_fuzzbench_ngram8 libafl_fuzzbench_rand_scheduler libafl_fuzzbench_value_profile libafl_fuzzbench_weighted

**Comment by Alan32Liu** [comment]
Experiment data and report will be available later at:
[Experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-05-22-libafl_var/).
[Experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-05-22-libafl_var/index.html).

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-05-22-libafl-var --fuzzers libafl_fuzzbench_cmplog libafl_fuzzbench_cov_accounting libafl_fuzzbench_eco libafl_fuzzbench_explore libafl_fuzzbench_fast libafl_fuzzbench_mopt libafl_fuzzbench_naive libafl_fuzzbench_naive_ctx libafl_fuzzbench_ngram4 libafl_fuzzbench_ngram8 libafl_fuzzbench_rand_scheduler libafl_fuzzbench_value_profile libafl_fuzzbench_weighted

**Comment by tokatoka** [comment]
The experiment will run till 24h, right?

**Comment by andreafioraldi** [comment]
> The experiment will run till 24h, right?

23h

**Comment by tokatoka** [comment]
Do you know why libafl_fuzzbench_ngram8 on bloaty_fuzz_targets says NaN while we do have the data here?
https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-05-22-libafl-var/experiment-folders/bloaty_fuzz_target-libafl_fuzzbench_ngram8/

**Comment by Alan32Liu** [comment]
> Do you know why libafl_fuzzbench_ngram8 on bloaty_fuzz_targets says NaN while we do have the data here? https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-05-22-libafl-var/experiment-folders/bloaty_fuzz_target-libafl_fuzzbench_ngram8/

The result will be `NaN` if it fails to complete the 23-hour experiment?
I looked into one trial and found it terminated in 3 hours.
Could you please check the rest? Thanks : )

**Comment by tokatoka** [comment]
Hey @Alan32Liu 
We found that perhaps the coverage map is too big for some fuzzers, leading to their worse performance

I fixed the size of the map in https://github.com/google/fuzzbench/pull/1840/commits/e6e6404be28e610bc5bfdc055025dde12f0050c0
Could you do another experiment for `libafl_libfuzzer_ngram4`, `libafl_libfuzzer_ngram8` and `libafl_libfuzzer_naive_ctx` with this new setup?

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-05-31-libafl-var --fuzzers libafl_libfuzzer_ngram4 libafl_libfuzzer_ngram8 libafl_libfuzzer_naive_ctx

**Comment by Alan32Liu** [comment]
> Hey @Alan32Liu We found that perhaps the coverage map is too big for some fuzzers, leading to their worse performance
> 
> I fixed the size of the map in [e6e6404](https://github.com/google/fuzzbench/commit/e6e6404be28e610bc5bfdc055025dde12f0050c0) Could you do another experiment for `libafl_libfuzzer_ngram4`, `libafl_libfuzzer_ngram8` and `libafl_libfuzzer_naive_ctx` with this new setup?

Sure!
[Experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-05-31-libafl-var/).
[Experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-05-31-libafl-var/index.html).

**Comment by Alan32Liu** [comment]
> Hey @Alan32Liu We found that perhaps the coverage map is too big for some fuzzers, leading to their worse performance
> 
> I fixed the size of the map in [e6e6404](https://github.com/google/fuzzbench/commit/e6e6404be28e610bc5bfdc055025dde12f0050c0) Could you do another experiment for `libafl_libfuzzer_ngram4`, `libafl_libfuzzer_ngram8` and `libafl_libfuzzer_naive_ctx` with this new setup?

Ops, I believe the experiment was not launched due to incorrect fuzzer names:
Judging by the new dirs you added, I guess you meant `libafl_fuzzbench_ngram4`, `libafl_fuzzbench_ngram8` and `libafl_fuzzbench_naive_ctx`?
I will relaunch the experiment with those names instead.

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-06-02-libafl-var --fuzzers libafl_fuzzbench_ngram4 libafl_fuzzbench_ngram8 libafl_fuzzbench_naive_ctx

**Comment by Alan32Liu** [comment]
These should be available in hours:
[Experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-06-02-libafl-var/).
[Experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-06-02-libafl-var/index.html).

**Comment by tokatoka** [comment]
> Ops, I believe the experiment was not launched due to incorrect fuzzer names:
Judging by the new dirs you added, I guess you meant libafl_fuzzbench_ngram4, libafl_fuzzbench_ngram8 and libafl_fuzzbench_naive_ctx?

Yup my mistake :sweat_smile: 

> These should be available in hours:

Thanks!

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-06-06-libafl-var --fuzzers libafl_fuzzbench_naive_ctx --benchmark harfbuzz_hb-shape-fuzzer

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-06-07-libafl-var --fuzzers libafl_fuzzbench_naive_ctx --benchmarks harfbuzz_hb-shape-fuzzer

**Comment by Alan32Liu** [comment]
> Hi, @Alan32Liu there was another error for `libafl_fuzzbench_naive_ctx` on `harfbuzz_hb-shape-fuzzer` (I forgot -lm to compile)
> 
> Could you run one more for experiment only for `libafl_fuzzbench_naive_ctx` and only on `harfbuzz_hb-shape-fuzzer`?

No problem, here are the links:
[Experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-06-07-libafl-var/).
[Experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-06-07-libafl-var/index.html).

**Comment by tokatoka** [comment]
hey @Alan32Liu.
Thanks for all the stuff. I think we can close this.
One question, in the result page, I see we have the data from other fuzzers too (non-libafl fuzzer; aflpp, hoggfuzz, libfuzzer, ... and others)
Do you know where these data of other fuzzers come from?
They were run right after our fuzzers experiment ?, or they were run before (from which day's experiment) and then the result is just merged?

**Pull request closed without merging**
