### PR TITLE
Requesting new experiments for AFL schedules

### PR DESCRIPTION
**Pull request by mboehme**
This experiment is to test the following schedules
* `afl_fast_32` integrates spliceless and xxh3 with the previous afl_fast_32.
* `afl_fast_branches` integrates XXH3 and skips to favourites that exercise rare branches (called champions), and falls back to vanilla AFL once we run out of champions.
* `afl_fast_branches2` is the same as `afl_fast_branches` but falls back to `afl_fast_32` once we run out of champions.
* `afl_oldfast_4` and `afl_oldfast_16` are like `afl_fast_32` but give more energy to seeds that have been chosen often and still exercise rare paths.
* `afl_coe` is like `afl_fast_32` but assigns zero energy to seeds that exercise paths with above average log2(n_fuzz).
* `afl_oldcoe_16` is like `afl_oldfast_16` but assigns zero energy to seeds that exercise paths with above average log2(n_fuzz).

Insights from last experiments (more detailed report to follow):
* `afl_fast_spliceless2` (which removes the impact of boosting the perf_score from splice_havoc) has been effective.
* In general, edge coverage alone is insufficient, hit counts are an important signal (even the efficient `afl_nohits_srsly` performed much worse than `afl`)
* Almost all FAST schedules outperform AFL in terms of number of unique crashes and time to error.
* Specific schedules perform well really well on specific benchmarks, even if they don't generally outperform.

### CODE REVIEW

**Review by inferno-chromium — CHANGES_REQUESTED** [review]
Please add the change to request experiment :) service/experiment-requests.yaml. Also sync to trunk so that you take latest version of that file.

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
Just fyi, 2020-10-14 experiment will be used.

**Comment by mboehme** [comment]
The CI is failing on some of my fuzzers. Found the problem in a last minute change.. l'll submit another.

**Comment by jonathanmetzman** [comment]
> The CI is failing on some of my fuzzers. Found the problem in a last minute change.. 
> l'll submit another PR.

Thanks!

**Comment by inferno-chromium** [comment]
> The CI is failing on some of my fuzzers. Found the problem in a last minute change.. 😅
> l'll submit another PR.

Ok, i thought CI was green before this last one. Maybe i didnt remember correctly, i have stopped 2020-10-14 now, please just change the date in experiment requests to trigger a new one. can even use "2020-10-13-2". also i will wait for CI this time :)

**Comment by mboehme** [comment]
> please just change the date in experiment requests to trigger a new one.
Done.

Apologies. Didn't git add the .github/workflows/fuzzer.yml either. So, they were missed in CI. The build failed because it didn't add an untracked file to the patch.diff. I tested the versions for a patch which had the file, but I needed to change something. After git reset (to switch from another fuzzer variant) and git apply (to make my changes), the additional file was untracked again.

Submitted PR #817. Fixed some bugs, as well.

**Pull request merged**
