### PR TITLE
new cmplog variants and experiment

### PR DESCRIPTION
**Pull request by vanhauser-thc**
as symqemu is not mergable yet - a new cmplog experiment :) let's use those cores! :D

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Some minor issue in dockerfile

```
#6 0.272 Cloning into '/afl'...
#6 2.506 error: unknown switch `i'
#6 2.506 usage: git checkout [<options>] <branch>
#6 2.506    or: git checkout [<options>] [<branch>] -- <file>...
```

**Comment by vanhauser-thc** [comment]
oh damn, thanks & sorry

**Comment by vanhauser-thc** [comment]
its ready to merge, no more adding by me :)

**Comment by vanhauser-thc** [comment]
@inferno-chromium it was merged 15 hours ago, the experiment is not showing up - are there any issues?

**Comment by inferno-chromium** [comment]
> @inferno-chromium it was merged 15 hours ago, the experiment is not showing up - are there any issues?

same name conflict, need some test to detect these, fixed in https://github.com/google/fuzzbench/commit/c264147a9f93efc9e84b6a46016bfcd143b5d4b5, should start now.

**Pull request merged**
