### PR TITLE
Add Proxygen benchmark.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
In .github/workflows/build.py there's a list of benchmarks. This needs to be added to one.

**Comment by inferno-chromium** [comment]
@mhlakhani - do you think this will be a good benchmark fuzzer ?

**Comment by inferno-chromium** [comment]
> In .github/workflows/build.py there's a list of benchmarks. This needs to be added to one.

Done, thanks!

**Comment by jonathanmetzman** [comment]
> @mhlakhani - do you think this will be a good benchmark fuzzer ?

e.g. does it not do things considered "wrong" for fuzzing like accumulating state, connecting to the network, etc.

**Comment by mhlakhani** [comment]
apologies for not seeing this until now - yeah I think this would be a good benchmark. it does not keep any state across requests and only does parsing.

**Comment by jonathanmetzman** [comment]
Can you update the table of our benchmarks after you run this?
The script I wrote only works if you have the coverage build zip that we create during experiments so feel free to wait until you do an experiment or get the data manually now.

**Comment by inferno-chromium** [comment]
> Can you update the table of our benchmarks after you run this?
> The script I wrote only works if you have the coverage build zip that we create during experiments so feel free to wait until you do an experiment or get the data manually now.

Yes, once oyu LGTM this, we merge, run and then i can update table.

**Pull request merged**
