### PR TITLE
Benchmark new AFL++ feature with saturated corpus

### PR DESCRIPTION
**Pull request by andreafioraldi**
The last experiment was promising even if I coded the new feature in 2 days with a very slow instrumentation.
On targets in which speed matters and it is very useful to get more coverage sooner, it was ofc decremental (e.g https://www.fuzzbench.com/reports/experimental/2021-06-03-aflpp/index.html#arrow_parquet-arrow-fuzz-summary watch the cov graph the line is continuously increasing even after 20h).
On the other hand, on target in which the fuzzer can easily reach saturation it was able to uncover more bugs (e.g. https://www.fuzzbench.com/reports/experimental/2021-06-03-aflpp/index.html#matio_matio_fuzzer-summary and in htp https://www.fuzzbench.com/reports/experimental/2021-06-03-aflpp/index.html#libhtp_fuzz_htp-summary I don't recall any experiment in which any fuzzer triggered more than 5 bugs).

Today I worked a bit on it, improving the speed situation and the feedback (previously was working only with aflpp with classic instr, so collisions) and now I want to test it on a saturated corpus from OSS-Fuzz to see if it can de-saturate it.

### CODE REVIEW

**Comment by andreafioraldi** [comment]
Note: libarchive does not build because of an infinite loop (maybe the basic alias analysis?) and PHP, well, it's PHP

**Comment by andreafioraldi** [comment]
@inferno-chromium @jonathanmetzman is there a way to know if two fuzzers triggered different bugs?

**Comment by inferno-chromium** [comment]
> @inferno-chromium @jonathanmetzman is there a way to know if two fuzzers triggered different bugs?

crash state should be in the experiment table, that can be used to distinguish bugs.

**Comment by andreafioraldi** [comment]
> > @inferno-chromium @jonathanmetzman is there a way to know if two fuzzers triggered different bugs?
> 
> crash state should be in the experiment table, that can be used to distinguish bugs.

I see "Total unique bugs found on each benchmark", in which there is the total number of bugs and the number discovered by each fuzzer, would be helpful to have the intersection between each pair of fuzzers, if it is not already in the report (maybe I missed it, it is night now in EU :) )

**Comment by inferno-chromium** [comment]
> > > @inferno-chromium @jonathanmetzman is there a way to know if two fuzzers triggered different bugs?
> > 
> > 
> > crash state should be in the experiment table, that can be used to distinguish bugs.
> 
> I see "Total unique bugs found on each benchmark", in which there is the total number of bugs and the number discovered by each fuzzer, would be helpful to have the intersection between each pair of fuzzers, if it is not already in the report (maybe I missed it, it is night now in EU :) )

in every report at end, there is a "You can download the raw data for this report here." download that csv by clicking on here, that has detailed data points.

**Comment by andreafioraldi** [comment]
There is a bug in the fuzzer, sorry for that!
I just read again the code this morning and there is a typo that breaks the logic (a missing boolean neg duh).
If I'm in time, please do not start this experiment @inferno-chromium , otherwise stop it to not waste CPU time, sorry again for that.

**Comment by inferno-chromium** [comment]
> There is a bug in the fuzzer, sorry for that!
> I just read again the code this morning and there is a typo that breaks the logic (a missing boolean neg duh).
> If I'm in time, please do not start this experiment @inferno-chromium , otherwise stop it to not waste CPU time, sorry again for that.

luckily didnt start yet, so removed from yaml file and this one should start sometime today.

**Pull request merged**
