### PR TITLE
Corpus Pruning Algorithm Experiment

### PR DESCRIPTION
**Pull request by tokatoka**
This PR tries new idea from https://mschloegel.me/paper/schiller2023fuzzerrestarts.pdf

I implemented a fuzzer that periodically reset the scorpus every 30/120 minutes after novelty was not found/enough time has passed.

### CODE REVIEW

**Comment by tokatoka** [comment]
@DonggeLiu 
Could you run the CI?

**Comment by tokatoka** [comment]
@DonggeLiu Ping

**Comment by DonggeLiu** [comment]
Done!
I was on leave last week.

**Comment by tokatoka** [comment]
it looks like everytime i update it needs additional approval 😅 
can you run it again?

**Comment by DonggeLiu** [comment]
> it looks like everytime i update it needs additional approval 😅 can you run it again?

Do you happen to know any way to allow certain users (like you) to always be able to run CIs?

**Comment by tokatoka** [comment]
I think you can make me "Collaborator".

**Comment by DonggeLiu** [comment]
> I think you can make me "Collaborator".

Oh we will have to discuss this with other owners of this repo.
Is there a more lightweight alternative?

**Comment by tokatoka** [comment]
https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#configuring-required-approval-for-workflows-from-public-forks

I think all the options are written here but it looks like there's no functionality to allow specific users to run CI

**Comment by tokatoka** [comment]
but it's strange because previously you didn't have to manually run it for me right?

**Comment by DonggeLiu** [comment]
> but it's strange because previously you didn't have to manually run it for me right?

I am not sure, maybe I did.

**Comment by tokatoka** [comment]
i'm still debuggin it :)

**Comment by tokatoka** [comment]
i think i resolved the problem, could you run again?

**Comment by jonathanmetzman** [comment]
I've changed things so we shouldn't need to approve every time actions wants to run

**Comment by tokatoka** [comment]
thank you!

**Comment by tokatoka** [comment]
@DonggeLiu The CI looks good 
can we run the experiment?
The command is 

```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-05-14-libafl-pruner --fuzzers libafl libafl_latest libafl_r120_force_10 libafl_r120_force_50 libafl_r120_last_10 libafl_r120_last_50 libafl_r30_force_10 libafl_r30_force_50 libafl_r30_last_10 libafl_r30_last_50
```

**Comment by DonggeLiu** [comment]
Sure! We are still resolving the bottleneck in measurement so we cannot run too many fuzzers in one experiment. Ideally let's keep ~5 fuzzers in each.
How would you like to group them?

**Comment by tokatoka** [comment]
ok

This is group A.
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-05-14-libafl-pruner --fuzzers libafl libafl_latest libafl_r120_force_10 libafl_r120_force_50 libafl_r120_last_10
```

This is group B
```
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-05-14-libafl-pruner --fuzzers libafl_r120_last_50 libafl_r30_force_10 libafl_r30_force_50 libafl_r30_last_10 libafl_r30_last_50
```

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-02-libafl-pruner --fuzzers libafl libafl_latest libafl_r120_force_10 libafl_r120_force_50 libafl_r120_last_10

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-02-libafl-pruner --fuzzers libafl_r120_last_50 libafl_r30_force_10 libafl_r30_force_50 libafl_r30_last_10 libafl_r30_last_50

**Comment by DonggeLiu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2024-08-02-libafl-pruner-1 --fuzzers libafl_r120_last_50 libafl_r30_force_10 libafl_r30_force_50 libafl_r30_last_10 libafl_r30_last_50

**Comment by DanBlackwell** [comment]
HI @tokatoka , not my PR so sorry to intrude; it looks like your experiment did start, as the experiment data was created and the logs indicate it's running [here](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-02-libafl-pruner-1/). I've had the same thing happen on the last 2 runs of my PR [here](https://github.com/google/fuzzbench/pull/2000#issuecomment-2259034820); the `coverage` sub-directory in the data never gets created, even though the fuzzer is running.

 I wonder if there's anything obvious in the logs? (I guess one of the FB team can see these?)

**Comment by tokatoka** [comment]
thanks for the info!
it looks like all the experiment that began today is affected..

**Comment by DonggeLiu** [comment]
This is likely due to `no space on device`:
image


@gustavogaldinoo could you please look in this? Thanks!

**Comment by DonggeLiu** [comment]
Also noticed many `Profdata files merging failed.` and `https://github.com/google/fuzzbench/pull/2011#issuecomment-2270197163` in the cloud log, which may block the experiment report generation. Related: https://github.com/google/fuzzbench/pull/2011#issuecomment-2270197163.

BTW, will this PR generate a large corpus? This may explain the tons of `no space left on device` errors.

**Comment by tokatoka** [comment]
> BTW, will this PR generate a large corpus? This may explain the tons of no space left on device errors.

yes. i'm thinking about the fix for it now..

**Comment by DanBlackwell** [comment]
Any chance you ran this somewhere in the end? It would be interesting to see the results even if it's only a subset of the available benchmarks that don't use much storage (e.g. [open_h264 looks bad for storage](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-02-libafl-pruner-1/experiment-folders/openh264_decoder_fuzzer-libafl_r30_force_10/trial-3013055/corpus/), [as does proj4](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2024-08-02-libafl-pruner-1/experiment-folders/proj4_proj_crs_to_crs_fuzzer-libafl_r30_force_10/trial-3013101/corpus/))

**Comment by tokatoka** [comment]
no i didn't run this in the end

**Pull request closed without merging**
