### PR TITLE
Transparent oss fuzz benchmarks

### PR DESCRIPTION
**Pull request by Tanq16**
PR to merge transparent OSS-Fuzz benchmark build system and migrate the following OSS-Fuzz benchmarks -
|||
| ---------- | --------- |
|1| bloaty_fuzz_target |
|2| curl_curl_fuzzer_http |
|3| jsoncpp_jsoncpp_fuzzer |
|4| libpcap_fuzz_both |
|5| mbedtls_fuzz_dtlsclient |
|6| openssl_x509 |
|7| systemd_fuzz-link-parser |
|8| php_php-fuzz-parser |
|9| zlib_zlib_uncompress_fuzzer |

### CODE REVIEW

**Comment by Tanq16** [comment]
Commits by @jonathanmetzman present in the PR.

**Comment by Tanq16** [comment]
@googlebot I fixed it.

**Comment by jonathanmetzman** [comment]
Can you resolve the conflict please?

**Comment by jonathanmetzman** [comment]
Looks like all of the failures are unrelated and due to a libxml build issue.

**Comment by jonathanmetzman** [comment]
I think before landing this we should run an experiment with it and compare the results.
I'll get started on that later today.

**Comment by Tanq16** [comment]
> Looks like all of the failures are unrelated and due to a libxml build issue.

Yes, none of the OSS-Fuzz benchmarks fail.

**Comment by jonathanmetzman** [comment]
Report from an experiment: http://commondatastorage.googleapis.com/fuzzbench-reports/oss-fuzz-benchmarks/index.html
Need to compare this to a report with same fuzzers and same benchmarks. Eyeballing it though it looks ready to land.
Can you pull from master and fix the build failures please.

**Comment by jonathanmetzman** [comment]
The experiment is actually still in progress.

**Comment by Tanq16** [comment]
> The experiment is actually still in progress.

Yes sorry, I saw that after the pull. Any subsequent change required ?

**Comment by jonathanmetzman** [comment]
> > The experiment is actually still in progress.
> 
> Yes sorry, I saw that after the pull. Any subsequent change required ?

Not that I can think of right now.

**Comment by jonathanmetzman** [comment]
Don't know why Github closed this and won't let me reopen. I've opened an equivalent PR here: https://github.com/google/fuzzbench/pull/569

**Pull request closed without merging**
