### PR TITLE
[DO NOT MERGE] New experiment test config yaml

### PR DESCRIPTION
**Pull request by gustavogaldinoo**
Just testing the gcbrun command and checking experiments results on gcp

### CODE REVIEW

**Comment by gustavogaldinoo** [comment]
/gcbrun run_experiment.py --experiment-config experiment-config.yaml --benchmarks sqlite3_ossfuzz bloaty_fuzz_target --experiment-name gustavo-galdino-gcbrun-test --fuzzers afl libfuzzer -a

**Comment by gustavogaldinoo** [comment]
/gcbrun run_experiment.py -a --experiment-config experiment-config.yaml --benchmarks sqlite3_ossfuzz bloaty_fuzz_target --experiment-name gustavo-galdino-gcbrun-test --fuzzers afl libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun run_experiment.py -a --experiment-config experiment-config.yaml --benchmarks sqlite3_ossfuzz bloaty_fuzz_target --experiment-name gustavo-galdino-gcbrun-test --fuzzers afl libfuzzer

**Comment by gustavogaldinoo** [comment]
/gcbrun run_experiment.py -a --experiment-config experiment-config.yaml --benchmarks sqlite3_ossfuzz bloaty_fuzz_target --experiment-name gustavo-galdino-gcbrun-test --fuzzers afl libfuzzer

**Comment by gustavogaldinoo** [comment]
/gcbrun run_experiment.py -a --experiment-config experiment-config.yaml --benchmarks sqlite3_ossfuzz bloaty_fuzz_target --experiment-name gustavo-galdino-gcbrun-test --fuzzers afl libfuzzer

**Comment by gustavogaldinoo** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --benchmarks sqlite3_ossfuzz bloaty_fuzz_target --experiment-name gustavo-galdino-gcbrun-test --fuzzers afl libfuzzer

**Pull request closed without merging**
