### PR TITLE
Add nginx benchmark, add support for hg in checkout_commit.py

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by inferno-chromium** [comment]
@vanhauser-thc - i really want to get nginx benchmark, was wondering if you can check what is going on with the compile failures with aflplusplus here. Use this patch on trunk, and see failure with test-aflplusplus-nginx_http_request_fuzzer. Rest all fuzzers are all ok, so i am kind of blocked here. I can blacklist it, but at this point, too many afl++ variants and blacklisting will be pain.

**Comment by vanhauser-thc** [comment]
> @vanhauser-thc - i really want to get nginx benchmark, was wondering if you can check what is going on with the compile failures with aflplusplus here. Use this patch on trunk, and see failure with test-aflplusplus-nginx_http_request_fuzzer. Rest all fuzzers are all ok, so i am kind of blocked here. I can blacklist it, but at this point, too many afl++ variants and blacklisting will be pain.

uh nice find. dict2file llvm module bug. will add a fix once I have figured out where it breaks.

**Comment by vanhauser-thc** [comment]
why the hell is nginx using 96 bit integers ... should work now

**Comment by inferno-chromium** [comment]
> why the hell is nginx using 96 bit integers ... should work now

Thanks a lot, retriggered CI.

**Comment by vanhauser-thc** [comment]
Coe2 fast2 etc will fail because they use an old commit that is required for @mboehme ‘s patch

**Comment by inferno-chromium** [comment]
> Coe2 fast2 etc will fail because they use an old commit that is required for @mboehme ‘s patch

I wont commit this then for the current 09-22, 09-23 experiments.

**Comment by inferno-chromium** [comment]
@vanhauser-thc - any idea why aflplusplus_optimal still fails.

**Comment by vanhauser-thc** [comment]
of course it does ... the feature is implemented twice and I forgot to fix it in LTO. my bad. it was 2:30 in the morning ...

**Pull request merged**
