### PR TITLE
two new experiments

### PR DESCRIPTION
**Pull request by vanhauser-thc**
for @andreafioraldi a bug benchmark
for me a normal cmplog, schedule and optimal benchmark

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
I will enable "auto-merge" when this PR is ready.

**Review by inferno-chromium — APPROVED** [review]

**Comment by andreafioraldi** [comment]
@googlebot I consent.

**Comment by vanhauser-thc** [comment]
@inferno-chromium  it wont automerge ... it can be merged now. thank you!

**Comment by inferno-chromium** [comment]
> @inferno-chromium it wont automerge ... it can be merged now. thank you!

are afl_buf failures expected, they look real - https://github.com/google/fuzzbench/pull/1094/checks?check_run_id=1952345856

**Comment by vanhauser-thc** [comment]
> > @inferno-chromium it wont automerge ... it can be merged now. thank you!
> 
> are afl_buf failures expected, they look real - https://github.com/google/fuzzbench/pull/1094/checks?check_run_id=1952345856

they are real but no concern. this is specifically for a bug benchmark, there all target checks pass.

**Comment by inferno-chromium** [comment]
first experiment started, second should start soon after this regex fix - https://github.com/google/fuzzbench/commit/1d767c8a79da104d0b0e8d13185ba8761c32909d

**Pull request merged**
