### PR TITLE
Redo ecofuzz experiment

### PR DESCRIPTION
**Pull request by jonathanmetzman**
@Alan32Liu @andreafioraldi

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
TBR

**Review by Alan32Liu — COMMENTED** [review]
LGTM, thanks!

**Comment by andreafioraldi** [comment]
Ty, it looks AFL didn't start yet on some targets like woff2, it will be scheduled later or is it a bug?
It is reasonable for Ecofuzz to fail to run some benchmarks but AFL should work with any benchmark in theory.
Maybe try to reduce the number of trials to 10 or even 5 if the issue is resource exhaustion.

**Comment by jonathanmetzman** [comment]
I think AFL is working. I don't think there's resource exhaustion. Measurement is just bad. sorry

**Pull request merged**
