### PR TITLE
Remove bug-draft

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by Alan32Liu** [comment]
Yeah, maybe it is a good idea to remove them.
I can find more bug-based benchmarks from OSS-Fuzz, not necessarily reusing and updating these.

**Review by Alan32Liu — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
> Yeah, maybe it is a good idea to remove them. I can find more bug-based benchmarks from OSS-Fuzz, not necessarily reusing and updating these.

These are probably good to start with, unless you've tried fixing them and they are hard to fix. Have you?

**Comment by Alan32Liu** [comment]
> > Yeah, maybe it is a good idea to remove them. I can find more bug-based benchmarks from OSS-Fuzz, not necessarily reusing and updating these.
> 
> These are probably good to start with, unless you've tried fixing them and they are hard to fix. Have you?

Not at this moment.
I do plan to add more bug-based benchmarks (not necessarily these ones), but it's probably cleaner to delete them now and add them back later if needed.

**Comment by jonathanmetzman** [comment]
I think these CI jobs must not be considered mandatory...

**Pull request merged**
