### PR TITLE
aflplusplus_fortify

### PR DESCRIPTION
**Pull request by vanhauser-thc**
Can you please add this variant and then start a comparison of aflplusplus, aflplusplus_noalloc and aflplusplus_fortify? (plus what else would be good to have a current evaluation)

Thanks a lot!

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
We are already doing a full evaluation. I think tommorow I can start an expeirment with aflplusplus_noalloc and we can combine the results.

**Comment by jonathanmetzman** [comment]
btw, it doesn't look like the seed fixing you did had much of an effect judging from the results I see here: https://www.fuzzbench.com/reports/2020-04-01/index.html

I still see afl++ having different coverage values for min, max, median,25th percentile and 50th percentile.

**Comment by vanhauser-thc** [comment]
> I assume everything is the same except for the hash because the change was made on master and you want to compare it to an older commit on master?

yes exactly. thanks!



> btw, it doesn't look like the seed fixing you did had much of an effect judging from the results I see here: https://www.fuzzbench.com/reports/2020-04-01/index.html
> 
> I still see afl++ having different coverage values for min, max, median,25th percentile and 50th percentile.
> We should probably undo that change I'm thinking.

I saw the same thing. I have now to check if this is a bug in afl++ that the -s is not working as it should - but if it does then fuzzbench results are unreliable. that would be a major issue. I will investigate this and get back to you.

**Comment by jonathanmetzman** [comment]
>but if it does then fuzzbench results are unreliable. that would be a major issue.

If it isn't due to AFL++ it may be a sign of a "major issue" in FuzzBench, but it's possible there isn't anything seriously wrong. The latter would be true if there are small amounts of non-determinism in fuzz targets as I mentioned in a previous thread.

**Comment by jonathanmetzman** [comment]
I tried running a few instances of the sqlite benchmark with libFuzzer and the same seed to see if it was deterministic. I used this command for 4 instances:
```
./ossfuzz seeds/ -seed=1 -max_total_time=120
```
These are the last lines of output I saw on each instance:
```
#24160  DONE   cov: 7148 ft: 31839 corp: 895/129Mb lim: 1048576 exec/s: 199 rss: 198Mb
```

```
#46545  DONE   cov: 7593 ft: 35118 corp: 1231/63Mb lim: 1048576 exec/s: 384 rss: 150Mb
```

```
#54252  DONE   cov: 7942 ft: 36283 corp: 1287/43Mb lim: 1048576 exec/s: 448 rss: 118Mb
```

```
#55621  DONE   cov: 7325 ft: 34116 corp: 1186/55Mb lim: 1048576 exec/s: 459 rss: 144Mb
```

It's possible there is a bug in libfuzzer, or maybe the way I ran them favored the later runs (as the speed (exec/s) seems to be increasing) but my guess is that the targets have enough non-determinism in them to make the seed useless.

**Comment by vanhauser-thc** [comment]
I pushed a PR which fixed an area for fixed seed that was not fixed. now it is deterministic every time (unless the target does random stuff). when this has run through we will know :)

**Comment by vanhauser-thc** [comment]
> ```
> #54252  DONE   cov: 7942 ft: 36283 corp: 1287/43Mb lim: 1048576 exec/s: 448 rss: 118Mb
> ```
> ```
> #55621  DONE   cov: 7325 ft: 34116 corp: 1186/55Mb lim: 1048576 exec/s: 459 rss: 144Mb
> ```

here you can see something is wrong: the run above is slower than the one below - but finds more paths. so yes, either there is an issue in libfuzzer with the seeds, the target does random things (unlikely with sqlite), or it is fuzzbench.

My money is on libfuzzer though. Because I think they made the same mistake I did - although the seed is fixed and all random values generated are the same, the run-time measurements of a new discovered path can be different and that results in different priorizations of queue entries, and therefore queue selections etc.

**Comment by jonathanmetzman** [comment]
I started a fortify experiment this morning btw.

>My money is on libfuzzer though. Because I think they made the same mistake I did - although the seed is fixed and all random values generated are the same, the run-time measurements of a new discovered path can be different and that results in different priorizations of queue entries, and therefore queue selections etc.

Ah do you mean the instrumentation can't tell when two runs have the exact same coverage?
i think AFL uses the timing of testcases, I'd expect this not to behave deterministically.

Did you fix this already (so I can narrow down causes if we see similar problems on the next afl++ run)?

**Comment by vanhauser-thc** [comment]
> Ah do you mean the instrumentation can't tell when two runs have the exact same coverage?
> i think AFL uses the timing of testcases, I'd expect this not to behave deterministically.

no, what I mean:
Expectations are that with the same seed you would get the exact same result (edges found, etc.) with the only difference being the runtime because of CPU scheduling and load.
But this is not the case because if you run the same input several time you will get different run times for that input. and the run time is part of the seed selection algorithm of afl and libfuzzer. so although the random numbers are all the same, a different run of the fuzzer will get different run times for the same input and therefore select different seeds and hence the difference.

> Did you fix this already (asking so I can narrow down causes if we see similar problems on the next afl++ run)?

I fixed this, so the difference we will see in the fortify run will show in what range the available CPU time is different between the runs.

**Comment by jonathanmetzman** [comment]
> > Ah do you mean the instrumentation can't tell when two runs have the exact same coverage?
> > i think AFL uses the timing of testcases, I'd expect this not to behave deterministically.
> 
> no, what I mean:
> Expectations are that with the same seed you would get the exact same result (edges found, etc.) with the only difference being the runtime because of CPU scheduling and load.
> But this is not the case because if you run the same input several time you will get different run times for that input. and the run time is part of the seed selection algorithm of afl and libfuzzer. so although the random numbers are all the same, a different run of the fuzzer will get different run times for the same input and therefore select different seeds and hence the difference.
> 

Got it. By the way, as far as I know, the time a seed takes to execute does not directly impact seed selection in libFuzzer. I think this could happen indirectly though if a testcase times out in one libFuzzer run but doesn't timeout in another.

> > Did you fix this already (asking so I can narrow down causes if we see similar problems on the next afl++ run)?
> 
> I fixed this, so the difference we will see in the fortify run will show in what range the available CPU time is different between the runs.

Maybe, but I still think the targets may have some nondeterminism. In https://github.com/google/fuzzbench/pull/158#issuecomment-605148424 for example, I found that the SQLite target is ~76% stable.

**Comment by jonathanmetzman** [comment]
We can revert this now right?

**Comment by vanhauser-thc** [comment]
already pushed a PR which removes it and adds the next level of tests. after that: different target instrumentations :)

**Pull request merged**
