### PR TITLE
KLEE: convert files in a dedicated thread

### PR DESCRIPTION
**Pull request by laurentsimon**

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]
Please fix the lint failures,

`make format`
and `'make lint` then to check. for some imports like psutil, would need to pylint disable, i dont think that is fixable.

What should we do for this hardcoded max memory i added as 3200 ? since you use psutil now, can you make it automatic then, maybe like Max memory = max free memory using psutil - 2 gb ? or wdyt ? i plan to run klee on a 2 core 13 gb memory machine.

**Comment by laurentsimon** [comment]
This sounds like a good idea to automatically set the max memory. I'll make the changes.

**Comment by laurentsimon** [comment]
`make lint` and `make presubmit` worked locally. Not sure why it's still triggering an error here :/

**Comment by inferno-chromium** [comment]
```
source .venv/bin/activate && python3 presubmit.py
--- /home/runner/work/fuzzbench/fuzzbench/fuzzers/klee/fuzzer.py	(original)
+++ /home/runner/work/fuzzbench/fuzzbench/fuzzers/klee/fuzzer.py	(reformatted)
@@ -370,6 +370,7 @@
                 Found {crashes} crashes'.format(converted=n_converted,
                                                 crashes=n_crashes))
 
+
 # pylint: disable=import-error
 # pylint: disable=import-outside-toplevel
 def monitor_resource_usage():
@@ -389,6 +390,7 @@
         print('[resource_thread] Resource usage after {time}:\n{message}',
               time=now - start,
               message=message)
+
 
 # pylint: disable=import-error
 # pylint: disable=import-outside-toplevel
```

add those two extra lines
unsure why lint is not showing these, are you on python 3.7 virtualenv

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
Started 2020-10-13-klee test experiment with n1-highmem-2. Should show up on https://www.fuzzbench.com/reports/experimental/index.html

**Pull request merged**
