### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I might have to undo the change to CI because while it does work well for adding new fuzzers, it works terribly for modifying core fuzzers like afl which every fuzzer depends on, since now these builds will be repeated on so many machines.

**Comment by jonathanmetzman** [comment]
TBR

**Comment by Alan32Liu** [comment]
> I might have to undo the change to CI because while it does work well for adding new fuzzers, it works terribly for modifying core fuzzers like afl which every fuzzer depends on, since now these builds will be repeated on so many machines.

I see, thanks for the update!

**Comment by jonathanmetzman** [comment]
> > I might have to undo the change to CI because while it does work well for adding new fuzzers, it works terribly for modifying core fuzzers like afl which every fuzzer depends on, since now these builds will be repeated on so many machines.
> 
> I see, thanks for the update!

Things may be less terrible after #1599

**Pull request merged**
