### PR TITLE
sbft-introspection

### PR DESCRIPTION
**Pull request by vanhauser-thc**

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@Alan32Liu 
can you please run the aflpp_introspection fuzzer
1) against all coverage benchmarks
2) against all bug benchmarks?
It is only one fuzzer but I guess this will take 4-5 days to complete.
Thank you!

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-03-13-intro-cov --fuzzers  aflpp_introspection -a

**Comment by vanhauser-thc** [comment]
thank you! :)

**Comment by Alan32Liu** [comment]
> thank you! :)

It seems the experiments were not launched due to unresolved conflict, sorry : )
I've fixed it and will try again now.

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-03-13-intro-bug --fuzzers aflpp_introspection --benchmarks arrow_arrow-ipc-stream-fuzz_1a34a0 aspell_aspell_fuzzer_e8eb74 assimp_assimp_fuzzer_4d451f bloaty_fuzz_target_52948c ffmpeg_ffmpeg_demuxer_fuzzer_7adeef file_magic_fuzzer_2d5f85 grok_grk_decompress_fuzzer_9cd001 harfbuzz_hb-shape-fuzzer_17863b lcms_cms_transform_all_fuzzer_97d37d libaom_av1_dec_fuzzer_6e1848 libpcap_fuzz_filter_98b0a2 libxml2_xml_e85b9b mbedtls_fuzz_dtlsclient_7c6b0e php_php-fuzz-parser_0dbedb systemd_fuzz-network-parser_288baf -a

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-03-13-intro-cov --fuzzers aflpp_introspection --benchmarks arduinojson_json_fuzzer assimp_assimp_fuzzer astc-encoder_fuzz_astc_physical_to_symbolic bloaty_fuzz_target botan_tls_server brotli_decode_fuzzer curl_curl_fuzzer_http double-conversion_string_to_double_fuzzer draco_draco_pc_decoder_fuzzer dropbear_fuzzer-postauth_nomaths firestore_firestore_serializer_fuzzer fmt_chrono-duration-fuzzer freetype2_ftfuzzer guetzli_guetzli_fuzzer harfbuzz_hb-shape-fuzzer icu_unicode_string_codepage_create_fuzzer jansson_json_load_dump_fuzzer jsoncpp_jsoncpp_fuzzer lcms_cms_transform_fuzzer libaom_av1_dec_fuzzer libcoap_pdu_parse_fuzzer libhevc_hevc_dec_fuzzer libjpeg-turbo_libjpeg_turbo_fuzzer libpcap_fuzz_both libpng_libpng_read_fuzzer librdkafka_fuzz_regex libxml2_xml libxslt_xpath mbedtls_fuzz_dtlsclient openh264_decoder_fuzzer openssl_x509 openthread_ot-ip6-send-fuzzer proj4_proj_crs_to_crs_fuzzer re2_fuzzer sqlite3_ossfuzz stb_stbi_read_fuzzer systemd_fuzz-link-parser vorbis_decode_fuzzer woff2_convert_woff2ttf_fuzzer zlib_zlib_uncompress_fuzzer -a

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-03-31-intro-bug --fuzzers aflpp_introspection --benchmarks arrow_arrow-ipc-stream-fuzz_1a34a0 aspell_aspell_fuzzer_e8eb74 assimp_assimp_fuzzer_4d451f bloaty_fuzz_target_52948c ffmpeg_ffmpeg_demuxer_fuzzer_7adeef file_magic_fuzzer_2d5f85 grok_grk_decompress_fuzzer_9cd001 harfbuzz_hb-shape-fuzzer_17863b lcms_cms_transform_all_fuzzer_97d37d libaom_av1_dec_fuzzer_6e1848 libpcap_fuzz_filter_98b0a2 libxml2_xml_e85b9b mbedtls_fuzz_dtlsclient_7c6b0e php_php-fuzz-parser_0dbedb systemd_fuzz-network-parser_288baf -a

**Pull request closed without merging**
