### PR TITLE
[SBST23] LearnPerfFuzz

### PR DESCRIPTION
**Pull request by somiha**

### CODE REVIEW

**Comment by Alan32Liu** [comment]
Hi @somiha, 
Just a gentle reminder that PR is due for a pre-run on AoE 17 Feb.
Please consider at least passing the presubmit and a few benchmark-building CIs so that the pre-run can give you some preliminary results.

Could I ask you to share the following information with us, please? The conference requires it from us by Wednesday (Feb 22):
1. Title of your paper, 
2. Affiliations,
3. Emails, 
4. Name and surnames of all authors,
5. The order of authors.

You might have answered some of them in the registration form, but we do want to confirm them before submitting them to the conference.
Feel free to reply to us here or via email (sbft23fuzzcomp@googlegroups.com).

**Comment by Alan32Liu** [comment]
Hi @somiha,
thanks for the submission!
Would you mind omitting the svg files in `test3` (assuming they are not required by your fuzzer)? Thanks!

**Comment by somiha** [comment]
I omit the test3 file then push it again. Then make a Pull Request. But the
CI test hasn't started yet.

**Comment by Alan32Liu** [comment]
> I omit the test3 file then push it again. Then make a Pull Request. But the CI test hasn't started yet.

They are running now.
Could you please provide [the information in my earlier comment](https://github.com/google/fuzzbench/pull/1620#issuecomment-1434047937)? Thanks!

**Comment by somiha** [comment]
Title: LearnPerfFuzz: Generating Pathological Inputs using Greybox Fuzzing
with Knowledge Enhancement

Affiliation: Department of Computer Science and Engineering, Faculty of
Engineering and Technology, Jashore University of Science and Tenchnology

Emails: ***@***.***
***@***.***
***@***.***

Name and surnames of Authors:

Dr. Syed Md. Galib
Professor, Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

Md. Shafiuzzaman
Assistant Professor, Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

Somiha Tasnim
Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

Orders of Authors:

1. Dr. Syed Md. Galib
Professor, Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

2. Md. Shafiuzzaman
Assistant Professor, Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

3. Somiha Tasnim
Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

**Comment by somiha** [comment]
I want to change the orders of authors.

**Comment by somiha** [comment]
Title: LearnPerfFuzz: Generating Pathological Inputs using Greybox Fuzzing
with Knowledge Enhancement

Affiliation: Department of Computer Science and Engineering, Faculty of
Engineering and Technology, Jashore University of Science and Tenchnology

Emails: ***@***.***
***@***.***
***@***.***

Name and surnames of Authors:

1. Somiha Tasnim
Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

2. Md. Shafiuzzaman
Assistant Professor, Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

3. Dr. Syed Md. Galib
Professor, Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

Orders of Authors:

1. Somiha Tasnim
Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

2. Md. Shafiuzzaman
Assistant Professor, Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

3. Dr. Syed Md. Galib
Professor, Computer Science and Engineering
Jashore University of Science and Technology
Jashore, Bangladesh

**Comment by somiha** [comment]
Short Tool Report

**Comment by Alan32Liu** [comment]
Hi, @somiha could you please avoid including files outside your fuzzer directory? For example, `a.out` and `experiment-config.yaml` in the current PR.
No worries this time, I've deleted them in #1737, but I would really appreciate it if you could exclude them from your PR before the final submission : )

**Pull request merged**
