### PR TITLE
[DO NOT MERGE] A standard experiment

### PR DESCRIPTION
**Pull request by Alan32Liu**
A standard coverage experiment and a bug-based one.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-12-07-standard

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-12-07-standard-bug --benchmarks bloaty_fuzz_target_52948c harfbuzz_hb-shape-fuzzer_17863b libxml2_xml_e85b9b mbedtls_fuzz_dtlsclient_7c6b0e php_php-fuzz-parser_0dbedb

**Comment by jonathanmetzman** [comment]
Thanks Dongge!

**Comment by Alan32Liu** [comment]
Experiment `2023-12-07-standard` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-12-07-standard/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-12-07-standard/index.html).

Experiment `2023-12-07-standard-bug` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-12-07-standard-bug/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-12-07-standard-bug/index.html).

**Pull request closed without merging**
