### PR TITLE
Add input models to fuzz Freetype2 and Vorbis

### PR DESCRIPTION
**Pull request by thuanpv**
Hi,

In this pull request, I add support for True/OpenType fonts and OGG files which are used by AFLSmart to fuzz Freetype2 and Vorbis, respectively.

Regards,

Thuan

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Thanks!

**Comment by thuanpv** [comment]
Thanks, Abhishek for approving the request. Actually, I have more input models than the 5 which are used currently to fuzz subjects in FuzzBench. However, I cannot use some of them (e.g., Zip, Pcap) because the subject doesn't come with syntactically seed inputs. It is related to this issue https://github.com/google/fuzzbench/issues/85.

**Comment by inferno-chromium** [comment]
@thuanpv - feel free to add seeds for those benchmarks as part of your PR.

**Comment by jonathanmetzman** [comment]
Note that there's no way currently to add seeds to OSS-Fuzz benchmarks.

**Pull request merged**
