### PR TITLE
Fix benchmark integration script

### PR DESCRIPTION
**Pull request by jonathanmetzman**
The previous model used a submodule that was never updated and thus the stuff copied from oss-fuzz repo was very old and generally not working. Change this to use the latest oss-fuzz clone.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @maxammann 
Related: https://github.com/google/fuzzbench/issues/1353

**Comment by jonathanmetzman** [comment]
This is blocking #1441

**Review by maxammann — APPROVED** [review]
That looks good to me! I was actually quite puzzled why there is a submodule :)

There is ofc never a guarantee that integration works. Most of the time only minior tweaks will be necessary I think.

Did not test this yet though.

**Comment by maxammann** [comment]
Like you said in Discord: It might be a good idea to remove this script. Most of the time this will not easily work. And frankly, without understanding what is going on, how benchmarks are built, which tools they use, just copying it is very dangerous.

I think it would be good to "force" users going the more complicated way of manually creating a new benchmark.

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
