### PR TITLE
new alf++ variants

### PR DESCRIPTION
**Pull request by vanhauser-thc**
sadly the last attempt failed twice.
As eager I want to see how good the LTO variant works out (the 2x 12h attempts already showed it should be the best), I rather want compete runs to test other features.

this this compares two things:
cmplog vs laf-intel vs laf-intel with a 2^17 map (because of many more map collisions with laf-intel)

and normal vs mopt vs mopt2 (mopt2 is normal + mopt)

So basically: please test all aflplusplus variants incl. the main "aflplusplus" one. thanks! (it is a different one than from the 2020-05-11 run)

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
> sadly the last attempt failed twice.

See my comments on https://github.com/google/fuzzbench/issues/286#issuecomment-630367637 about how the last attempt was't actually a failure.

**Comment by jonathanmetzman** [comment]
I started the experiment with all 7 AFL++ based fuzzers. But I don't really see what changed in aflplusplus_cmplog or aflplusplus.
Note that the compiler was updated since the last experiment if you need to compare them to the old results, let me know and I can try to figure out something to make this work.

**Comment by jonathanmetzman** [comment]
Sorry, I had to kill this experiment because I started the experiment using the wrong checkout (one which only contained AFL++ and _cmplog). I'll start a fresh one shortly.

>I can try to figure out something to make this work.

To clarify what I mean here, we can pin the clang version we take from OSS-Fuzz so there's much less that can majorly change between experiments.

**Comment by jonathanmetzman** [comment]
Restarted the experiment.

**Comment by vanhauser-thc** [comment]
> But I don't really see what changed in aflplusplus_cmplog or aflplusplus.

before they were using the classic map[prev >> 1 ^ cur] instrumentation, now they are using trace pc guard sanitizer. so faster and less collision.
basically "aflplusplus" is now the same as "afl" in the settings (which wasnt the case before)

**Comment by jonathanmetzman** [comment]
Ah sorry, didn't notice those changes came here: https://github.com/google/fuzzbench/commit/eb910871dc14d823dffa6aef024415eae9a2e01c

**Pull request merged**
