### PR TITLE
test afl++ classify changes

### PR DESCRIPTION
**Pull request by vanhauser-thc**
should result in a minor improvement.

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by vanhauser-thc** [comment]
this can be merged :)
thank you

**Comment by vanhauser-thc** [comment]
@inferno-chromium this run doesnt show up, but was merged 2 days ago. can you please have a look? thank you.

**Comment by inferno-chromium** [comment]
@oliverchang - can you please find an owner to debug fuzzbench service failure. similar one is https://github.com/google/fuzzbench/pull/1322. We should try to get new folks upto speed on fuzzbench failures or thoughts ?

**Comment by oliverchang** [comment]
Our new hire will work a bit on FuzzBench after ramping up. In the meantine, @jonathanmetzman could you please take a look at these?

**Pull request merged**
