### PR TITLE
Add a parallel fuzzer

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Based off of #1197

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @gtt1995

**Comment by gtt1995** [comment]
Hello
[https://github.com/google/fuzzbench/pull/1197#issuecomment-894618592](https://github.com/google/fuzzbench/pull/1197#issuecomment-894618592)

[https://github.com/google/fuzzbench/pull/1197#issuecomment-894619829](https://github.com/google/fuzzbench/pull/1197#issuecomment-894619829)

**Comment by gtt1995** [comment]
I think so too, and I am very looking forward to contributing this work to the community. I am preparing to request @morehouse to review this patch. Maybe he is on vacation recently and has not yet responded to me. The libfuzzer-fork strategy is also included in clusterfuzz.
I looked at the results of the experiment. There were three test subjects. There was no result from glibfuzzer. Which part was wrong?

**Comment by jonathanmetzman** [comment]
I don't have time to look into it. You can look at the logs in gs://fuzzbench-data/2021-08-05-parallel/experiment-folders/ to find out.
My guess is it crashed on those benchmarks.

**Comment by gtt1995** [comment]
Yes,it crashed.  
It may be a problem with glibfuzzer, it will encounter an error when facing an initial seed, I can fix it.
On the other hand, can you contact @morehouse for me, he has not replied to me yet.
Thanks.

**Pull request merged**
