### PR TITLE
Fix gcbrun trigger

### LINKED ISSUE #1897: Only trigger experiments when a comment starts with `/gcbrun`
Currently, a `GCB` experiment will be triggered if our comment **_mentions_** `/gcbrun`.

This is problematic because experiments will be launched unintendedly (e.g., when we quote previous `/gcb` commands, or even when we mention `/gcb` in any form).

## Root cause
1. `GCB` trigger simply [checks for `/gcb` without any constraints](https://pantheon.corp.google.com/cloud-build/triggers/edit/fff67372-9e94-4eeb-ab8c-4566ca73badf?project=fuzzbench). 
2. Our `gcbrun_experiment.py` [iterates all previous comments](https://github.com/google/fuzzbench/blob/56caa83e81bc59a1389367c6bd29d46fd35d03e6/service/gcbrun_experiment.py#L57) to find the latest valid `/gcb` command, which might have already been run.

## Proofs
1. [This example](https://github.com/google/fuzzbench/pull/1893#issuecomment-1716770892) quotes an old command and modifies its experiment name. However, it triggers an experiment with the old name, indicating we launch the latest valid experiment command.
2. [This example](https://github.com/google/fuzzbench/pull/1893#issuecomment-1716780709) includes a random `/gcb` command in the middle of the sentence. It also triggers the same old experiment, confirming the same conclusion.

## Propose fix
Change https://github.com/google/fuzzbench/blob/56caa83e81bc59a1389367c6bd29d46fd35d03e6/service/gcbrun_experiment.py#L56-L57
to
```python
 if not body.startswith(RUN_EXPERIMENT_COMMAND_STR): 
     return None 
```

## Justification
1. Based on our setting on Google Cloud, all `/gcb` commands will immediately trigger an experiment, there is no need to search back in history for an old command.
2. If we need to run an old command, we can always add a new comment for it.

@jonathanmetzman: Did I miss anything?
If it looks good to you, I will implement the fix proposed above.

### PR DESCRIPTION
**Pull request by Alan32Liu**
Fixes #1897

### CODE REVIEW

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-06-fix-gcb --fuzzers afl --benchmark libxml2_xml

**Comment by Alan32Liu** [comment]
Testing launching exp with the comment above, will test some other cases once it launches successfully.

**Comment by Alan32Liu** [comment]
Experiment `2023-09-06-fix-gcb` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-09-06-fix-gcb/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-09-06-fix-gcb/index.html).

**Comment by Alan32Liu** [comment]
> /gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-06-fix-gcb --fuzzers afl --benchmark libxml2_xml

This comment should not trigger any experiment now.

**Comment by Alan32Liu** [comment]
> This comment should not trigger any experiment now.

Oh, it did. Maybe we should merge this PR to make it take effect?

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-06-fix-gcb-1 --fuzzers afl --benchmark libxml2_xml

**Comment by Alan32Liu** [comment]
Experiment `2023-09-06-fix-gcb-1` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-09-06-fix-gcb-1/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-09-06-fix-gcb-1/index.html).

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-06-fix-gcb-2 --fuzzers afl --benchmark libxml2_xml

**Comment by Alan32Liu** [comment]
Experiment `2023-09-06-fix-gcb-2` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-09-06-fix-gcb-2/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-09-06-fix-gcb-2/index.html).

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-06-fix-gcb-2 --fuzzers afl --benchmark libxml2_xml

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-06-fix-gcb-2 --fuzzers afl --benchmark libxml2_xml

**Comment by Alan32Liu** [comment]
> /gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-06-fix-gcb-2 --fuzzers afl --benchmark libxml2_xml

This should not start an exp.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
