### PR TITLE
afl++ support for bug benchmarks

### PR DESCRIPTION
**Pull request by vanhauser-thc**
when UBSAN is activated this results in a huge increase in compile time.
I have a theory why this could be, but no clue how to resolve this.
So for bug benchmarks we switch back to lame clang -fsanitize=coverage... :(
but this will just degrade exec/s and none of the features.

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]
Thank you so much for fix, i guess you will request experiment in another run. E.g. see https://www.fuzzbench.com/reports/2020-12-08-bug/index.html

**Comment by vanhauser-thc** [comment]
this is still WIP ...  a few things a still not working... working on that. :)

**Comment by inferno-chromium** [comment]
> this is still WIP ... a few things a still not working... working on that. :)

No worries, take your time, it is exciting!

**Comment by vanhauser-thc** [comment]
OK I do not get it.
the bug benchmark that is going wrong with afl++ is php-fuzz-execute - and it fails because UBSAN is triggered already in LLVMFuzzerInitialize():

```
#5  0x00000000004ea50c in handleNegateOverflowImpl ()
    at /src/llvm-project/compiler-rt/lib/ubsan/ubsan_handlers.cpp:272
#6  0x00000000004ea2aa in __ubsan_handle_negate_overflow ()
    at /src/llvm-project/compiler-rt/lib/ubsan/ubsan_handlers.cpp:277
#7  0x0000000000eb5f5b in zend_hash_real_init_mixed_ex (
    ht=0x2961b60 <sapi_globals+448>) at Zend/zend_hash.c:169
#8  0x0000000000ebf25f in _zend_hash_add_or_update_i (
    ht=0x2961b60 <sapi_globals+448>, ht@entry=0x7fffffffe120, 
    key=0x6060000000e0, key@entry=0x21, pData=0x7fffffffe100, 
    pData@entry=0x7fffffffe0e0, flag=flag@entry=2) at Zend/zend_hash.c:735
#9  0x0000000000ebea72 in zend_hash_add (ht=0x79, key=0x79, 
    key@entry=0x6060000000e0, pData=0x6) at Zend/zend_hash.c:896
#10 0x0000000000c96068 in zend_hash_add_mem (key=0x6060000000e0, 
    pData=0x1bdfec0 <php_post_entries>, size=32, ht=<optimized out>)
    at Zend/zend_hash.h:687
#11 sapi_register_post_entry (post_entry=<optimized out>) at main/SAPI.c:944
#12 0x0000000000c95da6 in sapi_register_post_entries (
    post_entries=<optimized out>) at main/SAPI.c:926
#13 0x0000000000ca0699 in php_setup_sapi_content_types ()
    at main/php_content_types.c:56
#14 0x0000000000c90533 in sapi_globals_ctor (sapi_globals=<optimized out>)
    at main/SAPI.c:58
#15 sapi_startup (sf=sf@entry=0x8) at main/SAPI.c:81
#16 0x000000000124a211 in fuzzer_init_php () at sapi/fuzzer/fuzzer-sapi.c:138
#17 0x000000000124a17d in LLVMFuzzerInitialize (
    argc=argc@entry=0x7fffffffe224, argv=argv@entry=0x7fffffffe228)
    at sapi/fuzzer/fuzzer-execute.c:70
#18 0x000000000134d583 in main (argc=1, argv=0x7fffffffe378)
    at aflpp_driver.c:269
```
so IMHO this is a bad setup that needs to be fixed, and not an issue in afl++

**Comment by inferno-chromium** [comment]
> OK I do not get it.
> the bug benchmark that is going wrong with afl++ is php-fuzz-execute - and it fails because UBSAN is triggered already in LLVMFuzzerInitialize():
> 
> ```
> #5  0x00000000004ea50c in handleNegateOverflowImpl ()
>     at /src/llvm-project/compiler-rt/lib/ubsan/ubsan_handlers.cpp:272
> #6  0x00000000004ea2aa in __ubsan_handle_negate_overflow ()
>     at /src/llvm-project/compiler-rt/lib/ubsan/ubsan_handlers.cpp:277
> #7  0x0000000000eb5f5b in zend_hash_real_init_mixed_ex (
>     ht=0x2961b60 <sapi_globals+448>) at Zend/zend_hash.c:169
> #8  0x0000000000ebf25f in _zend_hash_add_or_update_i (
>     ht=0x2961b60 <sapi_globals+448>, ht@entry=0x7fffffffe120, 
>     key=0x6060000000e0, key@entry=0x21, pData=0x7fffffffe100, 
>     pData@entry=0x7fffffffe0e0, flag=flag@entry=2) at Zend/zend_hash.c:735
> #9  0x0000000000ebea72 in zend_hash_add (ht=0x79, key=0x79, 
>     key@entry=0x6060000000e0, pData=0x6) at Zend/zend_hash.c:896
> #10 0x0000000000c96068 in zend_hash_add_mem (key=0x6060000000e0, 
>     pData=0x1bdfec0 <php_post_entries>, size=32, ht=<optimized out>)
>     at Zend/zend_hash.h:687
> #11 sapi_register_post_entry (post_entry=<optimized out>) at main/SAPI.c:944
> #12 0x0000000000c95da6 in sapi_register_post_entries (
>     post_entries=<optimized out>) at main/SAPI.c:926
> #13 0x0000000000ca0699 in php_setup_sapi_content_types ()
>     at main/php_content_types.c:56
> #14 0x0000000000c90533 in sapi_globals_ctor (sapi_globals=<optimized out>)
>     at main/SAPI.c:58
> #15 sapi_startup (sf=sf@entry=0x8) at main/SAPI.c:81
> #16 0x000000000124a211 in fuzzer_init_php () at sapi/fuzzer/fuzzer-sapi.c:138
> #17 0x000000000124a17d in LLVMFuzzerInitialize (
>     argc=argc@entry=0x7fffffffe224, argv=argv@entry=0x7fffffffe228)
>     at sapi/fuzzer/fuzzer-execute.c:70
> #18 0x000000000134d583 in main (argc=1, argv=0x7fffffffe378)
>     at aflpp_driver.c:269
> ```
> 
> so IMHO this is a bad setup that needs to be fixed, and not an issue in afl++

Can you try adding
env['UBSAN_OPTIONS']='silence_unsigned_overflow=1'
in this branch
https://github.com/google/fuzzbench/blob/master/fuzzers/utils.py#L190

this stuff we disable in oss-fuzz, https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L105

i think if you add that, then CI should come out green. thoughts?

**Comment by vanhauser-thc** [comment]
with the env var it works. where would I need to add this to the PR so it affects all fuzzers? it is a runtime env var.

**Comment by vanhauser-thc** [comment]
In experiment/measurer/sanitizer.py it says:

```
ADDITIONAL_UBSAN_OPTIONS = {
    'allocator_release_to_os_interval_ms': 500,
    'print_stacktrace': 1,
    'silence_unsigned_overflow': 1,
}
```

however this does not end up in the fuzzing env vars:

```
environ({'OUTPUT_CORPUS_DIR': '/out/corpus', 'HOSTNAME': 'e016c214d5a1', 'OUT': '/out', 'RUNNER_NICENESS': '-5', 'LD_LIBRARY_PATH': ':/out', 'WORKDIR': '/out', 'MAX_TOTAL_TIME': '20', 'AFL_SKIP_CPUFREQ': '1', 'PYTHON_VERSION': '3.8.6', 'ROOT_DIR': '/src', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/out', 'FUZZ_OUTSIDE_EXPERIMENT': '1', 'PWD': '/out', 'FUZZER': 'aflplusplus_optimal', 'TRIAL_ID': '1', 'SEED_CORPUS_DIR': '/out/seeds', 'SHLVL': '1', 'HOME': '/root', 'AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES': '1', 'PYTHONPATH': '/src', 'FORCE_LOCAL': '1', 'BENCHMARK': 'php_php-fuzz-execute', 'FUZZ_TARGET': 'php-fuzz-execute', 'AFL_MAP_SIZE': '1048576', 'SNAPSHOT_PERIOD': '10', '_': '/usr/bin/nice', 'LC_CTYPE': 'C.UTF-8'})
```

so I think this is a bug?

**Comment by vanhauser-thc** [comment]
also symbolize=1 and print_stacktrace=1 is great for debugging an issue, however is very bad for the fuzzing performance.

**Comment by inferno-chromium** [comment]
> In experiment/measurer/sanitizer.py it says:
> 
> ```
> ADDITIONAL_UBSAN_OPTIONS = {
>     'allocator_release_to_os_interval_ms': 500,
>     'print_stacktrace': 1,
>     'silence_unsigned_overflow': 1,
> }
> ```
> 
> however this does not end up in the fuzzing env vars:
> 
> ```
> environ({'OUTPUT_CORPUS_DIR': '/out/corpus', 'HOSTNAME': 'e016c214d5a1', 'OUT': '/out', 'RUNNER_NICENESS': '-5', 'LD_LIBRARY_PATH': ':/out', 'WORKDIR': '/out', 'MAX_TOTAL_TIME': '20', 'AFL_SKIP_CPUFREQ': '1', 'PYTHON_VERSION': '3.8.6', 'ROOT_DIR': '/src', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/out', 'FUZZ_OUTSIDE_EXPERIMENT': '1', 'PWD': '/out', 'FUZZER': 'aflplusplus_optimal', 'TRIAL_ID': '1', 'SEED_CORPUS_DIR': '/out/seeds', 'SHLVL': '1', 'HOME': '/root', 'AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES': '1', 'PYTHONPATH': '/src', 'FORCE_LOCAL': '1', 'BENCHMARK': 'php_php-fuzz-execute', 'FUZZ_TARGET': 'php-fuzz-execute', 'AFL_MAP_SIZE': '1048576', 'SNAPSHOT_PERIOD': '10', '_': '/usr/bin/nice', 'LC_CTYPE': 'C.UTF-8'})
> ```
> 
> so I think this is a bug?

Yes it is, will fix tmrw, ooo today - https://github.com/google/fuzzbench/issues/994

**Pull request merged**
