### PR TITLE
Add RUSTFLAGS to LibAFL fuzzers

### PR DESCRIPTION
**Pull request by tokatoka**
This will make rust compiler build more optimized code

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @andreafioraldi

**Comment by tokatoka** [comment]
Can we merge this?

**Comment by jonathanmetzman** [comment]
CC @vanhauser-thc

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by vanhauser-thc** [comment]
I am not sure this is a good idea.
How oss-fuzz works is that it builds the package for fuzzing and then clusterfuzz fuzzes that package. however these are usually different machines.
so if oss-fuzz optimizes for the CPU oss-fuzz is building the packages, this an break when run on clusterfuzz - or just have a bit worse performance if lucky.

**Comment by jonathanmetzman** [comment]
This is in fuzzbench. But yeah, good point.

**Comment by jonathanmetzman** [comment]
I'm going to have to revert this.

**Comment by vanhauser-thc** [comment]
Ah did this on my phone and thought it is oss-fuzz :-D
We ran into this issue when ppl downloaded our docker container and the chip there was older than where it was built.

**Comment by tokatoka** [comment]
no no, this is fuzzbench 😢

**Pull request merged**
