### PR TITLE
Libafl forkserver test

### PR DESCRIPTION
**Pull request by andreafioraldi**
Recently, we added the support to run AFL++ binaries in LibAFL with CmpLog and shmem inputs.
With this PR, I'm requesting a bug-based benchmark (as the advantage of the forkserver is reliability even when the target is crashing often) to test if the Rust implementation matches the original C version of AFL++ in code and bug coverage.

Related to this, https://github.com/google/fuzzbench/issues/1584

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Bug based benchmarks is extremely broken now.

**Comment by andreafioraldi** [comment]
> Bug based benchmarks is extremely broken now.

Every benchmark? Just 2 or 3 would be fine.

presubmit doesn't fail locally and it seems to fail a test that is (probably) unrelated to my PR.

**Comment by andreafioraldi** [comment]
Do you know the last working commit? At least I can rebase on it and run on a subset of the programs locally

**Comment by jonathanmetzman** [comment]
Do you want to run this now? I think we're in better shape

**Comment by andreafioraldi** [comment]
> Do you want to run this now? I think we're in better shape

No for a strange reason some benchmarks don't build with afl++ under libafl_forkserver, I'm trying to figure out why, I'll remove the draft mark when ready

**Pull request merged**
