### PR TITLE
Integrate project mysql-server with target fuzz_real_query

### PR DESCRIPTION
**Pull request by Vaush**

### CODE REVIEW

**Review by inferno-chromium — CHANGES_REQUESTED** [review]
Something up with boost:

```
#19 3.705 -- cd /src/mysql-server/build; tar xfz /src/mysql-server/build/boost_1_70_0.tar.gz
#19 8.605 cmake -E tar: warning: unknown warning
#19 8.605 cmake -E tar: warning: unknown warning
#19 8.605 cmake -E tar: warning: unknown warning
#19 8.605 cmake -E tar: warning: unknown warning
#19 8.605 cmake -E tar: warning: unknown warning
#19 8.606 cmake -E tar: warning: unknown warning
#19 8.606 cmake -E tar: warning: unknown warning
#19 8.606 cmake -E tar: warning: unknown warning
#19 8.606 cmake -E tar: warning: unknown warning
#19 8.606 cmake -E tar: warning: unknown warning
#19 8.606 cmake -E tar: warning: unknown warning
#19 8.607 cmake -E tar: warning: unknown warning
#19 8.607 cmake -E tar: warning: unknown warning
#19 8.607 cmake -E tar: warning: unknown warning
#19 8.607 CMake Error: Problem with archive_write_header(): Can't create 'boost_1_70_0/libs/beast/test/extern/zlib-1.2.11/amiga'
#19 8.607 CMake Error: Current file: boost_1_70_0/libs/beast/test/extern/zlib-1.2.11/amiga/
#19 8.621 CMake Error: Problem extracting tar: /src/mysql-server/build/boost_1_70_0.tar.gz
#19 8.622 CMake Error at cmake/boost.cmake:252 (MESSAGE):
#19 8.622   Giving up.
#19 8.622 Call Stack (most recent call first):
#19 8.622   CMakeLists.txt:1002 (INCLUDE)
#19 8.622 
#19 8.622 
#19 8.622 -- WITH_BOOST /src/mysql-server/build.
#19 8.622 -- Failed to extract files.
#19 8.622    Please try downloading and extracting yourself.
#19 8.622    The url is: https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
#19 8.622 -- Configuring incomplete, errors occurred!
#19 8.622 See also "/src/mysql-server/build/CMakeFiles/CMakeOutput.log".
#19 8.629 Traceback (most recent call last):
#19 8.629   File "<string>", line 1, in <module>
#19 8.629   File "/src/fuzzers/aflsmart/fuzzer.py", line 25, in build
#19 8.629     afl_fuzzer.build()
#19 8.629   File "/src/fuzzers/afl/fuzzer.py", line 40, in build
#19 8.630     utils.build_benchmark()
#19 8.630   File "/src/fuzzers/utils.py", line 68, in build_benchmark
#19 8.630     subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
#19 8.630   File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
#19 8.630     raise CalledProcessError(retcode, cmd)
#19 8.630 subprocess.CalledProcessError: Command '['/bin/bash', '-ex', '/src/build.sh']' returned non-zero exit status 1.
#19 ERROR: executor failed running [/bin/sh -c PYTHONPATH=$SRC python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.$FUZZER import fuzzer; fuzzer.build()"]: runc did not terminate sucessfully```

**Comment by Vaush** [comment]
@inferno-chromium what is the space limit for checks? I believe mysql-server is running out of space

**Comment by inferno-chromium** [comment]
> @inferno-chromium what is the space limit for checks? I believe mysql-server is running out of space

i think it is around ~25gb (https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources we do cleanup their images to claim another 10 gb). Can you remove the unneeded fuzzers from build.sh+Cmakelists file and see if that helps ?

**Comment by Vaush** [comment]
I'll see how much I can trim, but I do know that it takes a lot of space, it crashed my vm twice.

**Comment by inferno-chromium** [comment]
Not fixable.

**Pull request closed without merging**
