### PR TITLE
new afl++ experiment

### PR DESCRIPTION
**Pull request by vanhauser-thc**
last run showed a regression, this benchmark checks if there really is one, and if yes, where.
the is a required run before I can update oss-fuzz for a few afl++ fixes.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
can be merged, the variants all built :)

**Comment by vanhauser-thc** [comment]
@jonathanmetzman the experiment seems to be stuck, there is no progress in the report for several hours now :(
https://www.fuzzbench.com/reports/experimental/2021-11-26-aflpp/index.html

**Comment by jonathanmetzman** [comment]
Sorry about that.
I'll take a look after I've fixed https://github.com/google/oss-fuzz/issues/6755 and https://github.com/google/fuzzbench/issues/1290

**Comment by jonathanmetzman** [comment]
I can't see anything obviously wrong.
Fuzzbench seems to still be measuring an entropic trial. My guess is there is some kind of pathlogical bottleneck that will resolve itself.

**Comment by jonathanmetzman** [comment]
Yeah looks like it unfroze

**Pull request merged**
