### PR TITLE
[SBFT23] libafl_libfuzzer

### PR DESCRIPTION
**Pull request by VTCAKAVSMoACE**

### CODE REVIEW

**Comment by Alan32Liu** [comment]
Congratulations!
We are pleased to inform you that your submission based on your past publication has been accepted by the _fuzzing competition of The 16th Intl. Workshop on Search-Based and Fuzz Testing_ on 14 May 2023, Melbourne, Australia.

We invite you to submit your fuzzer via this pull request (PR) by **17 Feb 2023 AoE** and email us your camera-ready tool report by **10 Mar 2023 AoE**. Please ensure your PR is always up-to-date and compatible with the master branch of FuzzBench before your submission. More information about the key dates and submission requirements can be found on [our website](https://sbft23.github.io/tools/fuzzing).

If you have any questions or concerns, please do not hesitate to contact us.

**Comment by Alan32Liu** [comment]
Hi @VTCAKAVSMoACE,

Could I ask you to share the following information with us, please? The conference requires it from us by Wednesday (Feb 22):
1. Title of your paper, 
2. Affiliations,
3. Emails, 
4. Name and surnames of all authors,
5. The order of authors.

You might have answered some of them in the registration form, but we do want to confirm them before submitting them to the conference.
Feel free to reply to us here or via email (sbft23fuzzcomp@googlegroups.com).

**Comment by VTCAKAVSMoACE** [comment]
Hey @Alan32Liu!

1. `libafl_libfuzzer: libfuzzer on top of libafl`
2. CISPA, EURECOM, Google Inc., The University of Tokyo
3. addison.crump@cispa.de, fioraldi@eurecom.fr, dmnk@google.com, toka@aflplus.plus
4. Addison Crump, Andrea Fioraldi, Dominik Maier, Dongjia Zhang
5. As above.

Thanks!

**Comment by Alan32Liu** [comment]
> Hey @Alan32Liu!
> 
> 1. `libafl_libfuzzer: libfuzzer on top of libafl`
> 2. CISPA, EURECOM, Google Inc., The University of Tokyo
> 3. [addison.crump@cispa.de](mailto:addison.crump@cispa.de), [fioraldi@eurecom.fr](mailto:fioraldi@eurecom.fr), [dmnk@google.com](mailto:dmnk@google.com), [toka@aflplus.plus](mailto:toka@aflplus.plus)
> 4. Addison Crump, Andrea Fioraldi, Dominik Maier, Dongjia Zhang
> 5. As above.
> 
> Thanks!

Thanks, @VTCAKAVSMoACE !
Your CI tests are running.
Please come back later to check their status : )

**Comment by VTCAKAVSMoACE** [comment]
@Alan32Liu I'm not understanding what's causing my presubmit CI job to fail. Do you have any insight?

**Comment by Alan32Liu** [comment]
> Details

`presubmit` failed to format and lint issues:
```
================ 287 passed, 17 skipped, 34 warnings in 15.60s =================
Code is not formatted correctly, please run 'make format'
ERROR: format failed, see errors above.
ERROR: lint failed, see errors above.
Failed checks: format lint
Failed.
make: *** [Makefile:60: presubmit] Error 1
Error: Process completed with exit code 2.
```

In short, you can run `make format` locally to automatically format your code and `make lint` to show the linting errors.

Before that, you will need to follow [`the prerequisite section of our doc`](https://google.github.io/fuzzbench/getting-started/prerequisites/) if you have not done so.
After that, you can run `make presubmit` to run the same `presubmit` tests locally and [follow this](https://google.github.io/fuzzbench/getting-started/adding-a-new-fuzzer/#testing-it-out) to test your fuzzer on a specific benchmark program.

**Comment by VTCAKAVSMoACE** [comment]
Okay; thank you for the information. I'm running into new problems with weak symbols in some of the fuzzers overriding my entrypoints that I'm trying to resolve now, but I'll let you know when these issues are fixed.

**Comment by VTCAKAVSMoACE** [comment]
Okay, I checked the presubmit and (I believe) all the fuzzers correctly link now. Bit finicky because of this -Wl,--whole-archive nonsense, but I tested it with several failing cases and I'm fairly confident.

**Comment by VTCAKAVSMoACE** [comment]
Failing some of the tests because my fuzzer (after my linker changes) doesn't cleanly recover from crashes. This is okay for initial evaluation, I'll simply fix it for the second round.

**Comment by Alan32Liu** [comment]
> Failing some of the tests because my fuzzer (after my linker changes) doesn't cleanly recover from crashes. This is okay for initial evaluation, I'll simply fix it for the second round.

Sure, no problem!
Would you please update your branch by merging the master branch to here? Thanks!

**Pull request merged**
