### PR TITLE
Always define FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION

### LINKED ISSUE #1300: `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` discarded
It seems that the value of `CFLAGS` set in the builders is discarded while building the benchmarks using the appropriate `fuzzer.py` file. The discard happens here, it would seem:
https://github.com/google/fuzzbench/blob/d156b3579fe882b46fb65ab3f2bc9a5c5aeb3308/fuzzers/utils.py#L179-L180

The value of `CFLAGS` set in the builders contains `-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`, which is thus discarded while building. Discarding this value makes at least `libxslt_xpath` and `libxml2_libxml2_xml_reader_for_file_fuzzer` compile with features that make executions non-deterministic. Other benchmarks may be affected.

### PR DESCRIPTION
**Pull request by EliaGeretto**
This PR makes sure that `-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is always present in `CFLAGS` and `CXXFLAGS` when building benchmarks. At least two benchmarks (`libxslt_xpath`, `libxml2_libxml2_xml_reader_for_file_fuzzer`) rely on this behavior, which is present in OSS-Fuzz.

This PR fixes #1300.

### CODE REVIEW

**Comment by EliaGeretto** [comment]
Ah, I broke a couple of tests. I will fix them immediately.

**Comment by EliaGeretto** [comment]
The `presubmit` tests are now passing, the other failures seem to be unrelated to my change.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
Thanks!

**Pull request merged**
