### PR TITLE
Fix ffmpeg build failure by not specifying depth

### LINKED ISSUE #1434: Benchmark `ffmpeg_ffmpeg_demuxer_fuzzer` fails to build.
temp_visual = Xmallocarray(n_visual, sz_VisualID32);
                      ^
./reallocarray.h:44:32: note: expanded from macro 'Xmallocarray'
#define Xmallocarray(n, size)           Xreallocarray(NULL, (n), (size))
                                        ^
./reallocarray.h:39:5: note: expanded from macro 'Xreallocarray'
    reallocarray((ptr), ((n) == 0 ? 1 : (n)), size)
    ^
XEVI.c:150:14: warning: incompatible integer to pointer conversion assigning to 'VisualID32 *' (aka 'unsigned int *') from 'int' [-Wint-conversion]
        temp_visual = Xmallocarray(n_visual, sz_VisualID32);

This was caused by a commit to a dependency (`libXert`) and was temporarily fixed by reverting to one commit earlier (d965a1a8ce9331d2aaf1c697a29455ad55171b36) in #1419.
Now that they pushed another commit in `libXert` and still did not fix this error.

Given this benchmark is not used in experiments, maybe we could remove it (from CI tests)?

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Fixes #1434

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @andreafioraldi

**Comment by jonathanmetzman** [comment]
CC @andreafioraldi

**Review by Alan32Liu — APPROVED** [review]
LGTM, but how do we know if they will have fixed that in future commits?

**Comment by jonathanmetzman** [comment]
> LGTM, but how do we know if they will have fixed that in future commits?

Frankly we should be pinning all of these dependencies. Otherwise one fuzzer could be building a benchmark with one version of th ecode and another benchmark could be using a different version

**Pull request merged**
