### PR TITLE
[CI] Upgrade python environment action to silence warnings

### PR DESCRIPTION
**Pull request by jonathanmetzman**
This upgrades the versions of github actions we use to setup the python environment.
Using the old action results in these warnings: https://github.com/google/fuzzbench/actions/runs/304779767
More details here: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I'm still getting these warnings. GIthub's warnings are terrible and I can't figure out what they are trying to say.

**Comment by jonathanmetzman** [comment]
OK pretty sure it is complaining about "Setup Python environment"

**Review by inferno-chromium — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
Sorry this isn't really ready for landing yet.

**Review by inferno-chromium — APPROVED** [review]
LGTM

**Pull request merged**
