### PR TITLE
Remove afl deterministic fuzzer (default, without -d).

### PR DESCRIPTION
**Pull request by inferno-chromium**
The default deterministic mode shows overall bad performance
in vanilla AFL fuzzer and its fuzzer variants (e.g. AFLSmart).
Now, deprecating it.
See results in
https://www.fuzzbench.com/reports/2020-03-19/index.html

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Didn't bother modifying dict stuff in afl deterministic in https://github.com/google/fuzzbench/pull/149, i think we are ready to remove this fuzzer variant.

**Comment by lszekeres** [comment]
+1 on adding it back as a "config", once we have config support.

**Comment by jonathanmetzman** [comment]
> +1 on adding it back as a "config", once we have config support.

Heh, will be hard since configs are usually meant to add flags not remove them.

**Comment by lszekeres** [comment]
> Heh, will be hard since configs are usually meant to add flags not remove them.
Hm, that doesn't sound ideal. How about having a design doc/discussion for supporting configs some time?

**Pull request merged**
