### PR TITLE
Upgrade curl, bloaty benchmarks for clang source code coverage.

### PR DESCRIPTION
**Pull request by inferno-chromium**
Fixes https://github.com/google/fuzzbench/issues/590

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Do we have any data on running an experiment with this new OSS-Fuzz benchmark system? The experiments I ran before were wrong, and it would be nicer to have that before making this change (and especially before landing #584)

**Comment by inferno-chromium** [comment]
> Do we have any data on running an experiment with this new OSS-Fuzz benchmark system? The experiments I ran before were wrong, and it would be nicer to have that before making this change (and especially before landing #584)

Yes it works, see http://commondatastorage.googleapis.com/fuzzbench-reports/aarya-2020-07-27/index.html that is run only for bloaty and curl. And see the old one that fails - http://commondatastorage.googleapis.com/fuzzbench-reports/aarya-2020-07-26/index.html

**Comment by jonathanmetzman** [comment]
> > Do we have any data on running an experiment with this new OSS-Fuzz benchmark system? The experiments I ran before were wrong, and it would be nicer to have that before making this change (and especially before landing #584)
> 
> Yes it works, see http://commondatastorage.googleapis.com/fuzzbench-reports/aarya-2020-07-27/index.html that is run only for bloaty and curl. And see the old one that fails - http://commondatastorage.googleapis.com/fuzzbench-reports/aarya-2020-07-26/index.html

Yes but this is incomplete and uses the new coverage. Still, the trend isn't good because now mopt is in first place which would mean one of our changes is affecting the benchmarking results. That doesn't mean the new results are wrong and the old ones right but isn't great for fuzzbench.

**Comment by Shadoom7** [comment]
LGTM!

**Pull request merged**
