### PR TITLE
Remove items that only contain space in gcb commands

### PR DESCRIPTION
**Pull request by Alan32Liu**
Fixes a known issues that affects many experiment requests, e.g., [this one](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/b1915f08-70ac-4321-ae45-38b45da07e70;step=1?project=fuzzbench) in #1859.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-06-13-space --fuzzers libfuzzer         hongfuzz

**Comment by Alan32Liu** [comment]
Intentionally added redundant spaces between fuzzers to check if they are removed as expected.

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-06-13-space-1 --fuzzers libfuzzer    honggfuzz

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
I wouldn't run an experiment for this in the future. If it's broken we will notice right away

**Comment by Alan32Liu** [comment]
> I wouldn't run an experiment for this in the future. If it's broken we will notice right away

Ah sorry, I was not intended to leave the experiment running.
I only wanted to use the GCB to verify that the extra spaces I added between `libfuzzer` and `honggfuzz` won't affect the experiment like in #1859 (the spaces are only visible if you *edit* my comment).

The experiment has been terminated now : )

**Pull request merged**
