### PR TITLE
Dd

### PR DESCRIPTION
**Pull request by elManto**
New experiment comparing different instrumentations against a new version of afldd

### CODE REVIEW

**Comment by elManto** [comment]
The checks failed because of https://github.com/google/fuzzbench/issues/1240 . Please, re-run the checks when the issue is fixed

**Comment by elManto** [comment]
@jonathanmetzman for my experiment I only need afldd (that works locally and runs out of time in the CI) and aflpp_vs_dd (that works also in the CI). The other fuzzers that don't work are not needed for my evaluation. Could you please merge this and run the experiments, since I need it for a paper submission?

**Comment by elManto** [comment]
@jonathanmetzman is it possible to merge this ? The two fuzzers that I want to test build correctly and I have a deadline for a paper

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman is it possible to merge this ? The two fuzzers that I want to test build correctly and I have a deadline for a paper

Really sorry I didn't notice this earlier.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by elManto** [comment]
No worries, thanks

**Pull request merged**
