### PR TITLE
[test] local end to end test on pull request

### PR DESCRIPTION
**Pull request by zchcai**
## Description

The end-to-end test for local running.
We check whether a local run can generate report and experimental data within a time limit.

## Motivation and Context

This test is required for local support related pull request handling. Related to #251 and #444.

### CODE REVIEW

**Comment by zchcai** [comment]
We may also put this test under ./experiment/test*. But I guess this is more general than a unit test, where ./experiment/test* is more of a place for unit test.

**Comment by jonathanmetzman** [comment]
Didn't we discuss how this should be written as a unittest?

**Comment by zchcai** [comment]
> Didn't we discuss how this should be written as a unittest?

Yes we mentioned that offline.

**Comment by zchcai** [comment]
Some discussion offline. Maybe it will be better to provide another check as `make local-integration` to do future integration end-to-end tests, which is separate with current unit test check in `make presubmit` and is not required when submitting a PR.
@jonathanmetzman @lszekeres  any other comments?

**Comment by jonathanmetzman** [comment]
I want it to be a test so that has a familiar interface for using locally. But we will also run it on PRs.

**Comment by zchcai** [comment]
> I want it to be a test so that has a familiar interface for using locally. But we will also run it on PRs.
Right. I will create another PR for this feature.

**Pull request closed without merging**
