### PR TITLE
Orchesctra: A Collaborative Fuzzer Framework

### PR DESCRIPTION
**Pull request by gtt1995**
#1859 

Hello dongge,
@Alan32Liu 
I've improved my fuzzer framework based on the data from the last experiment, and it's time to reopen this experiment.
Other than that, to avoid duplicating the experiment overhead, I've only submitted the necessary fuzzers, so please review it and get it running.

Best regards,
Taotao.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
OK, just to be extra safe, would it be alright if we split them into the following two groups and run them separately?
Group 1:
```
- orchestra_236
- orchestra_339
- orchestra_4310
- orchestra_219
- orchestra_116
```
Group 2:
```
- orchestra_aflplusplus
- orchestra_honggfuzz
- orchestra_libfuzzer
- pastis
```

If you'd like to see their result in one table, we can download the raw CSV data (`data.csv.gz`) from the end of the report, which can be used to regenerate the combined report with selected fuzzers and benchmarks.

**Comment by Alan32Liu** [comment]
(future note for myself)
The commands are:
```bash
gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-25 --fuzzers orchestra_236 orchestra_339 orchestra_4310 orchestra_219 orchestra_116
```

```
gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-25 --fuzzers orchestra_aflplusplus orchestra_honggfuzz orchestra_libfuzzer pastis
```

**Comment by Alan32Liu** [comment]
BTW, just a minor future request if it is not too much trouble:
Instead of editing `service/experiment-requests.yaml`, would there be any chance that I could invite you to write the experiment request in [this format](https://github.com/google/fuzzbench/pull/1866#issuecomment-1681565046)?
You can swap the `--experiment-name` and `--fuzzers` parameters with your values.
I would really appreciate that : )

The file `service/experiment-requests.yaml` was no longer used to trigger experiments, as it requires merging PRs.
The new way (via `gcbrun` comments) allows us to run experiments and modify code multiple times on the same PR for better maintenance. I believe this improvement will benefit both of us.

My comment above is another example of this : )

**Comment by gtt1995** [comment]
I totally agree with you, dongge. 😄



---Original---
From: "Dongge ***@***.***&gt;
Date: Tue, Sep 26, 2023 08:31 AM
To: ***@***.***&gt;;
Cc: "taotao ***@***.******@***.***&gt;;
Subject: Re: [google/fuzzbench] Orchesctra: A Collaborative Fuzzer Framework(PR #1904)




 
OK, just to be extra safe, would it be alright if we split them into the following two groups and run them separately?
 Group 1:
 - orchestra_236 - orchestra_339 - orchestra_4310 - orchestra_219 - orchestra_116  
Group 2:
 - orchestra_aflplusplus - orchestra_honggfuzz - orchestra_libfuzzer - pastis  
If you'd like to see their result in one table, we can download the raw CSV data (data.csv.gz) from the end of the report, which can be used to regenerate the combined report with selected fuzzers and benchmarks.

**Comment by gtt1995** [comment]
gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-25-orchestra-1 --fuzzers orchestra_236 orchestra_339 orchestra_4310 orchestra_219 orchestra_116

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-25-orchestra-1 --fuzzers orchestra_236 orchestra_339 orchestra_4310 orchestra_219 orchestra_116

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-27-orchestra-1 --fuzzers orchestra_116 orchestra_216 orchestra_236 orchestra_339 orchestra_4310

**Comment by Alan32Liu** [comment]
Experiment `2023-09-27-orchestra-1` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-09-27-orchestra-1/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-09-27-orchestra-1/index.html).

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-25-orchestra-2 --fuzzers orchestra_aflplusplus orchestra_honggfuzz orchestra_libfuzzer pastis

**Comment by Alan32Liu** [comment]
Experiment `2023-09-25-orchestra-2` data and results will be available later at:
[The experiment data](https://storage.googleapis.com/fuzzbench-data/index.html?prefix=2023-09-25-orchestra-2/).
[The experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-09-25-orchestra-2/index.html).

**Comment by Alan32Liu** [comment]
> gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-25-orchestra-1 --fuzzers orchestra_236 orchestra_339 orchestra_4310 orchestra_219 orchestra_116

I reckon `orchestra_219` is actually `orchestra_216`?

**Comment by gtt1995** [comment]
Yes, dongge. The config of 216 is same as 219 when the total time budget less than 23h.



---Original---
From: "Dongge ***@***.***&gt;
Date: Wed, Sep 27, 2023 10:41 AM
To: ***@***.***&gt;;
Cc: "taotao ***@***.******@***.***&gt;;
Subject: Re: [google/fuzzbench] Orchesctra: A Collaborative Fuzzer Framework(PR #1904)




  
gcbrun run_experiment.py -a --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-09-25-orchestra-1 --fuzzers orchestra_236 orchestra_339 orchestra_4310 orchestra_219 orchestra_116
  
I reckon orchestra_219 is actually orchestra_216?

**Comment by Alan32Liu** [comment]
> Yes, dongge. The config of 216 is same as 219 when the total time budget less than 23h.

I meant there isn't a 219, is this intended?

**Comment by gtt1995** [comment]
Yes, you can delete 219, thanks.



---Original---
From: "Dongge ***@***.***&gt;
Date: Wed, Sep 27, 2023 18:34 PM
To: ***@***.***&gt;;
Cc: "taotao ***@***.******@***.***&gt;;
Subject: Re: [google/fuzzbench] Orchesctra: A Collaborative Fuzzer Framework(PR #1904)




  
Yes, dongge. The config of 216 is same as 219 when the total time budget less than 23h.
  
I meant there isn't a 219, is this intended?

**Pull request closed without merging**
