### PR TITLE
Workaround for #801

### PR DESCRIPTION
**Pull request by mboehme**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Can you please add entropic as well. Wish these could come back, since it affects rankings significantly.

**Comment by mboehme** [comment]
If this isn't very urgent, I can look at it properly within a week?

**Comment by inferno-chromium** [comment]
> If this isn't very urgent, I can look at it properly within a week?

Yes not urgent at all, whenever you get time. Ideally we want that patch to stablize so that we can get in LLVM and benefit all consumers in industry (similar to how entropic is default now).

**Comment by inferno-chromium** [comment]
> If this isn't very urgent, I can look at it properly within a week?

Yes not urgent at all, whenever you get time. Ideally we want that patch to stablize so that we can get in LLVM and benefit all consumers in industry (similar to how entropic is default now).

**Comment by mboehme** [comment]
Sure. Closing this then.

**Comment by jonathanmetzman** [comment]
> > If this isn't very urgent, I can look at it properly within a week?
> 
> Yes not urgent at all, whenever you get time. Ideally we want that patch to stablize so that we can get in LLVM and benefit all consumers in industry (similar to how entropic is default now).

Youre not saying we need to upstream everything before testing it right? I think it's fine (even better) to do the testing here first.

**Comment by inferno-chromium** [comment]
> > > If this isn't very urgent, I can look at it properly within a week?
> > 
> > 
> > Yes not urgent at all, whenever you get time. Ideally we want that patch to stablize so that we can get in LLVM and benefit all consumers in industry (similar to how entropic is default now).
> 
> Youre not saying we need to upstream everything before testing it right? I think it's fine (even better) to do the testing here first.

Yes +1. i mean we can test things here and let it stabilize here, before submitting an upstream patch to llvm. We have seen that this breaks [i had to do this disabling before https://www.fuzzbench.com/reports/experimental/2020-10-11-ossfuzzc/index.html] and causes libfuzzer/entropic to exit/crash when a number of seeds are used. So, in a way it is important to fix this, but it can wait a week or two, otherwise, we can just commit this one to temporarily disable it.

**Pull request closed without merging**
