### PR TITLE
bump libfuzzer

### PR DESCRIPTION
**Pull request by Navidem**

### CODE REVIEW

**Review by jonathanmetzman — COMMENTED** [review]
Do we need to do this?

**Comment by Navidem** [comment]
Oh, I thought you asked for it!

**Comment by jonathanmetzman** [comment]
Only if it's needed. If it's not needed, I'd rather not do this.

**Comment by Navidem** [comment]
well, my use-case is making a libfuzzer request for one benchmark to use as reference point for my own experiment.

**Comment by Navidem** [comment]
Actually, I wonder if this merged does `patch.diff` still applies correctly?!

**Comment by jonathanmetzman** [comment]
> Actually, I wonder if this merged does `patch.diff` still applies correctly?!

patch.diff isn't applied. You can make a PR to delte it.

**Pull request closed without merging**
