### PR TITLE
Fix libFuzzer based fuzzers argument order.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
This breaks in some way after seed corpus is used, e.g.
https://storage.googleapis.com/fuzzbench-data/2020-10-07-ossfuzzc/experiment-folders/harfbuzz-1.3.2-libfuzzer/trial-497073/results/fuzzer-log.txt

```
#338870: cov: 0 ft: 0 corp: 16249 exec/s 8258 oom/timeout/crash: 0/0/40 time: 61s job: 41 dft_time: 0
==570== ERROR: libFuzzer: deadly signal
No such file or directory: -ignore_ooms=1; exiting
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/out/fuzzer.py", line 44, in fuzz
    extra_flags=['-keep_seed=1', '-cross_over_uniform_dist=1'])
  File "/out/fuzzer.py", line 76, in run_fuzzer
    subprocess.check_call(command)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/out/hb-shape-fuzzer', '/out/corpus', '/out/seeds', '-print_final_stats=1', '-close_fd_mask=3', '-fork=1', '-ignore_ooms=1', '-ignore_timeouts=1', '-ignore_crashes=1', '-detect_leaks=0', '-keep_seed=1', '-cross_over_uniform_dist=1']' returned non-zero exit status 1.
```

**Comment by inferno-chromium** [comment]
TBR minor fix.

**Comment by inferno-chromium** [comment]
real issue was - https://github.com/google/fuzzbench/issues/801, but this is fine to fix anyway since that is also the order in docs.

**Comment by jonathanmetzman** [comment]
LGTM

**Pull request merged**
