### PR TITLE
new afl++ test run

### PR DESCRIPTION
**Pull request by vanhauser-thc**
This tests several afl++ enhancements in a single run:

* instrument also select() IR instructions (blind spot in fuzzing at the moment)
* final cmplog enhancement test
* new frida speed enhacement
* -O1 vs -O2 vs -O3 default optimization

edit: also adds aflplusplus_gcc as a new fuzzer but not part of this run.

Thanks!

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by vanhauser-thc** [comment]
A ton of websites fail because their certificate lifetime has ended, e.g.

```
#7 4.019 ERROR: cannot verify download.qemu.org's certificate, issued by 'CN=R3,O=Let\'s Encrypt,C=US':
#7 4.019   Issued certificate has expired.
```
already did a workaround for libpng in this PR, but it seems that now more and more are affected.

I think this is safe to merge, however the builds for fuzzing will fail for the same reason.

**Comment by jonathanmetzman** [comment]
> A ton of websites fail because their certificate lifetime has ended, e.g.
> 
> ```
> #7 4.019 ERROR: cannot verify download.qemu.org's certificate, issued by 'CN=R3,O=Let\'s Encrypt,C=US':
> #7 4.019   Issued certificate has expired.
> ```
> 
> already did a workaround for libpng in this PR, but it seems that now more and more are affected.
> 
> I think this is safe to merge, however the builds for fuzzing will fail for the same reason.

Sorry I'm not following this, why merge if the builds fail?

**Comment by vanhauser-thc** [comment]
I am saying it could be merged based on the MY code.
But merging now while several SSL certificates are invalid which leads to failed builds and therefore an incomplete benchmark this should not be merged yet.
I will push another commit to retrigger the CI to see if the SSL cert issues were resolved.

**Comment by vanhauser-thc** [comment]
SSL cert issues have been resolved except qemu.
this benchmark run can live without qemu being available, so this can be merged now. thanks!

if this can be merged asap that would be great, because I want to talk about this on our Tuesday call.

**Comment by vanhauser-thc** [comment]
@jonathanmetzman thank you! :)

**Pull request merged**
