### PR TITLE
Add canary project to CI

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Review by Alan32Liu — APPROVED** [review]
LGTM.
But just out of curiosity: Why do we choose `afl` (instead of `libfuzzer`) as a canary fuzzer?

**Comment by jonathanmetzman** [comment]
> LGTM. But just out of curiosity: Why do we choose `afl` (instead of `libfuzzer`) as a canary fuzzer?

libfuzzer clones all of llvm -> slow
AFL is probably the fastest fuzzer to build.

**Comment by Alan32Liu** [comment]
> > LGTM. But just out of curiosity: Why do we choose `afl` (instead of `libfuzzer`) as a canary fuzzer?
> 
> libfuzzer clones all of llvm -> slow AFL is probably the fastest fuzzer to build.

Ah that makes sense, thanks!

**Comment by jonathanmetzman** [comment]
> > > LGTM. But just out of curiosity: Why do we choose `afl` (instead of `libfuzzer`) as a canary fuzzer?
> > 
> > 
> > libfuzzer clones all of llvm -> slow AFL is probably the fastest fuzzer to build.
> 
> Ah that makes sense, thanks!

I've included this reasoning in a comment.

**Comment by jonathanmetzman** [comment]
I'm blocked on this PR and no failures are new so landing it.

**Pull request merged**
