### PR TITLE
Requesting experiments for new AFL schedules

### PR DESCRIPTION
**Pull request by mboehme**
In local experiments, I observed that AFL is spending a lot of time splicing inputs. During splicing, AFL takes one part of the source seed and one part of some other seed to generate a new input. AFL determines the time spent (perf_score) for the *source seed* but actually fuzzes the *new, spliced input*. Now, if the source seed exercises a rare path, AFLFast would boosts the perf_score and the spliced input seed (which might exercise a totally different path) would be fuzzed way too often. This experiment tests two schedules (i) to reduce the time spent splicing (`spliceless`) and (ii) to make the time spent splicing independent of the (boosted) perf_score (`spliceless2`).

There are two schedules to boost AFL performance (i) by faster hashing (`xxh3`) and (ii) by ignoring hit counts on the edges (`nohits_srsly`). With nohits_srsly, AFL takes (MAP_SIZE >> 3) instead of MAP_SIZE iterations to loop over the entire bitmap in the hot has_new_bits function. In the last experiment, the nohits schedule seemed to be particularly beneficial when the code base is large (e.g., sqlite3 with over 35k edges). Let's see if this is confirmed here. If so, a schedule could be developed that enables hit counts dynamically, e.g., only once there is saturation.

I also added another schedule, `fast_branches` that boosts based on branch frequency instead of path frequency. This is more space efficient and more naturally focusses on increasing edge coverage. The idea is very simple. AFL maintains a favourite seed for each edge, i.e., the fastest and smallest seed that exercises this edge. fast_branches` only considers rare edges (exercised less than 0xFF times) for favourites. As long as there are any favourites pending, skip to those with 99% probability.

Thanks Fuzzbench team!

EDIT:  I added two more schedules. Wanted to see spliceless on the schedule where "manual" boosting of late (and thus rare) seeds by up to 20x (handicap) is disabled, giving fast more leverage to boost.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Can you please merge and push again to get this - https://github.com/google/fuzzbench/commit/80822859e5198aced9aa19d6a4a37ffbd89e35dc

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
> Can you please merge and push again to get this - [8082285](https://github.com/google/fuzzbench/commit/80822859e5198aced9aa19d6a4a37ffbd89e35dc) Otherwise, hard to test CI.

If you can merge to head/master, that will bring two fixes and make CI work properly (not run into matio benchmark issues). Can you please do that, sorry for the hassle.

**Comment by mboehme** [comment]
Done. 

Note that I added two more schedules. Wanted to see `spliceless` on the schedule where "manual" boosting of late and this rare seeds by up to 20x (`handicap`) is disabled, giving fast more leverage to boost.

**Comment by jonathanmetzman** [comment]
LGTM

**Pull request merged**
