### PR TITLE
Bump up AFL_MAP_SIZE for afl++ variants.

### PR DESCRIPTION
**Pull request by inferno-chromium**
See https://github.com/google/fuzzbench/pull/874#issuecomment-726193650

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by inferno-chromium** [comment]
@vanhauser-thc can you fix aflplusplus_oldnew, or what git hash should i replace ef3a024a0cc9a09453833f908bc7d836ff292be1 with ?

```
#14 DONE 0.0s
#6 0.274 Cloning into '/afl'...
#6 1.491 fatal: reference is not a tree: ef3a024a0cc9a09453833f908bc7d836ff292be1
#6 ERROR: executor failed running [/bin/sh -c git clone https://github.com/AFLplusplus/AFLplusplus.git /afl &&     cd /afl &&     git checkout ef3a024a0cc9a09453833f908bc7d836ff292be1 &&     unset CFLAGS && unset CXXFLAGS && export CC=clang &&     AFL_NO_X86=1 PYTHON_INCLUDE=/ make && make install &&     make -C examples/aflpp_driver &&     cp examples/aflpp_driver/libAFLDriver.a /]: runc did not terminate sucessfully
------
 > importing cache manifest from gcr.io/fuzzbench/builders/aflplusplus_oldnew/arrow_parquet-arrow-fuzz-intermediate:
------
------
```

**Comment by vanhauser-thc** [comment]
ah sorry I have already deleted that branch, and didnt delete the fuzzer here ...

**Comment by inferno-chromium** [comment]
> ah sorry I have already deleted that branch, and didnt delete the fuzzer here ...

Sure can you please delete those when you have time.

Also, somethings up with your old python version, can you please check using "make run-aflplusplus_dict2file-systemd_fuzz-link-parser"
```
2020-11-12T22:16:30.9201735Z #16 7.144 meson.build:626:16: ERROR: Problem encountered: unable to determine gperf len type
2020-11-12T22:16:30.9202224Z #16 7.144 
2020-11-12T22:16:30.9203458Z #16 7.144 A full log can be found at /work/build/meson-logs/meson-log.txt
2020-11-12T22:16:30.9204200Z #16 7.144 NOTICE: You are using Python 3.5 which is EOL. Starting with v0.57, Meson will require Python 3.6 or newer
2020-11-12T22:16:31.5103520Z #16 7.639 Traceback (most recent call last):
2020-11-12T22:16:31.5104045Z #16 7.639   File "<string>", line 1, in <module>
2020-11-12T22:16:31.5105064Z #16 7.639   File "/src/fuzzers/aflplusplus_dict2file/fuzzer.py", line 28, in build
2020-11-12T22:16:31.5106082Z #16 7.640     aflplusplus_fuzzer.build("tracepc", "dict2file")
2020-11-12T22:16:31.5106852Z #16 7.640   File "/src/fuzzers/aflplusplus/fuzzer.py", line 126, in build
2020-11-12T22:16:31.5107370Z #16 7.640     utils.build_benchmark()
2020-11-12T22:16:31.5107877Z #16 7.640   File "/src/fuzzers/utils.py", line 68, in build_benchmark
2020-11-12T22:16:31.5109064Z #16 7.640     subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
2020-11-12T22:16:31.5109706Z #16 7.640   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
2020-11-12T22:16:31.5110335Z #16 7.640     raise CalledProcessError(retcode, cmd)
2020-11-12T22:16:31.5111777Z #16 7.640 subprocess.CalledProcessError: Command '['/bin/bash', '-ex', '/src/build.sh']' returned non-zero exit status 1.
2020-11-12T22:16:31.6035768Z #16 ERROR: executor failed running [/bin/sh -c PYTHONPATH=$SRC python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.$FUZZER import fuzzer; fuzzer.build()"]: runc did not terminate sucessfully
2020-11-12T22:16:31.6037099Z ------
2020-11-12T22:16:31.6038210Z  > [stage-1 12/12] RUN PYTHONPATH=/src python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.aflplusplus_dict2file import fuzzer; fuzzer.build()":
2020-11-12T22:16:31.6039138Z ------
2020-11-12T22:16:31.6040631Z failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c PYTHONPATH=$SRC python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.$FUZZER import fuzzer; fuzzer.build()"]: runc did not terminate sucessfully
2020-11-12T22:16:31.6094904Z make: *** [.aflplusplus_dict2file-systemd_fuzz-link-parser-builder] Error 1
```

**Comment by inferno-chromium** [comment]
> make run-aflplusplus_dict2file-systemd_fuzz-link-parser
@vanhauser-thc 
Ignore my last comment part about python issue, looks like it is benchmark issue, i will fix later.

**Pull request merged**
