### PR TITLE
Remaining experiments for the Dissecting AFL paper

### PR DESCRIPTION
**Pull request by andreafioraldi**
These are the remaining bug-based experiments for the Dissecting AFL paper.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
send me an email when you want this merged, because i assume CI wil fail somewhere and this won't be automerged.
Ummm...the bug experiments have been not working so well lately btw.

**Comment by jonathanmetzman** [comment]
It seems I can't turn on automerge? I wonder what's going on

**Comment by andreafioraldi** [comment]
> send me an email when you want this merged, because i assume CI wil fail somewhere and this won't be automerged. Ummm...the bug experiments have been not working so well lately btw.

no that's presubmit, if forgot a newline by mistake. let's wait the CI, I'm not sure all the variants works with all the benchs

**Comment by andreafioraldi** [comment]
```
************* Module experiment.scheduler
experiment/scheduler.py:688:0: R0913: Too many arguments (6/5) (too-many-arguments)
experiment/scheduler.py:730:0: R0913: Too many arguments (6/5) (too-many-arguments)
```
This is not on me in presubmit

**Comment by andreafioraldi** [comment]
afl standard is failing with `#6 0.562 fatal: unable to access 'https://gitlab.gnome.org/GNOME/libxml2.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`

**Comment by jonathanmetzman** [comment]
> ```
> ************* Module experiment.scheduler
> experiment/scheduler.py:688:0: R0913: Too many arguments (6/5) (too-many-arguments)
> experiment/scheduler.py:730:0: R0913: Too many arguments (6/5) (too-many-arguments)
> ```
> 
> This is not on me in presubmit. I guess it can be related to #1384

Fixing this now. You'll need to pull and push after I merge https://github.com/google/fuzzbench/pull/1393

**Comment by jonathanmetzman** [comment]
Nevermind. You don't need to pull.

**Comment by jonathanmetzman** [comment]
Most have ~20 trials per fuzzer.
You need to click on "sample statistics" drop down on each benchmark to see trials per fuzzer.
The number you're seeing is the minimum number of trials that finished for any fuzzer.
This frequently seems to be afl_splicing_mutation which frequently has 5/6 finished trials. I would guess this fuzzer is broken somehow. Maybe check the logs.
But most of the other fuzzers have a sufficient number that finished.

**Pull request merged**
