### PR TITLE
Adding experiments and fixing fuzzers

### PR DESCRIPTION
**Pull request by kjain14**
Fixing _um fuzzers for aflplusplus and honggfuzz. Also adding experiment needed for the First, Fuzz the Mutants paper.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
There's gonna be a few issues/delays running this.
1. Were in the middle of the competition and have been having some quota issues.
2. We had to rollback some changes we made to allow the mutants fuzzers to work because they were breaking our quota limits: these were concurrent builds and disk size

**Comment by jonathanmetzman** [comment]
@Alan32Liu can you please start an experiment with these fuzzers using GCB.
You will need to re-add the code upping the number of builders and disk sizes.
```
- experiment: 2023-03-13-aflpp-um
  description: "afl++ um experiments."
  fuzzers:
    - aflplusplus
    - aflplusplus_um_random
    - aflplusplus_um_prioritize
    - aflplusplus_um_parallel
    - aflplusplus_um_prioritize_75
    - aflplusplus_um_random_75
    - ```

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml  --experiment-name 2023-03-13-aflpp-um --fuzzers aflplusplus aflplusplus_um_random aflplusplus_um_prioritize aflplusplus_um_parallel aflplusplus_um_prioritize_75 aflplusplus_um_random_75 -a

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-03-13-aflpp-um --fuzzers aflplusplus aflplusplus_um_random aflplusplus_um_prioritize aflplusplus_um_parallel aflplusplus_um_prioritize_75 aflplusplus_um_random_75 -a

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-03-13-aflpp-um --fuzzers aflplusplus aflplusplus_um_random aflplusplus_um_prioritize aflplusplus_um_parallel aflplusplus_um_prioritize_75 aflplusplus_um_random_75 -a

**Comment by jonathanmetzman** [comment]
kjain how do these results look? https://www.fuzzbench.com/reports/experimental/2023-03-13-aflpp-um/index.html

**Comment by jonathanmetzman** [comment]
(I'm not sure why libafl and other fuzzers were included there, maybe due to our automerging)

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-04-08-aflpp-um --fuzzers  aflplusplus_um_parallel aflplusplus aflplusplus_um_random aflplusplus_um_random_75 aflplusplus_um_prioritize aflplusplus_um_prioritize_75 -a

**Comment by Alan32Liu** [comment]
[Coverage experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-04-07-intro-cov/index.html).

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-04-08-aflpp-um --fuzzers aflplusplus_um_parallel aflplusplus aflplusplus_um_random aflplusplus_um_random_75 aflplusplus_um_prioritize aflplusplus_um_prioritize_75 -a

**Comment by Alan32Liu** [comment]
The [experiment data](https://pantheon.corp.google.com/storage/browser/fuzzbench-data/2023-04-08-aflpp-um?project=fuzzbench&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) and [experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-04-08-aflpp-um/index.html).

**Pull request closed without merging**
