### PR TITLE
libafl experiment

### PR DESCRIPTION
**Pull request by vanhauser-thc**
tests previous libafl vs libafl with afl-map + unstable edge detection.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
weird that the same code parts succeed in one and fail in another.
but that is not important for the tests, this can be merged :)

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
Github's interface doesn't seem like it will let me merge this without CI finishing. I need to figure out a way around this.
bug

**Comment by vanhauser-thc** [comment]
> Github's interface doesn't seem like it will let me merge this without CI finishing. I need to figure out a way around this. bug

for me it always works by ticket the box (like it is in the picture) and hitting the merge button. the text says otherwise but the tick text says it would work.

but doesnt matter, it is not urgent.

**Pull request merged**
