### PR TITLE
[NO MERGE] experimental pure local running support

### PR DESCRIPTION
**Pull request by zchcai**
Hi, this branch is an initial working plan for a pure running support in Linux hosts. (No GCS needed)

However, this support involves a lot of files to change, and we are trying to refactor and split this PR into several PRs to merge into `master` branch.

This PR is not for merging, but a reminder for current active PRs for local support. They are:
- refactor: `filetore_utils` interface for `gsutil`. In future, we can add `local_utils` or other `<file_storage>_utils`. #394
- refactor, minor change: support new configuration options, and rename most `cloud_*` (#402)
- `*gcs*` related path conversion: it will not affect functional behavior and thus no change now.
- new feature: add `local_utils` (for linux) and related unit tests. (#405)
- add `rsync` support #406 
- add some error handling logic: this is related to SQL distinct, fixed in #444.
- local dispatcher logic change
- final integration switching on: #422 (filestore_utils), #440 (local rsync fix), #441 (set env for local running), #444 (fix SQL error and enable end-to-end run).

### CODE REVIEW

**Comment by zchcai** [comment]
Here is the comparison at that moment.

https://github.com/zchcai/fuzzbench/compare/5d8feaa...1918184

**Comment by zchcai** [comment]
To have a try, the running scripts shall be the following:

Before starting, please [install docker](https://docs.docker.com/engine/install/) and set it able to [run without sudo](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user).

1. get the initial pure local support code
```
git clone -b filesys https://github.com/zchcai/fuzzbench.git && cd fuzzbench
```
2. [prerequisites](https://google.github.io/fuzzbench/getting-started/prerequisites/)
```
git submodule update --init
sudo apt-get install -y build-essential python3-dev python3-venv
make install-dependencies
```
3. prepare local config file, replace `local_*` paths to two different absolute paths. Cloud-related configs (except `cloud_project`) are redundant but need to preserve now in this file. `gsutil_disabled` will switch the running to pure local.
```
cat experiment-config.yaml

trials: 1
max_total_time: 600
cloud_project: fuzzbench
cloud_compute_zone: us-central1-a
cloud_experiment_bucket: gs://shouldnotbeused
cloud_web_bucket: gs://shouldnotbeused
local_experiment_bucket: <absolute_path_to>/fuzzbench-data
local_web_bucket: <absolute_path_to>/fuzzbench-reports
cloud_sql_instance_connection_name: "fuzzbench:us-central1:postgres-experiment-db=tcp:5432"
local_experiment: true
gsutil_disabled: true
```
4. run with an different experiment name each time. `benchmark_names` and `fuzzer_names` should change to valid folder names under `benchmarks` and `fuzzers`.
```
source .venv/bin/activate
export FORCE_LOCAL=1
PYTHONPATH=. python3 experiment/run_experiment.py --experiment-config experiment-config.yaml --benchmarks <benchmark_names> --experiment-name local_test_name --fuzzers <fuzzer_names>
```
For example,
PYTHONPATH=. python3 experiment/run_experiment.py --experiment-config experiment-config.yaml --benchmarks freetype2-2017 --experiment-name local_test_name --fuzzers aflplusplus
```
5. Later, we can open the HTML report under `fuzzbench_report` folder.
```

**Comment by lszekeres** [comment]
It's really nice having these instructions here, thanks! (It will also serve as a good draft for the documentation when all of this is landed.)

Btw, are you planning to merge these:

> cloud_experiment_bucket: gs://shouldnotbeused
> local_experiment_bucket: <absolute_path_to>/fuzzbench-data

> cloud_web_bucket: gs://shouldnotbeused
> local_web_bucket: <absolute_path_to>/fuzzbench-reports

into something like `experiment_data_directory` and `reports_directory`?

**Comment by zchcai** [comment]
This PR is not for merging and the instructions are not for final documentation. Instead, I put them here for any one interested for running a test.

Yes. I have plans to add alternatives for those options. I will link that PR here when I create it.

**Comment by vanhauser-thc** [comment]
I/we are interested in running local experiments as we got a 24 core server sponsored :)
@zchcai is your branch working and can be used for experiments?

**Comment by vanhauser-thc** [comment]
and a question - how does this scale? how can I set the maximum number of parallel tests being performed?

**Comment by zchcai** [comment]
> and a question - how does this scale? how can I set the maximum number of parallel tests being performed?

Thanks for your interests and bring this up! Unfortunately, this branch has no configuration to limit CPU or memory usages for the host machine and it will almost use up computing resources during building and running docker images.
However, these days our team are also working on a design for supporting limited computing resources during the whole experiment period. Please stay in tune.

**Comment by zchcai** [comment]
> is your branch working and can be used for experiments?
This branch still raises some issues during multi-trials running. Please stay in tune.

**Comment by zchcai** [comment]
> how does this scale?

Consider *B* benchmarks, *F* fuzzers, *W* trials (i.e., one trial is one running for a pair of benchmark and fuzzer), *T* total seconds for each trial, and *I* seconds for logging corpus for final coverage report:
- *B* and *F*:
  - through the command line options `--benchmarks` and `--fuzzers`. For example, `--benchmarks bloaty_fuzz_target curl_curl_fuzzer_http --fuzzers afl libfuzzer`.
- *W* and *T*:
  - in the `experiment-config.yaml`, `trials` and `max_total_time`. (sec)
- *I*:
  - https://github.com/zchcai/fuzzbench/blob/filesys/common/experiment_utils.py#L21

**Comment by zchcai** [comment]
Refer to #459 for latest local running command. This PR draft is closed.

**Pull request closed without merging**
