### PR TITLE
Libafl new experiment

### PR DESCRIPTION
**Pull request by andreafioraldi**
@jonathanmetzman we are quite in a hurry for the paper, if you can start it ASAP (after green CI) would be great

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Looks like the instrumentation pass is having some issues. Should I merge anyway?

**Comment by jonathanmetzman** [comment]
I'm gonna merge since failure is on bug based benchmark and this request is for coverage.

**Comment by jonathanmetzman** [comment]
Yeah I think the ffmpeg benchmark is using a different docker image than all the other benchmarks: https://github.com/google/fuzzbench/pull/1244

**Comment by andreafioraldi** [comment]
hey @jonathanmetzman do you know why entropic is not running on many targets? https://www.fuzzbench.com/reports/experimental/2022-04-11-libafl/index.html

**Comment by jonathanmetzman** [comment]
I think entropic started showing up right?

**Pull request merged**
