### PR TITLE
aflpp introspection

### PR DESCRIPTION
**Pull request by vanhauser-thc**
can this please be run on the sbft23 bug benchmark again? thank you!!

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
or better the sbft23 coverage one too ;-) ... the new implementation gets much more precise results but the price is very slow coverage gains ...

**Comment by Alan32Liu** [comment]
cov experiment seems to work, bug experiment was not (maybe due to I launched cov too quickly).
Re-launch bug now

**Comment by Alan32Liu** [comment]
/gcbrun run_experiment.py --experiment-config /opt/fuzzbench/service/experiment-config.yaml --experiment-name 2023-04-07-intro-bug --fuzzers aflpp_introspection --benchmarks arrow_arrow-ipc-stream-fuzz_1a34a0 aspell_aspell_fuzzer_e8eb74 assimp_assimp_fuzzer_4d451f bloaty_fuzz_target_52948c ffmpeg_ffmpeg_demuxer_fuzzer_7adeef file_magic_fuzzer_2d5f85 grok_grk_decompress_fuzzer_9cd001 harfbuzz_hb-shape-fuzzer_17863b lcms_cms_transform_all_fuzzer_97d37d libaom_av1_dec_fuzzer_6e1848 libpcap_fuzz_filter_98b0a2 libxml2_xml_e85b9b mbedtls_fuzz_dtlsclient_7c6b0e php_php-fuzz-parser_0dbedb systemd_fuzz-network-parser_288baf -a

**Comment by Alan32Liu** [comment]
[Coverage experiment report](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-04-07-intro-cov/index.html).

**Comment by vanhauser-thc** [comment]
thanks a lot!

can you please look at https://www.fuzzbench.com/reports/experimental/2023-04-05-aflpp/index.html ?
the report has not been updated for 12 hours, but when look at gs://fuzzbench-data/2023-04-05-aflpp/experiment-folders/ both show that all trials have been completed.
I think just the report generation has to be triggered.
the data.csv.gz is also from the 12:30h mark.

**Comment by vanhauser-thc** [comment]
> can you please look at https://www.fuzzbench.com/reports/experimental/2023-04-05-aflpp/index.html ? the report has not been updated for 12 hours, but when look at gs://fuzzbench-data/2023-04-05-aflpp/experiment-folders/ both show that all trials have been completed. I think just the report generation has to be triggered. the data.csv.gz is also from the 12:30h mark.

sorry that just took half a day to generate the final report, it is done.

**Comment by vanhauser-thc** [comment]
thank you!

**Pull request closed without merging**
