### PR TITLE
KLEE fixes.

### PR DESCRIPTION
**Pull request by inferno-chromium**
- Add max memory limit.
- Remove hack for fuzz target, pass it using env var.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Still testing in a live experiment.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by inferno-chromium** [comment]
It does not stop OOMs (obviously :), but good change anyway to remove fuzz target hack, so committing.

**Comment by lszekeres** [comment]
> It does not stop OOMs (obviously :), but good change anyway to remove fuzz target hack, so committing.

The -max-memory value is more like a soft limit than a hard one, it's used to prevent adding more paths/states if we're over it:
https://github.com/klee/klee/blob/3983b23eac93b0e6f28ffba4b626401c5280c10f/lib/Core/Executor.cpp#L2965

Consider setting something like 1gb, and perhaps that way we won't go over 3gb :)

**Comment by inferno-chromium** [comment]
> > It does not stop OOMs (obviously :), but good change anyway to remove fuzz target hack, so committing.
> 
> The -max-memory value is more like a soft limit than a hard one, it's just used to prevent adding more paths/states if we're over it:
> https://github.com/klee/klee/blob/3983b23eac93b0e6f28ffba4b626401c5280c10f/lib/Core/Executor.cpp#L2965
> 
> Consider setting something like 1gb, and perhaps that way we won't go over 3gb :)

Ok started 2020-10-07-klee experiment with 1 gb, lets see how it goes.

**Pull request merged**
