### PR TITLE
New experiment for libafl

### PR DESCRIPTION
**Pull request by andreafioraldi**
Inspecting the previous run on FuzzBench we found and fixed several bugs, let's test the fixes now

### CODE REVIEW

**Comment by andreafioraldi** [comment]
It builds for coverage experiments, for bug ffmpeg fails because Rust is not installed, but it should be.
Anyway, I requested a coverage experiment so I don't care ATM.

**Review by inferno-chromium — APPROVED** [review]

**Comment by andreafioraldi** [comment]
Any problems with the start of this experiment? Broken things from my side?

**Comment by andreafioraldi** [comment]
@inferno-chromium ping

**Comment by jonathanmetzman** [comment]
Sorry, I need to look into this.

**Comment by jonathanmetzman** [comment]
I think I fixed the issue.

**Pull request merged**
