### PR TITLE
Don't build python for no reason. Copy it

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Not sure why even switched to building it.

**Comment by jonathanmetzman** [comment]
> Not sure why even switched to building it.

One thing this may exacerbate: we may mess with the state of Python as it was left by the benchmark's Dockerfile

**Comment by jonathanmetzman** [comment]
Fixes https://github.com/google/fuzzbench/issues/1659

**Comment by jonathanmetzman** [comment]
TBR

**Review by Alan32Liu — COMMENTED** [review]
LGTM

**Pull request merged**
