### PR TITLE
Request new experiment for AFL variants 

### PR DESCRIPTION
**Pull request by jiradeto**
Hi, I would like to add new AFL-based fuzzers into the repo and also request a new experiment to benchmark them against the afl. 

Thanks

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Thanks for this. I'll take a look at this tomorrow.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
Can you fix the merge conflicts please?

**Comment by jiradeto** [comment]
Fixed, thank you.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
