### PR TITLE
change defaults, new temporary tests

### PR DESCRIPTION
**Pull request by vanhauser-thc**
this moves the _shmem variants to be the normal defaults. also adds new tests variants. these have been in before however there were several changes so I expect differences. also the autodict feature is a new test.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
a few benchmarks e.g. curl might fail as they take very long and can therefore trigger timeouts. I would not care in the experience if that happens.

**Comment by jonathanmetzman** [comment]
sounds good to me. Should I wait for CI to finish or go ahead and merge?

**Comment by vanhauser-thc** [comment]
ah lets wait. maybe I overlooked a benchmark that needs the dynamic flag for LTO - was changed it now would need it

**Comment by vanhauser-thc** [comment]
but can you please merge reports 2020-06-30 into 2020-06-26 (overwriting the aflplusplus_optimal_shmem from ...-26) and the merge this to 2020-05-24? thanks!

the one you just started have not the _shmem variant which is the new default :)

**Comment by vanhauser-thc** [comment]
btw the first oss-fuzz completed successfully from the LTO variants so all is fine and it can be merged.

**Comment by vanhauser-thc** [comment]
and one last thing before going to bed - afl had several updates, commit id is 82b5e359463238d790cadbe2dd494d6a4928bff3 and also mopt, commit id is 61cdee22a9dc0f638d2a200c0d460c699e8500e0

**Comment by jonathanmetzman** [comment]
We're running a large scale experiment using clang coverage right now so it might be a day or so before I get to run this.

**Comment by jonathanmetzman** [comment]
I merged the reports as you asked. See https://www.fuzzbench.com/reports/2020-06-30-and-05-24/index.html and https://www.fuzzbench.com/reports/2020-06-30/index.html

**Comment by vanhauser-thc** [comment]
> I merged the reports as you asked. See https://www.fuzzbench.com/reports/2020-06-30-and-05-24/index.html and https://www.fuzzbench.com/reports/2020-06-30/index.html

Thank you! This is for the update of the paper

**Comment by vanhauser-thc** [comment]
> We're running a large scale experiment using clang coverage right now so it might be a day or so before I get to run this.

as long as it is finished before the 24th ... no hurry ... :)
(it is also for the paper)

is the "clang coverage" new coverage measurement (the gcov style instead of sanitize-coverage)?

**Comment by jonathanmetzman** [comment]
> > We're running a large scale experiment using clang coverage right now so it might be a day or so before I get to run this.
> 
> as long as it is finished before the 24th ... no hurry ... :)
> (it is also for the paper)

I think this should be doable.

> 
> is the "clang coverage" new coverage measurement (the gcov style instead of sanitize-coverage)?

Yes.

**Pull request merged**
