### PR TITLE
compare two different afl++ customized versions (dd and no dd)

### PR DESCRIPTION
**Pull request by elManto**
This experiment compares two different instrumentations on top of afl++

### CODE REVIEW

**Comment by elManto** [comment]
@googlebot I signed it!

**Comment by inferno-chromium** [comment]
Currently fuzzbench infra is running several experiments, we will be able to do this sometime next week.

**Review by jonathanmetzman — APPROVED** [review]
Thanks for waiting. I'll merge this if CI passes.

**Comment by elManto** [comment]
The CI killed the bench on the bug but I verified locally that all the projects build

**Pull request merged**
