### PR TITLE
new testcache test

### PR DESCRIPTION
**Pull request by vanhauser-thc**
I made two changes to the testcase cache mechanism hoping for better performance :)

### CODE REVIEW

**Comment by inferno-chromium** [comment]
just a heads up, this pr experiment request change will conflict with https://github.com/google/fuzzbench/pull/859, and i will merge that in first. i think i can update experiment requests by editing stuff here, otherwise will ask you.

**Comment by inferno-chromium** [comment]
note that experiment name will be 2020-10-23-2 due to conflict, i have fixed this.

**Comment by vanhauser-thc** [comment]
thanks! so busy fuzzing weekend :) 
btw what are your working hours? you seem to be online constantly

**Comment by jonathanmetzman** [comment]
> thanks! so busy fuzzing weekend :)
> btw what are your working hours? you seem to be online constantly

Don't tell anyone but Abhishek is actually a team of people not just one, that is how he is so productive :-)

**Comment by inferno-chromium** [comment]
> thanks! so busy fuzzing weekend :)
> btw what are your working hours? you seem to be online constantly

i am usually online throughout the day (pst time). this week was fun, but our automation on experiment runs helps quite a bit. just need to figure out this conflict with changes in single file. maybe will add some seperator and focus on dates-suffix to avoid conflicts.

**Pull request merged**
