### PR TITLE
Remove wabt_wasm2wat_fuzzer as continuously crashes.

### PR DESCRIPTION
**Pull request by inferno-chromium**
This benchmark is unusable for crash measurement since crashes
every milliseconds causing thousands of crash files build up
and makes measuring infeasible.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@Vaush - just fyi, this one is unusable, so removing. rest are ok, testing in http://commondatastorage.googleapis.com/fuzzbench-reports/2020-11-153-bug/index.html. for arrow one, it works after https://github.com/google/fuzzbench/pull/955

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by Vaush** [comment]
> 
> 
> @Vaush - just fyi, this one is unusable, so removing. rest are ok, testing in http://commondatastorage.googleapis.com/fuzzbench-reports/2020-11-153-bug/index.html. for arrow one, it works after #955

Perfect. By what I see the test still doesn't involve crash gathering, right?

**Comment by inferno-chromium** [comment]
> > @Vaush - just fyi, this one is unusable, so removing. rest are ok, testing in http://commondatastorage.googleapis.com/fuzzbench-reports/2020-11-153-bug/index.html. for arrow one, it works after #955
> 
> Perfect. By what I see the test still doesn't involve crash gathering, right?

it is gathering crashes, see https://github.com/google/fuzzbench/pull/934#issuecomment-728123014 for example url - https://console.cloud.google.com/storage/browser/fuzzbench-data/2020-11-153-bug/experiment-folders/harfbuzz_hb-subset-fuzzer-afl/trial-626061/crashes?authuser=0&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

we dont show in report yet as we have to still work on visualization.

**Comment by Vaush** [comment]
I see, fantastic. Thanks for the explanation

**Pull request merged**
